/** 集中维护下游 Harness 升级器不可弱化的协议常量。 */

import path from "node:path";

export const SCHEMA_VERSION = 2;
export const OWNERSHIP_RELATIVE = path.join(".agents", "skills", "desktop-upgrade-harness", "references", "ownership-manifest.json");
export const LOCK_RELATIVE = path.join(".harness", "upstream-lock.json");
export const VALID_MODES = new Set(["managed", "managed-self", "merge-sections", "conditional", "protected", "tombstone"]);
export const AUTO_MODES = new Set(["managed", "managed-self"]);
export const BLOCKING_CLASSES = new Set(["bootstrap_conflict", "collision", "conflict", "protected_candidate", "tombstone_candidate", "tombstone_present"]);
export const MANUAL_CLASSES = new Set(["add", "delete", "manual_add", "manual_merge"]);
export const REQUIRED_MANAGED_SOURCE_PATHS = [
  ".agents/skills/desktop-implement-change/scripts/check_file_line_limits.mjs",
  ".agents/skills/desktop-implement-change/scripts/check_file_line_limits.test.mjs",
  ".agents/skills/desktop-implement-change/scripts/check_core_first.mjs",
  ".agents/skills/desktop-implement-change/scripts/check_core_first.test.mjs",
  ".agents/skills/desktop-implement-change/scripts/check_rust_chinese_comments.mjs",
  ".agents/skills/desktop-implement-change/scripts/check_rust_chinese_comments.test.mjs",
  ".agents/skills/desktop-manage-git-lifecycle/SKILL.md",
  ".agents/skills/desktop-manage-git-lifecycle/agents/openai.yaml",
  ".agents/skills/desktop-manage-git-lifecycle/scripts/git_lifecycle.mjs",
  ".agents/skills/desktop-manage-git-lifecycle/scripts/git_lifecycle_core.mjs",
  ".agents/skills/desktop-manage-git-lifecycle/scripts/git_lifecycle_publication.mjs",
  ".agents/skills/desktop-manage-git-lifecycle/scripts/git_publication_report.mjs",
  ".agents/skills/desktop-manage-git-lifecycle/scripts/git_lifecycle_test_support.mjs",
  ".agents/skills/desktop-manage-git-lifecycle/scripts/git_publication_test_cases.test.mjs",
  ".agents/skills/desktop-manage-git-lifecycle/scripts/git_lifecycle.test.mjs",
  ".agents/skills/desktop-manage-git-lifecycle/scripts/git_lifecycle_release.test.mjs",
];

export const MINIMUM_OWNERSHIP_RULES = new Map([
  ["Version.md", "tombstone"],
  [".agents/skills/desktop-instantiate-project/**", "tombstone"],
  [".agents/skills/desktop-initialize-rust-project/**", "tombstone"],
  [".agents/skills/desktop-test-gui-initialization-e2e/**", "tombstone"],
  ["scripts/validate_harness.mjs", "tombstone"],
  ["scripts/run_harness_tests.mjs", "tombstone"],
  ["scripts/agile_workflow.test.mjs", "tombstone"],
  ["scripts/harness_scope_and_initialization_boundaries.test.mjs", "tombstone"],
  ["scripts/validate_harness.test.mjs", "tombstone"],
  ["scripts/harness_validation/**", "tombstone"],
  ["docs/HARNESS_ENGINEERING.md", "tombstone"],
  ["docs/harness_engineering/**", "tombstone"],
  ["docs/AGENT_POLICY.md", "protected"],
  ["docs/GUI_SUPPORT_SURFACES.md", "protected"],
  ["docs/product_spec/**", "protected"],
  ["docs/project_status/**", "protected"],
  ["docs/work_plan/**", "protected"],
  ["docs/adr/**", "protected"],
  ["docs/changelog/**", "protected"],
  ["docs/VERIFICATION.md", "protected"],
  ["docs/verification/**", "protected"],
  ["docs/TECH_DEBT.md", "protected"],
  [".harness/version-state.json", "protected"],
  [".harness/release-context.json", "protected"],
  ["release-notes.json", "protected"],
  ["LICENSE.zh-CN.md", "protected"],
  ["LICENSE.en.md", "protected"],
  ["Cargo.toml", "protected"],
  ["Cargo.lock", "protected"],
  [".gitignore", "protected"],
  ["AGENTS.md", "merge-sections"],
  ["README.md", "merge-sections"],
  ["docs/ENGINEERING_RULES.md", "merge-sections"],
  ["docs/RUST_CLI_TEMPLATE.md", "merge-sections"],
  ["docs/CLI_CONTRACT.md", "merge-sections"],
  ["docs/RELEASE.md", "merge-sections"],
  ["docs/design_standards/**", "managed"],
  [".agents/skills/desktop-implement-change/scripts/check_file_line_limits.mjs", "managed"],
  [".agents/skills/desktop-implement-change/scripts/check_file_line_limits.test.mjs", "managed"],
  [".agents/skills/desktop-implement-change/scripts/check_core_first.mjs", "managed"],
  [".agents/skills/desktop-implement-change/scripts/check_core_first.test.mjs", "managed"],
  [".agents/skills/desktop-implement-change/scripts/check_rust_chinese_comments.mjs", "managed"],
  [".agents/skills/desktop-implement-change/scripts/check_rust_chinese_comments.test.mjs", "managed"],
  [".agents/skills/desktop-manage-git-lifecycle/**", "managed"],
  [".agents/skills/desktop-upgrade-harness/**", "managed-self"],
  [".agents/skills/desktop-add-cli-adapter/**", "conditional"],
  [".agents/skills/desktop-add-tui-adapter/**", "conditional"],
  [".agents/skills/desktop-add-mcp-adapter/**", "conditional"],
  [".agents/skills/desktop-add-gui-adapter/**", "conditional"],
  [".agents/skills/mantine-list-view/**", "conditional"],
  [".agents/skills/desktop-add-gui-system-locale/**", "conditional"],
  [".agents/skills/desktop-add-gui-updater/**", "conditional"],
  [".agents/skills/desktop-add-gui-window-state/**", "conditional"],
  [".agents/skills/desktop-add-gui-dialog/**", "conditional"],
  [".agents/skills/desktop-add-gui-system-tray/**", "conditional"],
  [".agents/skills/desktop-add-gui-single-instance/**", "conditional"],
  [".agents/skills/desktop-add-gui-deep-link/**", "conditional"],
  [".agents/skills/desktop-add-gui-global-shortcut/**", "conditional"],
  [".agents/skills/desktop-add-gui-system-notifications/**", "conditional"],
  [".agents/skills/desktop-add-gui-autostart/**", "conditional"],
  [".agents/skills/desktop-prepare-gui-app-identity/**", "conditional"],
  [".agents/skills/desktop-prepare-gui-support-surfaces/**", "conditional"],
  [".agents/skills/desktop-prepare-cross-platform-release/**", "conditional"],
  [".agents/skills/desktop-build-tauri-local-install/**", "conditional"],
  [".agents/skills/desktop-build-tauri-release/**", "conditional"],
  [".agents/skills/**", "managed"],
]);

export const VERSION_PATTERN = /当前版本[：:]\s*`([^`]+)`/u;
