"""校验工程治理、并行协作、当前描述与版本事实契约。"""

from __future__ import annotations

import re
from pathlib import Path

from .context import *  # noqa: F403
from .governance_descriptions import (
    validate_current_descriptions,
    validate_stale_fragments,
)
from .governance_policy import validate_agent_policy
from .governance_version import validate_version_contract as _validate_version_contract


AGENTS_ENTRYPOINT = ROOT / "AGENTS.md"
AGENTS_MAX_UTF8_BYTES = 20_000
AGENTS_MAX_LINES = 120
AGENTS_REQUIRED_HEADINGS = (
    "## 项目使命",
    "## 启动门禁",
    "## 按任务渐进读取",
    "## 始终生效的边界",
    "## Skills 地图",
    "## 约束地图",
    "## 每次任务的最小闭环",
)
AGENTS_PROGRESSIVE_DISCLOSURE_FRAGMENTS = (
    "先判定任务类型",
    "只读取下表命中的事实来源和 Skill",
    "发现冲突或缺失时才扩大读取",
    "不要为了“完整”加载全部项目记忆、设计标准、发布规则或 Skills",
    "不得一次加载全部 GUI Skills",
    "命中后必须完整读取对应 `SKILL.md`",
)
AGENTS_SOURCE_GATE_FRAGMENTS = (
    "Harness 源范围门禁",
    "只接受 Harness 自身工程维护",
    "产品目的、业务功能、产品专属 UI/文案/数据",
    "一律不得在当前模板源中接收、分析、记录或实施",
    "切换到已存在终端下游的唯一根目录后重新提出",
)
AGENTS_ALWAYS_ON_BOUNDARY_FRAGMENTS = (
    "`superpowers: disabled`",
    "`{Task}|{序号}|{功能摘要}{当前进度}`",
    "`已分配`、`运行中`、`检查中`、`已完成`",
    "不阻断已经完成的任务结果",
    "安全/隐私、数据迁移、破坏性操作",
    "规格不明确且不同答案会改变产品边界时停止并确认",
    "Core-first 是硬规则",
    "对产出物声称“完成”“可用”或“已验证”",
    "不覆盖或撤销用户已有修改",
)
AGENTS_MINIMUM_CLOSURE_FRAGMENTS = (
    "只读取路由命中的最少事实与 Skills",
    "只运行本次变化需要的测试或最小替代检查",
    "只更新被独立事件触发的权威记录",
    "实际验证、未执行项和剩余风险",
    "python3 -B scripts/validate_harness.py",
)


def validate_agents_entrypoint(
    errors: list[str],
    path: Path = AGENTS_ENTRYPOINT,
) -> None:
    """校验根 Agent 入口保持轻量，并以渐进披露路由到详细事实源。"""

    try:
        payload = path.read_bytes()
    except OSError as exc:
        fail(errors, f"cannot read AGENTS entrypoint {display_path(path)}: {exc}")
        return
    try:
        text = payload.decode("utf-8")
    except UnicodeDecodeError as exc:
        fail(errors, f"AGENTS entrypoint must be UTF-8: {display_path(path)}: {exc}")
        return

    if len(payload) > AGENTS_MAX_UTF8_BYTES:
        fail(
            errors,
            "AGENTS entrypoint exceeds UTF-8 byte budget: "
            f"{display_path(path)} has {len(payload)} bytes, limit {AGENTS_MAX_UTF8_BYTES}",
        )
    line_count = len(text.splitlines())
    if line_count > AGENTS_MAX_LINES:
        fail(
            errors,
            "AGENTS entrypoint exceeds line budget: "
            f"{display_path(path)} has {line_count} lines, limit {AGENTS_MAX_LINES}",
        )
    if not text.startswith(("# AGENTS.md\n", "# AGENTS.md\r\n")):
        fail(errors, f"AGENTS entrypoint must start with '# AGENTS.md': {display_path(path)}")

    heading_positions: list[int] = []
    for heading in AGENTS_REQUIRED_HEADINGS:
        occurrences = text.count(heading)
        if occurrences != 1:
            fail(
                errors,
                f"AGENTS entrypoint heading must appear exactly once in {display_path(path)}: "
                f"{heading} (observed {occurrences})",
            )
            continue
        heading_positions.append(text.index(heading))
    if len(heading_positions) == len(AGENTS_REQUIRED_HEADINGS) and heading_positions != sorted(
        heading_positions
    ):
        fail(errors, f"AGENTS entrypoint headings are out of order: {display_path(path)}")

    required_fragments = (
        *AGENTS_PROGRESSIVE_DISCLOSURE_FRAGMENTS,
        *AGENTS_SOURCE_GATE_FRAGMENTS,
        *AGENTS_ALWAYS_ON_BOUNDARY_FRAGMENTS,
        *AGENTS_MINIMUM_CLOSURE_FRAGMENTS,
        "项目 Skills 位于 `.agents/skills/`",
        "| 约束或事实 | 唯一来源 | 何时读取 |",
        "$desktop-upgrade-harness",
        "$desktop-manage-version",
        "$desktop-manage-git-branch-chain",
        ".harness/version-state.json",
        ".harness/git-branch-chain.json",
    )
    for fragment in required_fragments:
        if fragment not in text:
            fail(
                errors,
                f"AGENTS progressive-disclosure contract missing in {display_path(path)}: {fragment}",
            )


def validate_engineering_contract(errors: list[str]) -> None:
    """确认工程规则唯一来源、关键入口和执行型 Skills 已建立确定性引用。"""
    validate_agents_entrypoint(errors)
    required_fragments = {
        ENGINEERING_RULES: (
            "当前规范根同时包含 Harness 专用 `Version.md`",
            "只接受 Harness 自身工程维护",
            "只能拒绝并要求用户在初始化完成、切换到唯一终端下游根目录后重新提出",
            "## 2. 文件、模块与依赖边界",
            "Rust 代码：400 行及以内",
            "800 行通过，801 行失败",
            "前端代码：500 行及以内",
            "1000 行通过，1001 行失败",
            "其他人工维护文本",
            "2000 行通过，2001 行失败",
            "<module>/mod.rs",
            "不强制 `index.ts` 桶文件",
            "高内聚、职责单一和职责相近性复核",
            "## 3. 中文代码注释",
            "### 3.4 机械存在性门禁",
            "check_rust_chinese_comments.py",
            "TypeScript Compiler AST",
            "不得自动生成或批量补入",
            "## 4. 文档规则",
            "## 5. 测试组织",
            "## 6. 规则例外",
            "## 7. 机械检查边界",
            "src-tauri/icons/32x32.png",
            "Tauri Builder `.setup(...)` 可达",
            "`.on_window_event(...)` 注册",
            "透明点击区域",
            "本身不触发 Product Spec、ADR、Product Status、Changelog 或 Verification",
            "任务被称为“修复”或“重构”不能绕过门禁",
            "`candidate-1`、`candidate-2`、`candidate-3`",
            "用户选择前不得验证格式、尺寸、色彩、像素、摘要或质量",
            "用户明确选择后只验证和按需标准化所选项",
            "缺失时安装官方当前最新兼容稳定版、可证明低于最低下界时受管升级",
            "持久去重 PATH，并在当前进程与只读取持久 PATH 的新 shell 绑定路径和版本实际复探",
            "已有有效身份保持，缺失字段只在独立目标仓库 local 作用域补齐",
            "明确发布的受管原子事务是唯一例外",
            ".harness/git-branch-chain.json",
            "`main`、`master` 与动态远端默认分支禁止日常写入",
            "候选事实只写入忽略的 `release/` 原子集合",
            "真实渠道发布成功后，才从已发布的默认分支 closing commit 开始后续受管 feature 生命周期",
            "候选构建、E2E、完整验收和就绪复核不得为了留证污染固定的默认分支 closing commit",
        ),
        ROOT / "README.md": (
            "docs/ENGINEERING_RULES.md",
            "## AI Agent 快速入口",
            ".agents/skills/desktop-instantiate-project/SKILL.md",
            ".agents/skills/desktop-instantiate-project/references/initialization-form.md",
            "用户确认完整汇总前保持零写入",
            "不要复制源 `.git`",
            "切换到该目录，再用 `$desktop-define-product`",
            "## 当前模板仓库的请求边界",
            "只接受两类信息",
            "必须在完成实例化并切换到唯一终端下游根目录后重新提出",
            "缺失时按当前平台的受管方式安装",
            "不修改全局 Git 设置",
            "`candidate-1` → `candidate-2` → `candidate-3`",
            "docs/design_standards/README.md",
            "问题修复或用户可感知优化都沿用 `bug-fix` 分类自动提升 Patch",
            "日常只强制 Rust 800 行、前端 1000 行的硬上限",
            "其他人工维护文本也固定为 2000 行硬上限",
            "Rust 401–800、前端 501–1000、其他文本 501–2000 行的建议候选只在当次发布启用语义审查时集中提示",
            "<module>/mod.rs",
        ),
        AGENT_POLICY: (
            "superpowers:",
            "推荐预设物化为 `superpowers: disabled`",
            "parallel_worktree_subagents:",
            "milestone_smoke:",
            "milestone_e2e:",
            "日常开发直接实施",
            "显式发布候选构建必须为当前候选解析一次 E2E 选择",
            "GUI 发布性能选择刻意不进入本文件，每次发布重新解析",
            "每次 GUI 发布开始前解析当次 `performanceSelection: enabled | disabled`",
            "产品/渠道要求时执行完整门禁",
            "`$desktop-prepare-release` 必须把当次审查结果、GUI 性能选择和适用的 macOS 签名选择/来源封存在当前链 closing commit",
            "候选构建在清理、测试前和写 manifest 前只读验证并消费这两份信封",
            "只在关闭链后另行解析 E2E",
        ),
        PRODUCT_SPEC: (
            "docs/ENGINEERING_RULES.md",
            "HARNESS-FEAT-HARNESS-SOURCE-SCOPE-GATE",
            "HARNESS-FEAT-INITIALIZATION-GIT-BOOTSTRAP-RELEASE-AUTOCOMMIT",
            "HARNESS-FEAT-GUI-NOTIFICATION-AUTOSTART-CAPABILITIES",
            "系统通知在初始化阶段只验证默认关闭、串行 worker/权限状态机结构和失败可见性",
            "当前应用的 Notifications 设置跳转与真实投递只由满足签名前提的最终安装候选验收",
            "HARNESS-FEAT-GUI-RELEASE-PERFORMANCE-GATE",
            "HARNESS-CHANGE-GUI-RELEASE-PERFORMANCE-BUDGET-V2",
            "HARNESS-FIX-ATOMIC-CANDIDATE-EVIDENCE-LIFECYCLE",
            "`gui-release-v2` 预算",
            "HARNESS-FEAT-RUST-1-95-LATEST-STABLE-SELECTION",
            "HARNESS-FEAT-DEFERRED-LOGO-VALIDATION-STABLE-PREVIEW",
            "HARNESS-FEAT-BASE100-AUTO-VERSION-CARRY",
            "0.0.99 -> 0.1.0",
            "0.99.99 -> 1.0.0",
            "不把普通缺陷修复、纯重构、格式整理、测试补强或内部清理写成项目记忆流水账",
            "HARNESS-FEAT-TIERED-CODE-LINE-LIMITS",
            "Producer/collector 在仓库外同文件系统 sibling 暂存和验证完整精确集合",
            "候选和纯只读 ready 不写 tracked 记忆",
            "Rust 代码 400 行及以内",
            "前端代码 500 行及以内",
            "<module>/mod.rs",
        ),
        ROOT / "docs" / "RUST_CLI_TEMPLATE.md": (
            "docs/ENGINEERING_RULES.md",
            "design_standards/README.md",
        ),
        ROOT / "docs" / "design_standards" / "README.md": (
            "当前请求或产品 profile 中已批准的产品专属标准优先于 Harness 通用缺省",
            "不得自行发明数值",
            "tauri-gui-sidebar-compact-80-v1",
            "tauri-gui-sidebar-detailed-v1",
        ),
        ROOT / "docs" / "design_standards" / "tauri_gui.md": (
            "adapter 的展示和纯交互层",
            "localStorageColorSchemeManager",
            "page → surface → section → field → action",
            "320 CSS px",
            "@tabler/icons-react",
            "i18next",
            "父容器不得代理子控件动作",
            'role="alertdialog"',
            "WCAG 2.2 AA",
            "Testing Library",
        ),
        ROOT / "docs" / "design_standards" / "tauri_sidebar.md": (
            "80px",
            "6px",
            "36px",
            "22px",
            "line-height: 1.25",
            "56px",
            "禁止 `em`/`ch` 固定占位盒",
            "navbar.width",
            "AppShell.Navbar",
            "248px",
            "76px",
            "APP_SIDEBAR_NAV_ICON_SIZE_PX = 22",
            "readDetailedSidebarCollapsed()",
            "detailedSidebarNavbarWidth(collapsed)",
            'data-navbar-width',
            'data-testid="app-sidebar-collapse-toggle"',
            'position="right"',
            "身份区父级点击不得切换状态",
        ),
        SKILLS_ROOT / "desktop-plan-change" / "SKILL.md": ("docs/ENGINEERING_RULES.md",),
        SKILLS_ROOT / "desktop-implement-change" / "SKILL.md": (
            "docs/ENGINEERING_RULES.md",
            "本次开发需要的相关非空单元/回归测试",
            "不得自动追加格式化、lint、静态",
        ),
        INITIALIZE_SKILL / "SKILL.md": (
            "docs/ENGINEERING_RULES.md",
            "docs/design_standards/README.md",
            "只运行初始化本身必需的非空测试",
            "不得在日常开发中自动运行这些全仓门禁",
            "日常/初始化门禁只分别强制 800、1000、2000 行硬上限",
            "建议候选只在当次发布启用语义审查时集中列出",
            "<module>/mod.rs",
        ),
        SKILLS_ROOT / "desktop-refactor-code" / "SKILL.md": (
            "Rust 401 至 800 行",
            "前端 501 至 1000 行",
            "<module>/mod.rs",
            "不强制创建 `index.ts` 桶文件",
        ),
        ENVIRONMENT_SKILL / "SKILL.md": ("docs/RUST_CLI_TEMPLATE.md",),
        GUI_IDENTITY_SKILL: (
            "docs/ENGINEERING_RULES.md",
            "$desktop-add-gui-adapter",
            "tauri-gui-common-v1",
            "tauri-gui-sidebar-compact-80-v1",
        ),
        GUI_SUPPORT_SKILL: (
            "docs/ENGINEERING_RULES.md",
            "docs/design_standards/README.md",
            "$desktop-implement-change",
            "秘密只能由已批准的安全运行时来源提供",
        ),
        GUI_INITIALIZATION_E2E_SKILL: (
            "docs/ENGINEERING_RULES.md",
            "docs/design_standards/README.md",
            "真实本机调试二进制",
            "verify-gui-lifecycle-contract.mjs",
            "src-tauri/tauri.release.conf.json",
            "异步 `load_release_notes`",
            "loading/error/retry",
            "未选能力不是缺失证据",
            "`single_instance: enabled`",
            "第二进程 15 秒内退出",
            "`system_tray: enabled`",
            "icons/32x32.png",
            "非透明 `icons/32x32.png`/配置引用",
            "从 `.setup(...)` 可达",
            "真实非空图形",
            "空白点击区域",
            "退出项结束进程并移除图标",
            "close_last_window_exits_application",
        ),
        SKILLS_ROOT / "desktop-verify-delivery" / "SKILL.md": ("docs/ENGINEERING_RULES.md",),
        SKILLS_ROOT / "desktop-instantiate-project" / "SKILL.md": ("docs/ENGINEERING_RULES.md",),
        SKILLS_ROOT / "desktop-add-mcp-adapter" / "SKILL.md": ("docs/ENGINEERING_RULES.md",),
        SKILLS_ROOT / "desktop-add-gui-adapter" / "SKILL.md": (
            "docs/ENGINEERING_RULES.md",
            "docs/design_standards/README.md",
            "check-typescript-chinese-comments.cjs",
            "mantine-ui-guidelines.md",
        ),
        CLI_SKILL: ("docs/ENGINEERING_RULES.md",),
        TUI_SKILL: ("工程规则",),
        E2E_SKILL: ("docs/VERIFICATION.md",),
        RUST_ASSET / "example_tool_core" / "src" / "lib.rs": (
            "#![deny(missing_docs)]",
        ),
    }
    for path, fragments in required_fragments.items():
        if not path.is_file():
            fail(errors, f"missing engineering contract file: {display_path(path)}")
            continue
        text = path.read_text(encoding="utf-8")
        for fragment in fragments:
            if fragment not in text:
                fail(
                    errors,
                    f"engineering rule reference missing in {display_path(path)}: {fragment}",
                )

def validate_streamlined_development_and_build(errors: list[str]) -> None:
    """校验最小开发闭环、构建记录边界、全量构建单测和显式并行。"""
    required_fragments = {
        ROOT / "README.md": (
            "日常开发直接使用 `$desktop-implement-change`",
            "普通单结果请求会直接在当前调用 Session 中完成",
            "`{Task}|{序号}|{功能摘要}{当前进度}`",
            "`已分配`、`运行中`、`检查中`、`已完成`",
            "每次真实转换至多尝试一次更新并按真实 `threadId` 有界复读",
            "提交/推送/远端复读完成后才进入 `已完成`",
            "阻断时保留最后真实阶段",
            "不会推翻已经完成的任务结果",
            "只增加并运行本次变更需要的单元/回归测试",
            "不自动增加计划、全仓检查、构建、冒烟、发布候选 E2E 或验收步骤",
            "显式“发布候选”请求先由发布准备解析当次语义审查选择",
            "GUI 还在关闭分支链前解析性能与 macOS 签名选择，并把它们封存进同一 closing commit",
            "构建 Skill 只读校验并消费这些记录、把同一日志打入候选，只另外解析本次是否启用 E2E",
            "记录缺失或适用性不符时失败关闭，不从对话补写或兜底询问",
            "运行项目全部非空单元测试并构建",
            "普通 Windows 本地安装试包是开发制品",
            "不要求发布日志或 clean HEAD",
            "构建事实只写入适用的产物位置和最终回复",
            "不创建或更新 ADR、Changelog、Product Status、Work Plan、Verification 等项目记忆",
            "只有在用户明确要求并行",
            "## 开始一个左侧 Task",
            "用 `list_projects` 按完整路径锁定保存项目",
            "精确 `projectId`",
            "只返回 `clientThreadId` 时表示请求已接受但仍在 setup",
            "不假设存在转换接口、不无限等待，也不重复创建",
            "相同 Git common dir",
            "`codex/task-*`",
            "`codex/unit-*`",
            'title="{Task}|{序号}|{功能摘要}已分配"',
            "派发前记录不可变 Task key",
            "不得把 `{Task}|{序号}|{功能摘要}{当前进度}` 原样当作分支名",
            "不冒充满足左侧 Task 的显示标题契约",
            "生命周期阶段变化就拆 Task",
            "只拿到 `clientThreadId` 时无限等待",
            "把 Ready/Active/Blocked 等宿主状态当作标题进度",
        ),
        AGENT_POLICY: (
            "decision_mode: reuse_then_infer_then_ask",
            "所有用户可见的当前调用 Session",
            "`{Task}|{序号}|{功能摘要}{当前进度}`",
            "`已分配`、`运行中`、`检查中`、`已完成`",
            "每次真实进度转换至多尝试一次标题更新",
            "`Task`、`序号` 和 `功能摘要` 在同一结果内保持不变，只更新进度后缀",
            "请求或流程要求的提交、推送和远端复读都已完成",
            "遇到阻断时保留最后真实阶段",
            "调用 `set_thread_title` 并省略 `threadId`",
            "不得推翻已经完成的任务结果",
            "推荐预设",
            "持久启用本身不能触发并行步骤",
            "日常开发直接实施",
            "显式发布候选构建必须为当前候选解析一次 E2E 选择",
            "E2E 选择只对当前发布候选有效",
            "本地开发试包不消费 E2E/性能选择",
            "候选 E2E、完整验收、`pending` → `accepted` 和就绪复核",
            "只进入忽略的 `release/` 原子集合",
            "真实渠道发布成功后，才从已发布的默认分支 closing commit 开始后续受管 feature 生命周期",
            "不得反向批准活动候选",
            "milestone_e2e` 只提供建议默认值",
            "GUI 发布性能选择刻意不进入本文件，每次发布重新解析",
            "每次 GUI 发布开始前解析当次 `performanceSelection: enabled | disabled`",
            "选择 `disabled` 且没有硬要求时跳过探针",
            "`releaseReview`/`candidateSelections`",
            "候选构建在清理、测试前和写 manifest 前只读验证并消费这两份信封",
            "只在关闭链后另行解析 E2E",
            "## 左侧 Task、项目绑定与独立 Worktree",
            "user-owned Task/thread",
            "不得只因生命周期阶段变化自动拆 Task",
            "普通单结果请求不先创建所谓 Task0",
            "按规范化完整路径精确选中保存项目",
            "target.type = project",
            "SETUP_PENDING",
            "不得假设存在 `clientThreadId → threadId` 桥、无限轮询、重复创建",
            "用户随后明确要求检查先前 queued Task",
            "只核对稳定三部分与合法四态后缀，不要求仍为 `已分配`",
            "git rev-parse --path-format=absolute --git-common-dir",
            "git worktree list --porcelain",
            "不硬编码 `main` 或 `master`",
            "Codex 管理 Worktree 默认可能处于 detached HEAD",
            "`codex/task-<task-slug>`",
            'title="{Task}|{序号}|{功能摘要}已分配"',
            "Task 描述记录不可变的 Task key",
            "稳定序号",
            "显示标题与 Git slug 是两个事实",
            "不得根据返回 id 重新分配序号",
            "Task 绑定：",
            "必须阅读的项目文档：",
            "`git status --porcelain=v1 --untracked-files=all`",
            "不要自行合并默认/集成分支",
            "协调方才移除对应 Worktree",
            "## 产品 feature 分支链与默认分支发布",
            "`feature-{ascii-kebab-summary}-{YYYYMMDD}`",
            "分支链严格串行",
            "一条 active feature 叶子同一时刻最多承载一个产品写入",
            "`$desktop-manage-git-branch-chain integrate-task`",
            "`git merge --ff-only <task-head>`",
            "命令不得自动 push 或清理 Task",
            "不得用 merge commit、rebase、cherry-pick 或 squash",
            "`.harness/git-branch-chain.json` 是受保护的当前链状态",
            "精确 `main`、`master` 与动态解析出的远端默认分支在日常流程中是保护分支",
            "用一次 atomic push 把动态默认 `main`/`master` 从冻结 OID 严格快进到关闭提交",
            "以每个登记远端 feature ref 的旧 OID 作为 lease 删除整链",
            "成功后当前分支是 clean 的动态默认 `main`/`master`",
            "不创建 `Release` 中转分支",
        ),
        SKILLS_ROOT / "desktop-plan-change" / "SKILL.md": (
            "只在持久计划能解决真实协调问题时建立 Todo",
            "多步骤、多模块、中等风险、可并行或 Agent 偏好本身不构成准入",
            "日常开发直接交给 `$desktop-implement-change`",
            "日常计划不得自行增加这些步骤",
            "不得在执行时静默追加全仓检查、构建或验收",
        ),
        SKILLS_ROOT / "desktop-implement-change" / "SKILL.md": (
            "直接实现用户请求",
            "`{Task}|{序号}|{功能摘要}运行中`",
            "同一稳定三部分更新为 `检查中`",
            "每次真实转换至多尝试一次",
            "更新为终态 `已完成`",
            "结果、验证、文档、提交、推送、远端复读与 clean 门禁全部完成后",
            "按真实 `threadId` 用 `list_threads` 做一次有界复读",
            "不阻断已经完成的任务结果",
            "只运行第 6 步的测试",
            "日常开发不得自动追加格式化、lint、静态",
            "普通构建也只新增全量非空单元测试和实际构建",
            "构建请求、执行和结果本身不触发 Product Spec、ADR、Changelog、Product Status、Work Plan 或 Verification",
            "只更新被独立事件触发的记忆",
            "当前说明来自左侧 Task 模板",
            "保存项目完整路径、`projectId`、repository identity、起始分支和起始提交",
            "git rev-parse --path-format=absolute --git-common-dir",
            "git worktree list --porcelain",
            "`codex/task-*`",
            'title="{Task}|{序号}|{功能摘要}已分配"',
            "稳定正整数序号",
            "显示标题不得直接作为 Git ref",
            "同一活动叶子同一时刻最多一个产品写入 Task",
            "协调方读取交付报告后只机械核对范围",
            "不得借整合追加非必要语义审查",
            "只用 `$desktop-manage-git-branch-chain integrate-task` 条件快进到原活动叶子",
            "再以独立 `publish` 推送复读",
            "不退化到 Local 主目录、其他 Task 或内部 Subagent 继续实施",
            "每完成一个逻辑闭环",
            "`git status --porcelain=v1 --untracked-files=all`",
            "Task 不自行操作默认主分支",
        ),
        PARALLEL_SKILL / "SKILL.md": (
            "只有用户在当前请求中明确要求并行 Subagent/Worktree",
            "日常开发不得仅因持久策略启用而自动增加并行步骤",
            "活动链以稳定错误码 `managed_feature_chain_active` 拒绝创建",
            "损坏或非法状态以 `git_branch_chain_state_invalid` 拒绝创建",
            "它不调用 `create_thread`，不创建新的左侧 Task",
            "保存项目根和当前 Task source Worktree",
            "相同规范化 Git common-dir",
            "`codex/task-<task>`",
            "`codex/unit-<task>-<unit>`",
            "`{Task}|{序号}|{功能摘要}{当前进度}` 显示标题",
            "不得把 `{Task}|{序号}|{功能摘要}{当前进度}` 显示标题原样传给",
            "不得冒充新的左侧 Task",
            "非空 repo-relative 写入所有权",
            "--source-worktree",
            "--write-target",
            "postflight",
            "committed 路径",
            "staged、unstaged、untracked 和 rename",
            "让每个单元分支成为 source 分支的祖先",
            "squash/cherry-pick 不满足 helper 的可证明清理条件",
            "同步等待每个必需结果",
            "绝不得自动暂存、贮藏或提交用户修改",
            "不得因并行本身追加格式、lint、静态、构建、冒烟、E2E 或完整验收",
            "helper 删除状态登记但保留单元分支",
            "只管理单个左侧 user-owned Task 内部",
            "不得把两个左侧 Task 安排进同一 Worktree",
        ),
        SKILLS_ROOT / "desktop-initialize-rust-project" / "SKILL.md": (
            "还必须保留 `docs/AGENT_POLICY.md` 中左侧 Task",
            "`{Task}|{序号}|{功能摘要}{当前进度}` 统一格式",
            "每次真实转换至多一次更新",
            "失败不阻断已完成结果",
            "统一描述模板",
            'title="{Task}|{序号}|{功能摘要}已分配"',
            "显示标题与独立 ASCII `task-slug` 分离",
        ),
        INSTANTIATE_SKILL: (
            "必须完整保留 `docs/AGENT_POLICY.md` 的左侧 Task 描述模板",
            "`{Task}|{序号}|{功能摘要}{当前进度}` 统一格式",
            "每次真实转换至多一次更新",
            "失败不阻断已完成结果",
            "精确保存项目/`projectId`",
            "`SETUP_PENDING` 有界返回",
            "`codex/task-*`",
            "`codex/unit-*`",
            'title="{Task}|{序号}|{功能摘要}已分配"',
            "返回的 `threadId`/`clientThreadId` 不得生成序号或反填标题",
        ),
        SKILLS_ROOT / "desktop-configure-git-commits" / "SKILL.md": (
            "references/commit-convention.md", "commit.template", "commit.cleanup=strip", "commit.verbose=true",
            "core.commentChar=#", "git config --local", "install --replace", "用户没有要求创建提交时",
            "下一步将实际运行 `git commit`",
            "不得运行本 Skill 的脚本或改写任何 Git 配置",
            "不得在初始化表单、复制、身份改写、环境门禁、脚手架编写或测试阶段提前运行",
        ),
        PRODUCT_SPEC: (
            "HARNESS-FEAT-INDEPENDENT-TASK-WORKTREE-DELIVERY",
            "HARNESS-FIX-PROJECT-BOUND-TASK-AND-SUBAGENT-WORKTREE",
            "HARNESS-FEAT-HARNESS-SOURCE-SCOPE-GATE",
            "HARNESS-FEAT-INITIALIZATION-GIT-BOOTSTRAP-RELEASE-AUTOCOMMIT",
            "HARNESS-FEAT-DEFERRED-LOGO-VALIDATION-STABLE-PREVIEW",
            "HARNESS-FEAT-GIT-FEATURE-BRANCH-CHAIN-LIFECYCLE",
            "HARNESS-CHANGE-SESSION-TITLE-PROGRESS-LIFECYCLE",
            "`{Task}|{序号}|{功能摘要}{当前进度}`",
            'create_thread(title="{Task}|{序号}|{功能摘要}已分配")',
            "检查失败返工时回到 `运行中`",
            "要求的提交、推送和远端复读全部完成后才更新为终态 `已完成`",
            "阻断时保留最后真实阶段",
            "一个左侧 Task 固定对应一个明确且可独立验收的结果",
            "`clientThreadId` 表示请求已接受但仍 `SETUP_PENDING`",
            "相同规范化 Git common dir",
            "`codex/task-<task-slug>`",
            "`codex/unit-<task>-<unit>`",
            "活动 feature 叶子同一时刻只允许一个串行产品写入 Task",
            "postflight",
        ),
        PARALLEL_WORKTREE_SCRIPT: (
            '"rev-parse", "--show-toplevel"',
            "def reject_active_managed_feature_chain",
            '"managed_feature_chain_active"',
            '"git_branch_chain_state_invalid"',
            "project_root_not_primary_worktree",
            "source_worktree_not_independent",
            "source_repository_mismatch",
            'f"codex/task-{task}"',
            'f"codex/unit-{safe_task}-{safe_unit}"',
            "source_worktree_dirty",
            "ownership_overlap_across_units",
            "actual_change_outside_ownership",
            "integration_ref_mismatch",
            "worktree_path_exists",
            "worktree_branch_mismatch",
            "worktree_dirty",
            "branch_not_integrated",
            'command.add_argument("--source-worktree", required=True)',
            'commands.add_parser(name)',
            'for name in ("inspect", "create", "guard", "verify", "remove")',
            "def remove_unit",
        ),
        PARALLEL_WORKTREE_TESTS: (
            "test_create_rejects_active_managed_feature_chain_without_side_effects",
            "test_create_rejects_invalid_branch_chain_state_without_side_effects",
            "test_create_from_task_branch_avoids_parent_child_ref_collision_and_removes",
            "test_create_rejects_dirty_source_including_untracked_files",
            "test_create_requires_primary_project_and_exact_source_cwd",
            "test_create_rejects_source_from_another_repository",
            "test_create_rejects_symlinked_external_worktree_container",
            "test_create_requires_safe_non_root_ownership",
            "test_create_rejects_overlapping_ownership_within_and_across_units",
            "test_guard_accepts_registered_subpath_and_rejects_unregistered_target",
            "test_verify_rejects_committed_untracked_and_renamed_escape",
            "test_remove_rejects_self_reference_dirty_and_unintegrated_unit",
            "test_remove_runs_postflight_before_clean_integrated_cleanup",
        ),
        BRANCH_CHAIN_SKILL: (
            "不创建 Codex 左侧 Task",
            "feature-{ascii-kebab摘要}-{YYYYMMDD}",
            "helper 不创建或使用 `Release` 中转分支",
            "日常 `start`、`integrate-task`、`publish` 和普通 Git 写入中只读",
            "Git `>=2.36.0`",
            "初始化不得预创建它",
            "只有首次 `start` 可按 `assets/git-branch-chain.json` 的 schema 创建",
            "分支链严格串行",
            "### integrate-task",
            "--task-worktree <absolute-path>",
            "Task HEAD 是活动叶子的非空严格线性后代且没有 merge",
            "命令绝不 push、不删除 Task Worktree/ref，也不改写状态 JSON",
            "git push --atomic",
            "--force-with-lease",
            "默认分支更新只能是发布事务内基于冻结旧 OID 的严格 fast-forward",
            "也没有用户后续 Merge/PR 步骤",
            "legacy-local-cleanup-complete",
            "正常路径不会发送针对缺失 `Release` 的删除 refspec",
        ),
        BRANCH_CHAIN_SCRIPT: (
            'subparsers.add_parser("inspect"',
            'subparsers.add_parser("start"',
            '"integrate-task"',
            'subparsers.add_parser("publish"',
            '"release", help="原子快进默认分支并清理精确 feature 分支链"',
            "raise SystemExit(main())",
        ),
        BRANCH_CHAIN_OPERATIONS: (
            "def start_chain(",
            "def require_release_default(",
            "def integrate_task(",
            '"diff-tree"',
            "task commits must not change .harness/git-branch-chain.json",
            "def publish_leaf(",
            "def release_chain(",
            '"releaseTarget": "default"',
            '"releaseBranch": closed["defaultBranch"]',
            "closing state does not authorize a direct-default release",
            "remote default branch did not reach the closing commit",
            "def finish_legacy_local_cleanup(",
            '"status": "legacy-local-cleanup-complete"',
        ),
        BRANCH_CHAIN_COMMIT: (
            "def require_commit_prerequisites(",
            "def commit_state(",
            "state commit must contain only .harness/git-branch-chain.json",
            "state payload changed during commit hooks",
        ),
        BRANCH_CHAIN_CHECKS: (
            "def require_branch_head_clean(",
            "def require_state_postcondition(",
            "branch-chain state changed during the operation",
        ),
        BRANCH_CHAIN_GIT: (
            "MINIMUM_GIT_VERSION = (2, 36, 0)",
            "def require_git_version()",
            "def select_remote(",
            'if "origin" in remotes:',
            "def require_single_push_destination(",
            "def protected_branches(",
            'return {"main", "master", default_branch}',
            "def push_branch(",
            "def delete_local_branches(",
        ),
        BRANCH_CHAIN_REMOTE: (
            "def remote_heads(",
            '"ls-remote", "--heads"',
            "remote branch snapshot is malformed or ambiguous",
            "def push_release_transaction(",
            '"--atomic",',
            'f"--force-with-lease=refs/heads/{default_branch}:{default_before}"',
            'f"{closing_head}:refs/heads/{default_branch}"',
            'f"--force-with-lease=refs/heads/{entry[\'branch\']}:{entry[\'preCloseHead\']}"',
            'return "pending-release-missing"',
            "def require_legacy_remote_complete(",
        ),
        BRANCH_CHAIN_STATE: (
            "activeChain",
            "lastClosedChain",
            "preCloseHead",
            "baseBranch",
            "baseHead",
            'direct_release_extension = {"releaseTarget"}',
            "lastClosedChain.releaseTarget must be default",
            "def write_state(",
            "os.replace",
        ),
        BRANCH_CHAIN_TESTS: (
            "test_inspect_uses_live_remote_default_and_does_not_create_state",
            "test_start_creates_state_commit_from_default_and_pushes_exact_feature_ref",
            "test_second_start_requires_fully_pushed_parent_and_freezes_tip",
            "test_publish_fast_forwards_but_rejects_remote_ahead_or_diverged",
            "test_integrate_task_fast_forwards_locally_then_publish_updates_remote",
            "test_integrate_task_requires_clean_coordinator_and_task_worktrees",
            "test_integrate_task_requires_the_current_active_leaf",
            "test_integrate_task_rejects_remote_active_leaf_drift",
            "test_integrate_task_rejects_remote_task_ref",
            "test_integrate_task_rejects_invalid_or_mismatched_frozen_oid",
            "test_integrate_task_rejects_mismatched_task_worktree",
            "test_integrate_task_rejects_non_descendant_history",
            "test_integrate_task_rejects_merge_history",
            "test_integrate_task_requires_safe_task_ref",
            "test_integrate_task_rejects_protected_state_changes",
            "test_integrate_task_rejects_protected_state_change_then_revert",
            "test_integrate_task_rejects_other_task_worktree_occupancy",
            "test_start_rejects_release_as_remote_default",
            "test_start_rejects_non_main_master_default_without_ref_changes",
            "test_release_atomically_updates_default_and_cleans_exact_two_branch_chain",
            "test_release_supports_master_as_dynamic_default",
            "test_existing_release_is_migrated_to_default_and_deleted",
            "test_legacy_remote_complete_allows_local_cleanup_only",
            "test_next_chain_starts_from_published_default_without_release_branch",
            "test_remote_hook_rejection_keeps_atomic_refs_and_retry_reuses_close_commit",
            "test_remote_success_then_local_transaction_failure_is_retryable_without_push",
            "test_other_worktree_occupancy_blocks_before_close_commit_or_remote_delete",
            "test_default_branch_worktree_occupancy_blocks_before_close_commit",
            "test_remote_without_atomic_capability_never_falls_back",
        ),
        BRANCH_CHAIN_RACE_TESTS: (
            "test_default_race_uses_frozen_lease_and_preserves_feature_refs",
            "test_concurrent_release_creation_is_preserved_and_retryable",
            "test_legacy_release_deleted_during_push_is_retryable",
            "test_pre_commit_cannot_smuggle_paths_before_remote_deletion",
            "test_pre_commit_cannot_rewrite_expected_state_payload",
            "test_pre_push_dirty_hook_prevents_false_start_success",
        ),
        BRANCH_CHAIN_CONTRACT_TESTS: (
            "test_remote_heads_use_one_snapshot_for_all_requested_refs",
            "test_push_transaction_updates_default_and_deletes_only_registered_refs",
            "test_push_transaction_never_creates_release_when_it_was_absent",
            "test_unique_remote_must_have_a_safe_name_before_url_queries",
            "test_dangling_state_symlink_is_never_treated_as_missing_or_replaced",
            "test_success_postcondition_compares_the_full_state_snapshot",
        ),
        BRANCH_CHAIN_VERSION_TESTS: (
            "test_commit_prerequisites_require_identity_and_template_without_leak",
            "test_git_2_35_8_is_rejected_without_stderr_leak",
            "test_git_2_36_0_is_accepted",
            "test_git_release_candidate_and_interactive_run_are_rejected",
        ),
        SKILLS_ROOT / "desktop-rename-project-identity" / "SKILL.md": (
            "实例化身份重置",
            "现有产品改名",
            "必须先通过 `$desktop-define-product` 确认范围",
            "不自动创建 Work Plan、候选或完整验收步骤",
            "只有用户明确请求正式发布候选时才先进入 `$desktop-prepare-release`",
            "由关闭状态封存当前范围后调用对应构建 Skill",
            "构建只另外确认 E2E 并全量运行单元测试",
        ),
        VERIFY_DELIVERY_SKILL: (
            "当前构建已明确选择 E2E `enabled`",
            "没有 Work Plan 不阻断验收",
            "当前构建已经运行项目全部非空单元测试",
            "milestone_e2e` 仅用于当时询问的建议默认值",
            "按每个 GUI manifest 的 `performanceSelection` 条件复核性能",
            "`disabled`：只有不存在产品/渠道性能硬要求时才接受 `performanceStatus: Not run`",
            "performanceReason",
            "performanceRemainingRisk",
            "立即返回 `$desktop-implement-change`",
        ),
        E2E_SKILL: (
            "当前构建选择为 `enabled`",
            "milestone_e2e` 不能替代当前构建选择",
            "完整真实最终产物",
            "没有 Work Plan 不阻断 E2E",
            "GUI 性能按 manifest 的当次 `performanceSelection` 独立处理",
            "选择 `disabled` 且无硬要求时",
            "返回 `$desktop-implement-change` 增加回归测试",
        ),
        BUILD_RELEASE_SKILL: (
            "本次请求已明确 `enabled`/`disabled` 时直接复用",
            "否则在任何测试或编译前询问用户一次",
            "只强制运行项目全部非空单元测试",
            "cargo test --workspace --all-targets --all-features --locked",
            "不得在构建名义下自动追加格式、lint、中文注释或其他开发门禁",
            "不得因显式构建、缺少/过期环境证据",
            "并重试原失败命令一次",
            "e2eSelection",
            "不得创建或更新 Product Spec、ADR、Changelog、Product Status、Work Plan 或 Verification",
            "最终字节和清单形成后立即交给 `$desktop-verify-delivery`",
        ),
        TAURI_RELEASE_SKILL: (
            "本次请求已明确 `enabled`/`disabled` 时直接复用",
            "否则在任何测试或编译前询问用户一次",
            "审查、性能和 macOS 签名选择及来源都只能从关闭状态读取",
            "所有 GUI 候选的 `performanceSelection` 必须精确为 `enabled | disabled`",
            "当前候选目标包含 macOS 时 `macosSigningSelection` 必须精确为 `enabled | disabled`",
            "同一 closing commit 重跑复用，新发布重新由 prepare-release 解析",
            "打包前只先运行项目全部非空单元测试",
            "cargo test --workspace --all-targets --all-features --locked",
            "前端必须运行 `package.json` 与锁文件实际声明的完整单元测试套件",
            "不得自动追加格式、lint、类型、中文注释、`dist` 扫描或其他开发门禁",
            "初始化后的构建不做例行环境预检",
            "只有某条命令已经失败",
            "并重试原命令一次",
            "e2eSelection",
            "选择 `performanceSelection: disabled` 且无产品/渠道硬要求时",
            "performanceStatus: Not run",
            "performanceReason",
            "performanceRemainingRisk",
            "性能选择为 `enabled` 时 `performanceStatus` 为 `Unverified`",
            "不得创建或更新 Product Spec、ADR、Changelog、Product Status、Work Plan 或 Verification",
            "最终字节形成后立即交给 `$desktop-verify-delivery`",
        ),
        CROSS_PLATFORM_RELEASE_SKILL: (
            "e2e_selection",
            "cargo test --workspace --all-targets --all-features --locked",
            "不得自动追加格式、lint 或其他开发门禁",
            "e2eSelection",
            "不得创建或更新 Product Spec、ADR、Changelog、Product Status、Work Plan 或 Verification",
            "矩阵本身不得运行 E2E",
        ),
        COLLECT_RELEASE_SKILL: (
            "e2eSelection",
            "只接受当前 clean 动态默认 `main`/`master` closing commit",
            "锁定其 `releaseBranch`、`releaseHead`、`releaseReview` 与 `candidateSelections`",
            "审查、性能与 macOS 签名字段必须逐字段来自两份封存信封",
            "再次只读运行 `verify-release-review`",
            "选择为 `disabled` 且无产品/渠道硬要求时允许 `performanceStatus: Not run`",
            "performanceReason",
            "performanceRemainingRisk",
            "不重新构建、签名、执行或发布候选",
            "收集过程绝不得自行启动冒烟/E2E",
            "不得创建或更新 Product Spec、ADR、Changelog、Product Status、Work Plan 或 Verification",
        ),
        PREPARE_RELEASE_SKILL: (
            "只核对候选清单中的 `reviewSelection`、`e2eSelection`、`performanceSelection` 与 `macosSigningSelection`",
            "在任何提交或发布元数据写入前解析当次 `reviewSelection: enabled | disabled`",
            "含 GUI 时同轮解析 `performanceSelection: enabled | disabled`",
            "产品/渠道硬要求强制启用并记录来源",
            "新发布重新解析",
            "将完整 `releaseReview`、`candidateSelections` 与 `lastClosedChain` 在同一个 closing commit 中原子封存",
            "构建只另外解析本次 E2E 选择",
            "不得在此运行任一测试",
            "绝不得在发布准备中运行冒烟/E2E",
        ),
        ENGINEERING_RULES: (
            "### 5.3 开发、构建与完整验收",
            "日常开发统一直接实施，只运行本次变更需要的相关非空单元/回归测试",
            "显式发布候选构建在任何测试或编译前解析当前候选的 E2E 选择",
            "GUI 正式发布在任何测试或编译前解析当次 `performanceSelection: enabled | disabled`",
            "选择 `disabled` 且无硬要求时跳过探针",
            "构建必须运行项目全部非空单元测试",
            "manifest 和最终回复是发布候选构建的记录出口",
            "本地开发试包只报告实际产物路径和风险",
            "不触发 Product Spec、ADR、Changelog、Product Status、Work Plan 或 Verification",
            "自动增加 Work Plan、全仓测试、格式化、代码规范、静态、集成/契约、构建、冒烟、E2E、Verification 或人工复核",
            "普通构建不为它增加独立步骤",
        ),
        ROOT / "docs" / "RELEASE.md": (
            "## 构建、完整验收与发布顺序",
            "当前请求未明确时询问一次",
            "必须运行项目全部非空单元测试",
            "当前 `e2eSelection`",
            "E2E 选择只对当前发布候选有效",
            "GUI 性能和 macOS 签名选择也在该入口按当前请求、产品事实与渠道要求锁定",
            "产品/渠道硬要求强制启用",
            "封存为 `disabled` 且无硬要求时不生成探针",
            "把显式 `releaseReview`、`candidateSelections` 和链关闭状态写入同一个 closing commit",
            "候选构建在清理目录、测试或编译前，以及写 manifest 前",
            "E2E 仍在构建阶段按当前候选单独解析",
            "候选流程只把这些事实写入忽略的 `release/` 原子集合、manifest 声明的相邻制品证据和最终回复",
            "本地开发试包只写最终回复，不创建 manifest",
            "不得把构建或验收日志复制到项目记忆",
            "就绪复核是纯只读操作",
            "任一字节或仓库信封在执行期间漂移都拒绝候选",
            "一次性把所有 manifest 从 `pending` 更新为 `accepted`",
            "真实渠道发布成功后，才从该已发布 closing commit 开始后续受管 feature 生命周期",
        ),
        ROOT / "docs" / "RUST_CLI_TEMPLATE.md": (
            "用户显式请求发布候选构建时逐次解析 E2E 选择",
            "Windows 本地开发试包不解析 E2E/性能选择",
            "只追加全量非空单元测试和实际构建",
            "不自动追加格式、lint、静态或其他开发门禁",
            "候选 E2E、完整验收、状态更新和就绪复核",
            "只写入忽略的 `release/` 原子集合",
            "真实渠道发布成功后，才从已发布的默认分支 closing commit 开始后续受管 feature 生命周期",
        ),
        ROOT / "docs" / "VERIFICATION.md": (
            "候选 E2E、完整验收、`pending` → `accepted` 状态更新和发布就绪复核",
            "仅写入忽略的 `release/` 原子候选集合",
            "真实渠道发布成功后，发布执行方才从该已发布 closing commit 开始后续受管 feature 生命周期",
            "独立回顾性人工复核或长期审计也必须使用自己的受管 feature 生命周期",
            "不得改写活动候选、覆盖历史失败或反向授予其 `accepted`/`ready`",
            "GUI 发布性能是逐次选择",
            "选择 `disabled` 且无硬要求时允许 `performanceStatus: Not run`",
        ),
        UPGRADE_SKILL / "SKILL.md": (
            "不自动创建 Work Plan、Todo、并行 Worktree/Subagent 或完整验收步骤",
            "只有用户明确要求并行",
            "只运行本次升级实际影响的非空单元/回归测试",
            "不得因 Harness 升级自动追加全仓格式、lint、静态",
            "$desktop-manage-git-branch-chain",
            "旧下游尚无该状态时必须保持缺席",
        ),
        ENVIRONMENT_SKILL / "SKILL.md": (
            "只接受两类触发",
            "不得仅因首次修改代码、新任务、新会话、显式构建",
            "门禁成功后只重试原失败命令一次",
            "缺少环境证据或工具链版本可能变化而增加探测",
        ),
        UPGRADE_POLICY: (
            "managed",
            "managed-self",
            "merge-sections",
            "conditional",
            "protected",
            "tombstone",
        ),
    }
    helper_text = ""
    for path, fragments in required_fragments.items():
        if not path.is_file():
            fail(errors, f"missing streamlined workflow contract file: {display_path(path)}")
            continue
        text = path.read_text(encoding="utf-8")
        if path == PARALLEL_WORKTREE_SCRIPT:
            helper_text = text
        for fragment in fragments:
            if fragment not in text:
                fail(
                    errors,
                    f"streamlined workflow rule missing in {display_path(path)}: {fragment}",
                )

    for path in (
        BRANCH_CHAIN_SCRIPT,
        BRANCH_CHAIN_OPERATIONS,
        BRANCH_CHAIN_COMMIT,
        BRANCH_CHAIN_CHECKS,
        BRANCH_CHAIN_GIT,
        BRANCH_CHAIN_REMOTE,
        BRANCH_CHAIN_STATE,
        BRANCH_CHAIN_TESTS,
        BRANCH_CHAIN_CONTRACT_TESTS,
        BRANCH_CHAIN_RACE_TESTS,
        BRANCH_CHAIN_VERSION_TESTS,
    ):
        if not path.is_file():
            continue
        try:
            compile(path.read_text(encoding="utf-8"), str(path), "exec")
        except (OSError, SyntaxError, UnicodeError) as error:
            fail(errors, f"invalid Git branch-chain Python module {display_path(path)}: {error}")

    current_rule_files = (
        ROOT / "README.md",
        ROOT / "AGENTS.md",
        AGENT_POLICY,
        ENGINEERING_RULES,
        PRODUCT_SPEC,
        ROOT / "docs" / "RUST_CLI_TEMPLATE.md",
        ROOT / "docs" / "RELEASE.md",
        ROOT / "docs" / "VERIFICATION.md",
        ROOT / "docs" / "work_plan" / "README.md",
        *(ROOT / "docs" / "harness_engineering" / name for name in (
            "foundations.md",
            "agent_first_design.md",
            "project_lifecycle.md",
        )),
        *(path / "SKILL.md" for path in sorted(SKILLS_ROOT.iterdir()) if path.is_dir()),
    )
    forbidden_tier_fragments = (
        "每项任务使用一种路径",
        "快速路径",
        "标准路径",
        "里程碑路径",
        "当前任务路径",
        "推荐敏捷预设",
    )
    for path in current_rule_files:
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")
        for fragment in forbidden_tier_fragments:
            if fragment in text:
                fail(
                    errors,
                    f"obsolete tiered workflow remains in {display_path(path)}: {fragment}",
                )

    forbidden_helper_fragments = (
        "git stash",
        "git commit",
        "--force",
        '"branch", "-D"',
    )
    for fragment in forbidden_helper_fragments:
        if fragment in helper_text:
            fail(errors, f"unsafe parallel helper behavior present: {fragment}")

def validate_version_contract(errors: list[str]) -> None:
    """使用 facade 当前 VERSION_FILE，保留测试和调用方的注入边界。"""

    _validate_version_contract(errors, VERSION_FILE)  # noqa: F405
