"""初始化仓库契约的必需片段。"""

from __future__ import annotations

from pathlib import Path

from .context import *  # noqa: F403


def repository_required_fragments(
    gate_file: Path,
    rust_baseline: Path,
) -> dict[Path, tuple[str, ...]]:
    """返回策略、工具链、身份和仓库文件的契约片段。"""

    return {
        AGENT_POLICY: (
            "superpowers:",
            "parallel_worktree_subagents:",
            "milestone_smoke:",
            "milestone_e2e:",
            "`superpowers:`",
            "显式构建必须为当前构建解析一次 E2E 选择",
            "持久启用本身不能触发并行步骤",
            "$desktop-test-gui-initialization-e2e",
            "七项 GUI profile",
            "对启用的单实例、托盘、系统通知、自启、关于页或赞助页验证完整实现",
            "对禁用能力验证无残留",
            "只在单实例启用时执行双启动",
            "只在托盘启用时执行可见托盘与关闭隐藏/恢复/退出生命周期",
            "托盘禁用时必须实测关闭最后窗口退出",
            "最终侧栏模式",
            "宿主无法判定或观察某个已选场景",
            "性能失败先回实现修复和重建",
        ),
        gate_file: (
            "显式构建、缺少环境证据、新任务或新会话本身都不得触发它",
            "门禁成功后只重试原失败命令一次",
            "scripts/development-environment-gates.sh --install-missing",
            "scripts/development-environment-gates.ps1",
            "rustup --version",
            "node --version",
            "pnpm --version",
            "not-required",
            "https://static.rust-lang.org/rustup/dist",
            "https://nodejs.org/dist",
            "https://aka.ms/vs/17/release/vs_BuildTools.exe",
            "MSVC Build Tools",
            "scripts/macos-tauri-xwin-gates.sh --install-missing --target x86_64-pc-windows-msvc",
            "cargo install --locked --version '>=0.23.1, <0.24.0' cargo-xwin",
            "LLVM、LLD 与 NSIS 使用既有 Homebrew",
            "缺少 Homebrew 时阻断",
            "xwin 成功仍把 Windows runtime 记为 `Unverified`",
        ),
        rust_baseline: (
            "$desktop-check-development-environment",
            "只有 GUI 命令的环境恢复才增加 Node.js 与 pnpm",
            "example_tool_core = { path = \"example_tool_core\" }",
            "<项目标识>_core",
            "<项目标识>_cli",
            "_tui",
            "_mcp",
            "_gui",
            "所有第三方依赖和工作区内 crate 路径都集中在根",
            "首次脚手架在当前项目根创建 `Cargo.toml`",
            "scaffold status",
            "productDefinitionRequired=true",
            "$desktop-define-product",
            "$desktop-prepare-gui-support-surfaces",
            "选择 GUI 后必须先解析专门问询",
            "直接初始化时在首轮一并询问尚未解析的接口组合与 Agent 策略模式",
            "基础决定完成后再每轮补全一个 GUI 条件字段",
            "不得在复制后重复询问已确认值",
            "`system_tray`、`system_notification`、`autostart`、`about_page`、`sponsor_page`、`single_instance`",
            "`sidebar_mode` 的 `compact|detailed`",
            "唯一 `gui-initialization-config` 代码块",
            "六项能力不得缺失、推断或残留 `pending`",
            "未选择侧栏模式时必须写入 `sidebar_mode = detailed`",
            "显式非法值不得按未选择处理",
            "最终七项配置不得缺失",
            "$desktop-add-gui-system-notifications",
            "$desktop-add-gui-autostart",
            "tauri-plugin-notification = \"2.4.0\"",
            "mac-usernotifications = \"0.3.1\"",
            "tauri-plugin-autostart = \"2.5.1\"",
            "真实更新/强更/统计仍需独立产品批准",
            "tauri-plugin-single-instance",
            "插件必须是 Tauri Builder 注册的首个 plugin",
            "single_instance_plugin_is_registered_first",
            "second_launch_restores_existing_main_window",
            "选择 `disabled` 时不得声明依赖、注册插件、保留回调或运行双启动场景",
            "Tauri `tray-icon` feature",
            "仅当 `system_tray = enabled` 时",
            "由 `tauri.conf.json` 的 `bundle.icon` 引用的 `icons/32x32.png`",
            "Tauri Builder `.setup(...)` 调用",
            "必需应用图标和 `.build(app)`",
            "`.on_window_event(...)` 注册",
            "托盘菜单稳定 ID 恰好为 `show_window`/`quit`",
            "可见标签由 `rust_i18n` 解析",
            "`CloseRequested` 只 `prevent_close()` 后隐藏",
            "选择 `disabled` 时不得启用 feature、安装托盘、保留菜单/locale 资源、调用 `prevent_close()` 或隐藏窗口",
            "显式调用 `AppHandle::exit(0)`",
            "close_last_window_exits_application",
            "GUI 活动选项卡、查询/筛选、排序、分页页码/每页数量",
            "GUI 初始化固定建立动态标题、`/settings`",
            "`/about`、`/sponsor` 分别只在对应选择启用时建立",
            "按 `sidebar_mode` 精确命中",
            "compact 当前固定 `80px`、`6px` 内容内边距、`36px` Logo、`22px` 图标",
            "detailed 固定 `248px`/`76px`、`72px`/`44px`、`22px` 图标",
            "底部按已选赞助、固定设置、已选关于生成",
            "所选关于页包含检查更新、更新日志、作者、联系方式和三段免责声明",
            "所选赞助页包含双主题布局与完整 `media/sponsor/*`",
            "Ratatui + tui-realm + tui-realm-stdlib",
            "Vite + React + TypeScript + Mantine UI + `@tabler/icons-react` + TanStack Router 文件路由 + TanStack Query + Jotai",
            "$desktop-test-gui-initialization-e2e",
            "verify-gui-lifecycle-contract.mjs",
            "tray_show_restores_and_focuses_main_window",
            "close_request_hides_without_exit",
            "tray_quit_exits_application",
            "tray_labels_resolve_for_supported_locales",
            "tray_labels_fall_back_to_english",
            "language_change_updates_tray_menu_labels",
            "仅启用单实例时双启动",
            "仅启用托盘时实测托盘生命周期",
            "托盘禁用时实测关闭最后窗口退出",
            "对禁用能力验证依赖/运行时/路由/资源缺席",
            "pnpm tauri build --debug --no-bundle",
            "Tokio",
            "Axum",
            "Tower/Tower HTTP",
            "Clap",
            "SeaORM",
            "config-rs",
            "tracing",
            "tracing-subscriber",
            "tracing-appender",
            "OpenTelemetry OTLP/HTTP",
            "OpenTelemetry",
            "anyhow",
            "thiserror",
            "serde",
            "jiff",
            "不表示初始化时把所有依赖无条件写入清单",
            "硬规则例外",
            "<项目标识>_gui/src-tauri/dmg/background.png",
            "./dmg/background.png",
            "660×400",
        ),
        PRODUCT_SPEC: (
            "HARNESS-FEAT-BATCHED-BASE-INITIALIZATION-FORM",
            "首轮必须一次列出全部尚未解析的基础字段",
            "基础字段全部解析后才进入条件阶段",
            "每轮补全一个条件字段",
            "项目路径输入允许是最终项目根目录或其父目录",
            "区分大小写地精确相等",
            "`<项目路径>/<项目标识>`",
            "父目录可以存在且非空",
            "唯一项目根目录",
            "CLI/TUI/MCP/GUI",
            "未选择任何接口时默认 CLI",
            "docs/AGENT_POLICY.md",
            "scaffold status",
            "productDefinitionRequired=true",
            "Ratatui",
            "tui-realm-stdlib",
            "Mantine UI",
            "@tabler/icons-react",
            "TanStack Router",
            "TanStack Query",
            "Jotai",
            "Vite",
            "Vitest",
            "Testing Library",
            "Tokio",
            "Axum",
            "Tower/Tower HTTP",
            "Clap",
            "SeaORM",
            "config-rs",
            "tracing",
            "tracing-subscriber",
            "tracing-appender",
            "OpenTelemetry",
            "anyhow",
            "thiserror",
            "serde",
            "jiff",
            "固定选型表示“能力出现时采用该技术”",
            "硬规则例外 ADR",
            "独立 `main` 仓库",
            "git rev-parse --show-toplevel",
            "main",
            "Skills 地图和约束地图",
            "$desktop-prepare-gui-app-identity",
            "$desktop-prepare-gui-support-surfaces",
            "$desktop-test-gui-initialization-e2e",
            "未批准时保持禁用和零出站",
            "HARNESS-FEAT-GUI-NOTIFICATION-AUTOSTART-CAPABILITIES",
            "初始化器必须在基础字段全部解析后进入条件问询",
            "`system_tray`、`system_notification`、`autostart`、`about_page`、`sponsor_page`、`single_instance`",
            "提供 `sidebar_mode` 的 `compact` 或 `detailed` 选择",
            "唯一 `gui-initialization-config` 代码块",
            "七项写入唯一 `gui-initialization-config` 代码块",
            "用户未选择侧栏模式时必须写入 `sidebar_mode = detailed`",
            "显式非法值不得按未选择处理",
            "`system_tray = enabled` 时完整实现现有托盘图标",
            "`disabled` 时不启用 `tray-icon`",
            "`CloseRequested` 显式调用 `AppHandle::exit(0)`",
            "`single_instance = enabled` 时完整实现官方首插件",
            "`disabled` 时依赖、插件、回调和双启动场景都必须缺席",
            "`/settings`、动态标题、语言/三态主题和亮暗语义主题仍是所有 GUI 的固定基线",
            "`about_page`、`sponsor_page` 各自只控制相应路由、导航入口、组件和运行时资源",
            "`sidebar_mode = compact` 精确命中 `tauri-gui-sidebar-compact-80-v1`",
            "`sidebar_mode = detailed` 精确命中 `tauri-gui-sidebar-detailed-v1`",
            "独立 local-storage 键",
            "初始化结构检查和真实本机 E2E 读取同一 profile",
            "禁用能力必须证明无残留",
            "系统通知和开机自启各由独立 Skill",
            "自启登录项必须恢复执行前状态",
            "签名验证不可关闭",
            "notarytool` Keychain profile",
            "非空 `.DS_Store`",
            "HARNESS-FEAT-TIERED-CODE-LINE-LIMITS",
            "Rust 代码 400 行及以内",
            "800 行通过，801 行",
            "前端代码 500 行及以内",
            "1000 行通过，1001 行",
            "<module>/mod.rs",
            "<项目标识>_gui/src-tauri/dmg/background.png",
            "bundle.macOS.dmg.background",
        ),
        ROOT / "README.md": (
            "## 当前模板仓库的请求边界",
            "Agent 只接受两类信息",
            "只解析允许的初始化字段",
            "完成实例化并切换到唯一终端下游根目录后重新提出",
            "CLI、TUI、MCP、GUI",
            "默认使用 Rust 2024 和共享核心",
            "系统托盘、系统通知、开机自启、关于页、赞助页、单实例和侧栏样式",
            "`candidate-1` → `candidate-2` → `candidate-3`",
            "未经验证或标准化的原始 Logo 候选",
            "缺失时按当前平台的受管方式安装",
            "只在这个仓库静默使用设备账户名的英文形式",
            "独立、无远端、带初始化提交的 Git 仓库",
        ),
        ROOT / "LICENSE.zh-CN.md": (
            "本协议不是开源许可证",
            "终端下游与禁止继续衍生",
            "知识产权",
            "第三方材料",
            "以中文版本为准",
            "适用项目名称：Agent-first Harness 项目模板",
            "仅将该名称替换",
        ),
        ROOT / "LICENSE.en.md": (
            "This is not an open-source license",
            "Terminal Downstream Project; No Further Derivation",
            "intellectual property rights",
            "Third-Party Materials",
            "the Chinese version controls",
            "Applicable Project Name: Agent-first Harness Template",
            "only this name must be replaced",
        ),
        RENAME_IDENTITY_SKILL / "SKILL.md": (
            "--old-display-name-zh",
            "--new-display-name-zh",
            "--old-display-name-en",
            "--new-display-name-en",
            "--old-id",
            "--old-kebab",
            "--apply",
            "--rename-root",
            "路径越界",
            "符号链接",
            "LICENSE.zh-CN.md",
            "LICENSE.en.md",
            "残留",
        ),
        RENAME_IDENTITY_SKILL / "agents" / "openai.yaml": (
            "重命名项目身份",
            "$desktop-rename-project-identity",
        ),
        RENAME_IDENTITY_SKILL / "scripts" / "rename_project_identity.py": (
            "EXCLUDED_DIRECTORIES",
            "--old-display-name-zh",
            "--new-display-name-en",
            "--apply",
        "不允许符号链接",
        "目标已存在",
            "residuals",
        ),
        RENAME_IDENTITY_SKILL / "scripts" / "test_rename_project_identity.py": (
            "test_preview_then_apply_renames_content_paths_and_licenses",
            "test_existing_destination_blocks_without_overwrite",
            "test_symbolic_link_blocks_before_write",
            "test_explicit_root_rename_moves_project_without_overwrite",
        ),
        GITIGNORE: (
            "/target/",
            "**/node_modules/",
            "**/dist/",
            "**/__pycache__/",
            "**/coverage/",
            ".env.*",
            "!.env.example",
            ".DS_Store",
        ),
        ROOT / "docs" / "CLI_CONTRACT.md": (
            "<项目标识>_cli",
            "scaffold status",
            "productDefinitionRequired=true",
        ),
    }
