import path from "node:path";

import { ROOT } from "./core.mjs";
import {
  AGENT_POLICY,
  GITIGNORE,
  GUI_DIALOG_SKILL,
  PRODUCT_SPEC,
  RENAME_ROOT,
} from "./initialization_paths.mjs";

/** Return repository-level contracts that make neutral initialization reproducible. */
export function repositoryRequiredFragments(gateFile, rustBaseline) {
  return new Map([
    [AGENT_POLICY, [
      "superpowers:",
      "user_owned_tasks:",
      "parallel_worktree_subagents:",
      "acceptance_smoke:",
      "e2e_hint:",
      "显式发布候选构建必须为当前候选解析一次 E2E 选择",
      "$desktop-test-gui-initialization-e2e",
      "九项 GUI profile",
      "dialog:default",
      "deep_link = enabled",
      "宿主无法判定/观察适用场景",
    ]],
    [gateFile, [
      "显式构建、缺少环境证据、新任务或新会话本身都不得触发它",
      "门禁成功后只重试原失败命令一次",
      "development-environment-gates.sh --install-missing",
      "development-environment-gates.ps1",
      "Git、Rust 与 Node.js/npm 始终为必需项",
      "pnpm",
      "not-required",
      "rustup --version",
      "node --version",
      "https://static.rust-lang.org/rustup/dist",
      "https://nodejs.org/dist",
      "MSVC Build Tools",
      "upgrade-required",
      "当前用户标准全局根",
      "不建立 Harness 私有持久 env",
      "macos-tauri-xwin-gates.sh --install-missing",
      "cargo-xwin",
      "缺少 Homebrew 时阻断",
      "xwin 成功仍把 Windows runtime 记为 `Unverified`",
    ]],
    [rustBaseline, [
      "$desktop-check-development-environment",
      "Node.js | 所有接口",
      "pnpm | 仅 GUI",
      "example_tool_core = { path = \"example_tool_core\" }",
      "<项目标识>_core",
      "<项目标识>_cli",
      "_tui",
      "_mcp",
      "_gui",
      "[workspace.metadata.agent-first-harness]",
      "scaffold status",
      "productDefinitionRequired=true",
      "$desktop-define-product",
      "user_owned_tasks",
      "gui-initialization-config",
      "dialog:default",
      "Ratatui + tui-realm + tui-realm-stdlib",
      "Vite + React + TypeScript + Mantine UI",
      "verify-gui-lifecycle-contract.mjs",
      "660×400",
      "Tokio",
      "Axum + Tower/Tower HTTP",
      "Clap",
      "SeaORM",
      "config-rs",
      "tracing + tracing-subscriber + tracing-appender",
      "OpenTelemetry OTLP/HTTP",
      "anyhow",
      "thiserror",
      "serde",
      "jiff",
    ]],
    [PRODUCT_SPEC, [
      "HARNESS-FEAT-BATCHED-BASE-INITIALIZATION-FORM",
      "首轮必须一次列出全部尚未解析的基础字段",
      "基础字段全部解析后才进入条件阶段",
      "CLI/TUI/MCP/GUI",
      "未选择任何接口时默认 CLI",
      "docs/AGENT_POLICY.md",
      "scaffold status",
      "productDefinitionRequired=true",
      "独立 `main` 仓库",
      "$desktop-prepare-gui-app-identity",
      "$desktop-test-gui-initialization-e2e",
      "gui-initialization-config",
      "dialog:default",
      "660×400",
      "Tokio",
      "Axum + Tower/Tower HTTP",
      "Clap",
      "SeaORM",
      "config-rs",
      "tracing-subscriber",
      "tracing-appender",
      "OpenTelemetry",
      "anyhow",
      "thiserror",
      "serde",
      "jiff",
    ]],
    [path.join(ROOT, "README.md"), [
      "## 当前模板仓库的请求边界",
      "Agent 只接受两类信息",
      "只解析允许的初始化字段",
      "CLI、TUI、MCP、GUI",
      "系统托盘、系统通知、开机自启",
      "独立、无远端、带初始化提交的 Git 仓库",
    ]],
    [GUI_DIALOG_SKILL, [
      "tauri-plugin-dialog",
      "@tauri-apps/plugin-dialog",
      "workspace = true",
      "tauri_plugin_dialog::init()",
      "dialog:default",
      "不安装或授权 fs 插件",
    ]],
    [path.join(ROOT, "LICENSE.zh-CN.md"), [
      "本协议不是开源许可证",
      "终端下游与禁止继续衍生",
      "适用项目名称：毕方桌面应用Harness模版",
      "仅将该名称替换",
    ]],
    [path.join(ROOT, "LICENSE.en.md"), [
      "This is not an open-source license",
      "Terminal Downstream Project; No Further Derivation",
      "Applicable Project Name: Bifang Desktop Harness Template",
      "only this name must be replaced",
    ]],
    [path.join(RENAME_ROOT, "agents", "openai.yaml"), [
      "重命名项目身份",
      "$desktop-rename-project-identity",
    ]],
    [GITIGNORE, [
      "/target/",
      "**/node_modules/",
      "**/dist/",
      "**/coverage/",
      ".env.*",
      "!.env.example",
      ".DS_Store",
    ]],
    [path.join(ROOT, "docs", "CLI_CONTRACT.md"), [
      "<项目标识>_cli",
      "scaffold status",
      "productDefinitionRequired=true",
    ]],
  ]);
}
