import path from "node:path";

import { SKILLS_ROOT } from "./core.mjs";
import {
  CORE_FIRST_CHECKER,
  ENVIRONMENT_SKILL,
  ENVIRONMENT_TESTS,
  GIT_LIFECYCLE_ROOT,
  GUI_E2E_ROOT,
  GUI_E2E_SCRIPTS,
  INITIALIZE_SKILL,
  INSTANTIATE_FORM,
  INSTANTIATE_SKILL,
  INSTANTIATE_TARGET_RESOLVER,
  INSTANTIATE_TARGET_RESOLVER_TESTS,
  LINE_LIMIT_CHECKER,
  RENAME_ROOT,
  RENAME_SCRIPT,
  RENAME_TESTS,
  RUST_COMMENT_CHECKER,
  VERSION_GATE,
} from "./initialization_paths.mjs";

const lifecycleScript = path.join(GIT_LIFECYCLE_ROOT, "scripts");

/** Return the high-value initialization files and literal contracts they must retain. */
export function primaryRequiredFragments(skillFile = INITIALIZE_SKILL) {
  const contracts = new Map([
    [INSTANTIATE_SKILL, [
      "只收集 Harness 创建终端下游所需的固定初始化信息",
      "中文项目展示名称",
      "ASCII `snake_case` 项目标识",
      "resolve_project_target.mjs",
      "不得接收、分析、记录到源仓库",
      "$desktop-initialize-rust-project",
    ]],
    [path.join(path.dirname(INSTANTIATE_SKILL), "agents", "openai.yaml"), [
      "$desktop-instantiate-project",
      "初始化",
    ]],
    [INSTANTIATE_FORM, [
      "## 首轮基础问题模板",
      "## 字段阶段与顺序",
      "user_owned_tasks",
      "parallel_worktree_subagents",
      "system_tray",
      "system_notification",
      "global_shortcut",
      "sidebar_mode",
      "node .agents/skills/desktop-instantiate-project/scripts/resolve_project_target.mjs",
      "区分大小写地精确相等",
      "targetRoot",
    ]],
    [INSTANTIATE_TARGET_RESOLVER, [
      "parseArgs",
      "harness-root",
      "project-path",
      "project-id",
      "targetRoot",
      "isSymbolicLink",
      "realpathSync",
    ]],
    [INSTANTIATE_TARGET_RESOLVER_TESTS, [
      "exact_final_name_reuses_input_path",
      "similar_but_not_equal_final_name_still_appends_project_id",
      "final_target_symlink_is_rejected",
      "existing_nonempty_final_target_is_rejected",
      "harness_root_or_ancestor_is_rejected",
    ]],
    [skillFile, [
      "CLI 是可选接口",
      "user_owned_tasks: disabled",
      "parallel_worktree_subagents: disabled",
      "Node.js",
      ">=24.21.0",
      "pnpm",
      "workspace = true",
      "[workspace.metadata.agent-first-harness]",
      "$desktop-manage-version init",
      "productDefinitionRequired=true",
      "Core-first 是永久硬规则",
      "macos-dmg-background.png",
      "660×400",
      "唯一基线提交",
      "未选择侧栏模式必须写入 `sidebar_mode = detailed`",
      "显式非法值不得按未选择处理",
      "$desktop-test-gui-initialization-e2e",
      "`gui-initialization-config`",
      "$desktop-add-gui-system-locale",
      "$desktop-add-gui-updater",
      "$desktop-add-gui-window-state",
      "$desktop-add-gui-dialog",
      "最终九项不得缺失或残留 `pending`",
      "`deep_link = enabled` 且 `single_instance != enabled` 是非法组合",
      "结构检查器先验证唯一九字段、组合约束、四项固定基线和每个独立能力的启用完整/禁用无残留",
      "Tokio",
      "Axum + Tower/Tower HTTP",
      "Clap",
      "SeaORM",
      "config-rs",
      "tracing + tracing-subscriber + tracing-appender",
      "OpenTelemetry",
      "anyhow",
      "thiserror",
      "serde",
      "jiff",
    ]],
    [ENVIRONMENT_SKILL, [
      "Git 与 Rust 始终",
      "Node.js 是所有下游 Harness helper 的通用工程运行时",
      "只有已记录的接口选择包含 `GUI` 时才要求 pnpm",
      ">=24.21.0",
      ">=12.4.1",
      "--check-only",
      "upgrade-required",
      "失败关闭",
      "AFH_TEST_MODE=1",
    ]],
    [VERSION_GATE, [
      "parseArguments",
      "migration-approved",
      "version-state.json",
      "pending_changes",
      "applied_bug_ids",
    ]],
    [CORE_FIRST_CHECKER, ["export function", "Cargo.toml", "workspace"]],
    [LINE_LIMIT_CHECKER, ["export function", "max", "lines"]],
    [RUST_COMMENT_CHECKER, ["export function", "Cargo.toml", "Rust"]],
    [path.join(GIT_LIFECYCLE_ROOT, "SKILL.md"), [
      "创建本地分支不要求配置远端",
      "Git common-dir",
      "--also-remote",
      "pendingPublish",
      "--release-context-sha256",
      "local-only",
      "`v{version}-{YYYYMMDD}`",
      "不设置任何分支门禁",
    ]],
    [path.join(lifecycleScript, "git_lifecycle.mjs"), [
      "parseArguments",
      '"inspect"',
      '"start"',
      '"track-worktree"',
      '"publish"',
      '"release"',
    ]],
    [path.join(lifecycleScript, "git_lifecycle_core.mjs"), [
      'STATE_DIRECTORY = "agent-first-harness"',
      'STATE_FILENAME = "git-lifecycle.json"',
      "resolveAdditionalRemoteTargets",
      "pendingPublish",
      "commandTrackWorktree",
    ]],
    [path.join(lifecycleScript, "git_lifecycle_publication.mjs"), [
      "export function publish",
      "pendingPublish",
      "RELEASE_CONTEXT_PATH",
      "commandRelease",
    ]],
    [path.join(lifecycleScript, "git_publication_report.mjs"), [
      "primaryFailureMessage",
      "additionalFailureMessage",
      "pendingFailure",
    ]],
    [path.join(lifecycleScript, "git_lifecycle_test_support.mjs"), [
      "git_lifecycle.mjs",
      "lifecycleFixture",
      "spawnHelper",
    ]],
    [path.join(lifecycleScript, "git_lifecycle.test.mjs"), [
      "help_and_invalid_arguments_are_single_line_json",
      "--also-remote",
      "scenario(",
    ]],
    [path.join(lifecycleScript, "git_lifecycle_release.test.mjs"), [
      "--release-context-sha256",
      "--local-only",
      "release-context-mismatch",
    ]],
    [path.join(lifecycleScript, "git_publication_test_cases.test.mjs"), [
      "pendingPublish",
      "--also-remote",
      "publication",
    ]],
    [path.join(RENAME_ROOT, "SKILL.md"), [
      "--old-display-name-zh",
      "--new-display-name-en",
      "--old-id",
      "--rename-root",
      "LICENSE.zh-CN.md",
      "LICENSE.en.md",
      "残留",
    ]],
    [path.join(SKILLS_ROOT, "desktop-add-gui-adapter", "SKILL.md"), [
      "设置页固定区始终只渲染当前应用名/带一个小写 `v` 的版本",
      "唯一 `gui-initialization-config` 代码块",
      "$desktop-add-gui-system-locale",
      "$desktop-add-gui-updater",
      "$desktop-add-gui-window-state",
      "$desktop-add-gui-dialog",
      "全局快捷键空 contract 不增加占位",
    ]],
    [RENAME_SCRIPT, [
      "EXCLUDED_DIRECTORIES",
      "old-display-name-zh",
      "new-display-name-en",
      "不允许符号链接",
      "目标已存在",
      "residuals",
    ]],
    [RENAME_TESTS, [
      "preview_then_apply_renames_content_paths_and_licenses",
      "existing_destination_blocks_without_overwrite",
      "symbolic_link_blocks_before_write",
      "explicit_root_rename_moves_project_without_overwrite",
    ]],
    [path.join(GUI_E2E_ROOT, "SKILL.md"), [
      "Computer Use",
      "九项",
      "verify-gui-lifecycle-contract.mjs",
      "pnpm tauri build --debug --no-bundle",
      "新实例化目标在本 E2E 阶段不得提前 `git init`",
      "同时验证 `$desktop-add-gui-dialog` 固定 WebView 基线",
      "`single_instance: enabled`",
      "`deep_link: enabled`",
      "`global_shortcut: enabled`",
      "`system_tray: enabled`",
      "close_last_window_exits_application",
      "icons/32x32.png",
      "有且只有一个 `gui-initialization-config` 围栏代码块",
    ]],
    [path.join(GUI_E2E_SCRIPTS, "verify-gui-lifecycle-contract.mjs"), [
      "gui-initialization-config",
      "system_tray",
      "single_instance",
      "sidebar_mode",
      "初始化器应在用户未选择时写入 detailed",
      "close_last_window_exits_application",
      "GUI 初始化配置 deep_link = enabled 必须同时满足 single_instance = enabled",
    ]],
    [path.join(GUI_E2E_SCRIPTS, "gui-lifecycle-plugin-contract.mjs"), [
      "validateDialogRuntime",
      "validateFixedIpcRuntimeContract",
      "validateGlobalShortcutRuntimeContract",
      "allowedInitializationCommands",
    ]],
    [path.join(GUI_E2E_SCRIPTS, "gui-lifecycle-plugin-contract.test.mjs"), [
      "dialog_dependencies_are_fixed",
      "deep-link without single-instance",
      "empty updater configuration",
      "fixed metadata and locale commands",
      "dialog_plugin_is_registered_once_in_fixed_order",
      "rejects treating tauri_plugin_os locale as a Result",
      "rejects updater code that can check before the NotConfigured gate",
      "rejects window-state setup that is not wired through the recoverable helper",
      "rejects opening deep-link runtime registration APIs on the neutral restore path",
      "rejects a global shortcut handler that fires on press and release",
      "rejects duplicate notification and autostart plugin registrations",
      "rejects enabled commands omitted from the merged invoke handler",
      "rejects constant-true assertions in fixed plugin tests",
    ]],
  ]);

  const environmentTests = [
    [ENVIRONMENT_TESTS[0], [
      "Rust-only project requires Node but not pnpm",
      "newer stable Rust and Git versions satisfy continuous minimums",
      "lower Node and pnpm versions require upgrade in check-only",
      "removed WEB interface is rejected",
    ]],
    [ENVIRONMENT_TESTS[1], [
      "missing Git is installed and reprobed",
      "Node is installed for a non-GUI project while pnpm remains optional",
      "Rust upgrade that remains below MSRV fails closed",
      "Node checksum mismatch blocks before installation",
    ]],
    [ENVIRONMENT_TESTS[2], [
      "user tool directory symlinks fail before installation",
      "an unmanaged node symlink is never replaced",
      "managed Rust root symlinks fail before download",
    ]],
    [ENVIRONMENT_TESTS[3], [
      "PowerShell gate declares Node as common runtime and pnpm as GUI-only",
      "Windows Node minimum is continuous for every interface",
      "Windows pnpm is required only for GUI",
    ]],
    [ENVIRONMENT_TESTS[4], [
      "existing environment passes without installing",
      "missing environment is installed and reprobed",
      "outdated cargo-xwin is upgraded and reprobed",
      "non-macOS host and unsupported target are rejected",
    ]],
  ];
  for (const [file, fragments] of environmentTests) contracts.set(file, fragments);

  const fixedGuiSkills = [
    "desktop-add-gui-system-locale",
    "desktop-add-gui-updater",
    "desktop-add-gui-window-state",
    "desktop-add-gui-dialog",
  ];
  for (const name of fixedGuiSkills) {
    contracts.set(path.join(SKILLS_ROOT, name, "SKILL.md"), ["name:", "GUI"]);
  }
  return contracts;
}
