"""初始化主契约的必需片段。"""

from __future__ import annotations

from pathlib import Path

from .context import *  # noqa: F403


def primary_required_fragments(
    skill_file: Path,
) -> dict[Path, tuple[str, ...]]:
    """返回实例化、初始化和接口能力的主契约片段。"""

    return {
        INSTANTIATE_SKILL: (
            "references/initialization-form.md",
            "在任何写入或环境安装前完成初始化表单",
            "首轮一次询问全部尚未解析的基础字段",
            "中文项目展示名称、英文项目展示名称",
            "只提供其中一个时，Agent 自动翻译并补齐另一个",
            "中英文名称、各自来源",
            "不能拆成逐字段多轮",
            "基础字段全部解析后",
            "每轮只询问一个当前适用的条件字段",
            "ASCII `snake_case` 项目标识",
            "产品目的、核心输入/输出、业务规则、成功标准",
            "即使用户同时提供，也不得接收、分析、记录到源仓库",
            "切换到唯一终端下游根目录后",
            "重新提出",
            "scripts/resolve_project_target.py",
            "最后一个名称与 `<project-id>` 区分大小写地精确相等",
            "`<项目路径>/<project-id>`",
            "不得用大小写、连字符/下划线转换、前后缀或相似度",
            "父目录可以存在且非空",
            "通过符号链接解析到任何禁止位置的路径",
            "以免将 Harness 复制到其内部目标时发生递归",
            "唯一项目根目录",
            "不执行 Git 可用性、版本、身份、提交模板或仓库配置检查",
            "下一步将实际创建基线提交",
            "docs/adr/",
            "docs/changelog/",
            "docs/product_spec/",
            "docs/work_plan/",
            "docs/verification/",
            "历史验证正文",
            "不得仅为实例化创建产品规格、工作计划、ADR、变更记录或 `docs/VERIFICATION.md`",
            "创建恰好一个本地基线提交",
            "$desktop-test-gui-initialization-e2e",
            "不得在复制后重新发起一轮问询",
            "系统托盘、系统通知、开机自启、关于页、赞助页、单实例",
            "`compact`/`detailed` 侧栏模式",
            "用户跳过侧栏模式时必须已归一化为 `sidebar_mode = detailed`",
            "显式非法值必须在表单阶段重新确认",
            "九项无 `pending` 事实",
            "配置感知结构检查和 GUI 初始化 E2E",
            "单实例、托盘、系统通知、开机自启、深链接与全局快捷键只在启用时执行各自结构/宿主场景",
            "托盘禁用时必须证明没有 feature/托盘/关闭拦截且关闭最后窗口结束进程",
            "E2E 始终验证所选侧栏模式",
            "关于/赞助入口按选择存在或缺席",
            "未选能力不作为缺证据",
            "不得在经过选择性复制的目标目录中运行模板级 Harness 验证器",
            "LICENSE.zh-CN.md",
            "LICENSE.en.md",
            "逐字节复制两份许可证文件",
            "完整 `docs/design_standards/`",
            "$desktop-rename-project-identity",
            "整个受维护的目标树",
            "Applicable Project Name",
            "所有其他法律文本必须与复制后的源文件保持字节等价",
            "保留 `$desktop-rename-project-identity` 供未来已批准的产品改名使用",
            "$desktop-upgrade-harness",
            "$desktop-manage-git-lifecycle",
            "完整 Skill 目录、helper 和回归测试必须进入固定快照",
            "不运行 `start`、`publish` 或 `release`",
            "Git common-dir 生命周期清单不是 tracked 资产",
            "`.harness/release-context.json` 也只能在未来一次真实发布准备中产生",
            "无 remote 的独立 `main` 基线仍是唯一初始结果",
            "推荐预设",
            "自定义",
            "superpowers: disabled",
            "parallel_worktree_subagents: enabled",
            "milestone_smoke: enabled",
            "milestone_e2e: disabled",
            "Harness 源字段值不是下游确认",
            "不得静默采用预设",
            "一次原子写入",
            "不得再次询问目标平台、预设、策略或接口",
            "左侧 Task 描述模板",
            "精确保存项目/`projectId`",
            "`SETUP_PENDING` 有界返回",
            "`{序号}|{Task简述}|{当前进度} |{功能摘要}` 统一格式",
            "每次真实转换至多一次更新",
            "失败不阻断已完成结果",
            'title="{序号}|{Task简述}|已分配 |{功能摘要}"',
            "稳定正整数序号",
            "同一 `hostId` 与精确 `projectId`",
            "`list_threads(limit=50)`",
            "`list_archived_threads`",
            "最大有效序号加 1",
            "空历史才从 1 开始",
            "缺号不回填",
            "隐藏 Subagent 不占用项目序列",
            "显示标题与独立 ASCII `feature-summary`/Subagent `task_name` 分离",
            "内部 Subagent 遵守标题格式但不得冒充左侧 Task",
            "从具名或 detached HEAD 直接建立并登记 `feature-*` 分支",
            "`codex/unit-*`",
            "仅属于 Harness 的根目录 `Version.md`",
            "根 `Cargo.toml`",
            "[workspace.metadata.agent-first-harness]",
            "`target-platforms` 与 `interfaces`",
            "不得遗留空数组或根据新会话重新猜测",
            ".agents/skills/desktop-initialize-rust-project/assets/gui/macos-dmg-background.png",
            "$desktop-configure-git-commits",
            "环境门禁检查 Git",
            "仓库初始化、作者身份与模板仍统一推迟到全部脚手架和一次性裁剪完成",
            "安装和检查仓库本地提交模板",
            "不得修改全局 Git 配置",
        ),
        SKILLS_ROOT / "desktop-instantiate-project" / "agents" / "openai.yaml": (
            "只收集 Harness 初始化信息",
            "$desktop-instantiate-project",
            "只收集 Harness 创建终端下游所需的双语名称和固定初始化字段",
            "拒绝接收产品业务需求",
            "切换至下游后重新提出",
            "表单确认后先门禁 Git",
            "完成中性脚手架后再建立独立仓库与 local 身份",
        ),
        INSTANTIATE_FORM: (
            "首次问询必须用一份清晰编号的表单",
            "一次列出其中全部尚未解析字段",
            "基础字段全部解析前不得进入条件问询",
            "每次回复只询问一个当前适用且尚未解析的条件字段",
            "首轮基础问题模板",
            "首轮基础",
            "条件补全",
            "中文项目展示名称",
            "英文项目展示名称",
            "中英文项目展示名称至少由用户直接提供一个",
            "自动翻译得到的名称必须标记来源",
            "用户对汇总的确认同时构成对译名的确认",
            "`project_id`",
            "项目路径",
            "负责人",
            "目标平台",
            "接口组合",
            "Agent 策略模式",
            "`system_tray`",
            "`system_notification`",
            "`autostart`",
            "`about_page`",
            "`sponsor_page`",
            "`single_instance`",
            "`deep_link`",
            "`global_shortcut`",
            "`sidebar_mode`",
            "完整汇总",
            "区分大小写地精确相等",
            "`<项目路径>/<project_id>`",
            "相似度",
            "作为父目录输入的项目路径可以已经存在并包含其他项目或文件",
            "helper 输出的 `targetRoot`",
            "当前 Harness 源只接收创建终端下游所必需的本表字段",
            "即使用户主动提供，也不得把这些内容解析为表单字段",
            "切换到 helper 返回的唯一 `targetRoot` 后",
            "重新提出",
        ),
        INSTANTIATE_TARGET_RESOLVER: (
            "SNAKE_CASE",
            "input_kind = \"target-root\" if input_path.name == project_id else \"parent-directory\"",
            "target_lexical = input_path if input_kind == \"target-root\" else input_path / project_id",
            "最终项目根目录不是空目录",
            "最终项目根目录不得是 Harness 根目录或其祖先",
            '"targetRoot": str(target_root)',
            '"targetState": state',
        ),
        INSTANTIATE_TARGET_RESOLVER_TESTS: (
            "test_exact_final_name_reuses_input_path",
            "test_parent_path_appends_project_id_even_when_parent_is_nonempty",
            "test_similar_but_not_equal_final_name_still_appends_project_id",
            "test_existing_nonempty_final_target_is_rejected",
            "test_final_target_symlink_is_rejected",
            "test_harness_root_or_ancestor_is_rejected",
        ),
        skill_file: (
            "$desktop-check-development-environment",
            "只有包含 `GUI` 的选择才增加阻断性的 Node.js 和 pnpm 门禁",
            "完整删除 `.agents/skills/desktop-instantiate-project/`、`.agents/skills/desktop-initialize-rust-project/` 和初始化专用的 `.agents/skills/desktop-test-gui-initialization-e2e/`",
            "## Skills 地图",
            "## 约束地图",
            "workspace = true",
            "只能从 `CLI`、`TUI`、`MCP` 和 `GUI` 中选择",
            "目标平台只能从 `Windows`、`macOS`、`Linux` 中选择至少一项",
            "`[workspace.metadata.agent-first-harness]` 下 `target-platforms` 和 `interfaces`",
            "任何空数组、`pending` 或未知值都阻断初始化基线",
            "$desktop-build-tauri-local-install",
            "用户明确选择默认值或跳过接口选择时记录 `CLI`",
            "不得静默附加 CLI",
            "docs/AGENT_POLICY.md",
            "推荐预设",
            "自定义",
            "superpowers: disabled",
            "parallel_worktree_subagents: enabled",
            "milestone_smoke: enabled",
            "milestone_e2e: disabled",
            "Harness 源字段值不是下游确认",
            "不得静默采用推荐值",
            "一次原子写入",
            "只验证并复用，不再次询问",
            "统一描述模板",
            "`{序号}|{Task简述}|{当前进度} |{功能摘要}` 统一格式",
            "每次真实转换至多一次更新",
            "失败不阻断已完成结果",
            "同一 `hostId` 与精确 `projectId`",
            "`list_threads(limit=50)`",
            "`list_archived_threads`",
            "最大有效序号加 1",
            "空历史才从 1 开始",
            "缺号不回填",
            "隐藏 Subagent 不占用项目序列",
            "内部 Subagent/agent thread",
            "左侧 Task 的保存项目绑定、setup 状态机和独立 Worktree 交付契约",
            "`codex/unit-*`",
            "$desktop-add-cli-adapter",
            "$desktop-add-tui-adapter",
            "$desktop-add-mcp-adapter",
            "$desktop-add-gui-adapter",
            "_cli",
            "_tui",
            "中性脚手架状态",
            "productDefinitionRequired=true",
            "产品目的、核心输入/输出、业务规则、成功标准",
            "不得在 Harness 源或中性初始化阶段接收、分析、记录或实现",
            "包含根 `Version.md` 与活动 `$desktop-instantiate-project` 的 Harness 源项目",
            "Harness 源只处理自身工程维护和创建下游所需的固定初始化信息",
            "业务 core 或适配器变化都直接实施",
            "不为中性初始化创建产品规格、计划、ADR、Changelog 或 Verification",
            "$desktop-define-product",
            "Ratatui + tui-realm + tui-realm-stdlib",
            "Vite + React + TypeScript + Mantine UI + `@tabler/icons-react` + TanStack Router 文件路由 + TanStack Query + Jotai",
            "@tabler/icons-react",
            "git --version",
            "git init --initial-branch=main .",
            "git rev-parse --show-toplevel",
            "git status --porcelain=v1 --untracked-files=all",
            "git remote",
            "chore: initialize project",
            "已有有效身份保持不变",
            "只写当前仓库 local 配置",
            "docs/adr/",
            "docs/changelog/",
            "docs/product_spec/",
            "docs/work_plan/",
            "docs/verification/",
            "`docs/verification/` 仍然不存在",
            "`docs/harness_engineering/`",
            "只运行初始化本身必需的非空测试",
            "当前项目根目录必须同时是唯一的下游根目录及其独立 Git 顶层目录",
            "项目根目录 `.gitignore`",
            "根锚定的 `/release/`",
            "Tokio current-thread 异步入口",
            "Tauri 由 Tokio 支撑的异步运行时",
            "Tokio、Axum + Tower/Tower HTTP、Clap、SeaORM、config-rs、tracing + tracing-subscriber + tracing-appender、anyhow、thiserror、serde、jiff",
            "OpenTelemetry",
            "不得为中性状态预装未使用的 HTTP、ORM、配置、错误或可观测性依赖",
            "LICENSE.zh-CN.md",
            "LICENSE.en.md",
            "保留继承的两份非开源企业专有商业许可证文件",
            "当前中英文项目展示名称",
            "只提供其中一个时自动翻译另一个",
            "名称语言错配",
            "$desktop-rename-project-identity",
            "$desktop-run-parallel-worktrees",
            "$desktop-upgrade-harness",
            "$desktop-manage-git-lifecycle",
            "`SKILL.md`、`agents/openai.yaml`、`scripts/git_lifecycle.py` 和 `scripts/test_git_lifecycle.py`",
            "不运行 `start`、`publish` 或 `release`",
            "Git common-dir 中的生命周期清单只在初始化后首次真实开发时由 helper 创建",
            "不得预创建 `.harness/release-context.json`",
            "不自动创建左侧 Task",
            "无 remote 的独立 `main` 基线仍是唯一初始结果",
            "$desktop-configure-git-commits",
            "identity-report",
            "identity-bootstrap",
            "identity-check",
            "configure_git_commit.py install --project-root .",
            "configure_git_commit.py check --project-root .",
            "git config --local",
            "只有用户明确批准后才可使用 `--replace`",
            "提交模板本地配置与检查结果",
            "完整表单确认后、首次脚手架写入前",
            "gate.git.status/version/change",
            "紧邻真实初始化基线提交时",
            "选择 GUI 时同时完整保留 `$desktop-add-gui-dialog`、`$desktop-prepare-gui-support-surfaces`（包括 `assets/brand-support/**`）",
            "不得预创建 `docs/GUI_SUPPORT_SURFACES.md`",
            "必须在同一首轮一次列出",
            "每轮只询问一个尚未解析的 GUI 条件字段",
            "不得在复制后重新询问接口、中英文名称或目标平台",
            "`system_tray`、`system_notification`、`autostart`、`about_page`、`sponsor_page`、`single_instance`、`deep_link`、`global_shortcut`、`sidebar_mode`",
            "`gui-initialization-config`",
            "未选择侧栏模式必须写入 `sidebar_mode = detailed`",
            "显式非法值不得按未选择处理",
            "最终九项不得缺失或残留 `pending`",
            "`deep_link = enabled` 且 `single_instance != enabled` 是非法组合",
            "$desktop-add-gui-system-locale",
            "$desktop-add-gui-updater",
            "$desktop-add-gui-window-state",
            "$desktop-add-gui-dialog",
            "并严格按 profile 调用其余独立 GUI 能力 Skills",
            "system-locale、updater、window-state、dialog 四项固定宿主基线始终接入且不增加问询",
            "中央初始化器不得复制实现或为四者写 profile 开关",
            "$desktop-add-gui-system-notifications",
            "$desktop-add-gui-autostart",
            "$desktop-add-gui-system-tray",
            "$desktop-add-gui-single-instance",
            "$desktop-add-gui-deep-link",
            "$desktop-add-gui-global-shortcut",
            "`{applicationName} v{version} {contactChannel}:{contactValue}`",
            "全局快捷键选项必须说明只安装 Rust-only 能力",
            "中性 contract 保持空动作、零默认 chord 和零 OS 注册",
            "global-shortcut 启用时写入并消费唯一空 action contract",
            "不得复制旧默认 chord/恢复动作",
            "不含隐私/统计",
            "对系统托盘、系统通知、开机自启、关于页、赞助页、单实例、深链接、全局快捷键分别报告 `enabled`/`disabled`",
            "`tauri-gui-sidebar-compact-80-v1`",
            "`80px` 栏宽",
            "`6px` 内容内边距",
            "`36px` Logo",
            "`22px`/`1.75` 图标",
            "`11px`/`1.25` 全宽居中名称",
            "`56px` 菜单项",
            "禁止固定 `em/ch` 名称盒和折叠按钮",
            "`detailed` 精确命中 `tauri-gui-sidebar-detailed-v1`",
            "自身按钮收起为 `76px`/`44px` Logo",
            "Mantine `Tooltip`",
            "独立设备偏好",
            "不含隐私/统计",
            "浅色/深色/跟随系统",
            "页面工作状态继续由应用根 Jotai store 仅在当前进程跨路由保留",
            "三态主题和亮暗语义主题始终存在",
            "`candidate-1`、`candidate-2`、`candidate-3`",
            "始终按该顺序同时展示原始候选",
            "用户选择前不得验证格式、尺寸、色彩、像素、摘要或质量",
            "用户明确选择后只验证和按需标准化所选项",
            "拒绝项不补做处理",
            "<project-id>_gui/src-tauri/icons/app-icon-master.png",
            "<project-id>_gui/public/app-identity/logo.png",
            "$desktop-test-gui-initialization-e2e",
            "结构检查器先验证唯一九字段、组合约束、四项固定基线和每个独立能力的启用完整/禁用无残留",
            "dialog 固定结构检查必须覆盖 Rust/前端依赖、唯一 Builder 顺序、主窗口 `dialog:default` 和无 fs 授权",
            "构建并启动真实本机调试二进制",
            "执行所选侧栏、设置页、页面、窗口状态、单实例、托盘、通知、自启、深链接、快捷键及关闭语义中的全部适用场景",
            "所有由测试创建的登录项、window-state 数据、快捷键注册和进程必须恢复/回收",
            "只能由 macOS 已打包应用证明的静态 scheme 系统注册明确留给候选补验",
            "未选能力不得被当作缺证据",
            "仍包含旧 Harness 身份",
            ".agents/skills/desktop-initialize-rust-project/assets/gui/macos-dmg-background.png",
            "<project-id>_gui/src-tauri/dmg/background.png",
            "bundle.macOS.dmg.background",
            "./dmg/background.png",
            "660×400",
        ),
        ENVIRONMENT_SKILL / "SKILL.md": (
            "只接受两类触发",
            "不得仅因首次修改代码、新任务、新会话、显式构建",
            "门禁成功后只重试原失败命令一次",
            "Rust 始终是常规阻断门禁",
            "仅当已记录的接口选择包含 `GUI` 时，Node.js 和 pnpm 才是常规阻断门禁",
            "必须把两者都报告为 `not-required`",
            "由中性 `$desktop-initialize-rust-project` 调用时",
            "不得为普通开发预建 Verification",
            "本 Skill 及其脚本在下游初始化后必须保留",
            "scripts/macos-tauri-xwin-gates.sh --install-missing",
            "不自动安装 Homebrew",
            "只证明交叉工具可用，不证明 Windows 运行时",
        ),
        GUI_NOTIFICATION_SKILL: (
            "system_notification = enabled",
            'tauri-plugin-notification = "2.4.0"',
            'mac-usernotifications = "0.3.1"',
            "Windows 与 Linux 使用官方 `tauri-plugin-notification` Rust API",
            "现代 `UNUserNotificationCenter` 异步 API",
            "不得退回已废弃的 `NSUserNotificationCenter`",
            "WebView 不安装 `@tauri-apps/plugin-notification`",
            "单个串行通知 worker",
            "应用 runtime state 拥有",
            "先完成系统权限请求",
            "只有明确授权后才原子持久化 `true`",
            "中性 scaffold 不发送测试通知",
            "Switch 自身点击",
            "system_notification_worker_is_owned_and_cancelled",
            "disabled 配置拒绝通知依赖",
        ),
        GUI_NOTIFICATION_SKILL.parent / "agents" / "openai.yaml": (
            "添加 GUI 系统通知",
            "$desktop-add-gui-system-notifications",
        ),
        GUI_AUTOSTART_SKILL: (
            "autostart = enabled",
            'tauri-plugin-autostart = "2.5.1"',
            "MacosLauncher::LaunchAgent",
            "前端不安装 `@tauri-apps/plugin-autostart`",
            "初始化插件但不调用 `enable()`",
            "OS 登录项注册状态是唯一权威事实",
            "失败时返回稳定错误并重新读取实际状态",
            "开关事件只绑定 Switch 自身",
            "恢复原状态并再次确认",
            "autostart_e2e_restores_previous_registration",
            "disabled 配置拒绝插件依赖",
        ),
        GUI_AUTOSTART_SKILL.parent / "agents" / "openai.yaml": (
            "添加 GUI 开机自启",
            "$desktop-add-gui-autostart",
        ),
        GUI_GLOBAL_SHORTCUT_SKILL: (
            "完整读取并执行 [绑定契约](references/binding-contract.md)",
            "中性初始化只建立 Rust-only 宿主能力",
            "`schemaVersion = 1`、`actions = []`",
            "没有产品动作、默认 chord、OS 注册或快捷键界面",
            "产品实现只从已批准 Product Spec、当前请求和 GUI profile 取得动作、初始绑定、是否可编辑及安全验收事实",
            "不得从 Harness 示例推断",
            'tauri-plugin-global-shortcut = "2.3.2"',
            "WebView 不安装 `@tauri-apps/plugin-global-shortcut`",
            "`global-shortcut:*` ACL",
            "`disabled` 时该块、依赖、插件、注册器、命令、配置文件、UI/i18n 与专属测试全部缺席",
            "不得注入 `CommandOrControl+Shift+Space`、`restore_main_window`",
            "产品动作使用稳定 ID 映射到编译期登记的宿主动作或单个 core 用例",
            "回调只在 `ShortcutState::Pressed` 分派",
            "配置文本、期望绑定与 OS 实际注册状态分开建模",
            "未绑定使用 `null`/`Option::None`",
            "逐项报告配置 chord、`registered` 与稳定脱敏错误码",
            "原子替换/回滚",
            "只注销本模块实际拥有的 chord",
            "固定绑定显示只读 chord/动作/真实状态",
            "可编辑绑定提供录制、取消与清空",
            "空动作 contract 不生成占位界面",
            "中性初始化 E2E 证明启动时零绑定、零默认注册和清理无残留",
            "存在明确非空动作时才按安全场景触发实际 chord",
        ),
        GUI_GLOBAL_SHORTCUT_BINDING_CONTRACT: (
            "保留九字段 `gui-initialization-config`",
            "`global_shortcut = enabled|disabled`",
            '"bindingPolicy"',
            '"defaultChord"',
            '"dispatch"',
            '"e2eSafe"',
            "`fixed` 必须有需求明确给出的非空 `defaultChord`",
            "`user-configurable` 允许 `null`",
            "不得使用 fallback、推荐值或旧 Harness chord 填补 `null`",
            "`dispatch.kind = host-action`",
            "`core-use-case` 必须指向一个已批准、有类型且稳定的 core 用例",
            "`target` 使用 ASCII 小写 snake_case 或点分 snake_case",
            "三层状态不得合并",
            "`actionId`、`configuredChord: string | null`、`registered: boolean` 与 `errorCode: string | null`",
            "读取拒绝符号链接和超限/未知版本",
            "OS 注册成功后才持久化",
            "持久化失败时恢复旧注册与旧文件",
            "只响应 `Pressed`",
            "不得使用 `unregister_all()`",
            "录制开始必须先通过窄 Rust command 取得唯一 token",
            "录制期间不注销旧 binding",
            "`GLOBAL_SHORTCUT_ACTIONS` 必须是 profile contract 的逐字段等价物化",
            "typed dispatcher 必须为每个声明 target 有明确分支",
            "global_shortcut_initial_bindings_match_contract",
            "global_shortcut_registers_only_configured_bindings",
            "global_shortcut_dispatches_pressed_events_to_declared_actions",
            "global_shortcut_reports_real_registration_state",
            "global_shortcut_unregisters_owned_bindings_on_shutdown",
            "global_shortcut_setup_failure_unregisters_owned_bindings",
            "shortcut_bindings_require_modifier_and_reject_equivalent_duplicates",
            "global_shortcut_replace_rolls_back_on_registration_failure",
            "global_shortcut_persistence_failure_restores_previous_bindings",
            "global_shortcut_recording_suppresses_dispatch_until_released",
        ),
        GUI_GLOBAL_SHORTCUT_SKILL.parent / "agents" / "openai.yaml": (
            "按明确产品需求接入固定或可编辑且无默认绑定的全局快捷键能力",
            "$desktop-add-gui-global-shortcut",
            "不注入默认 chord",
        ),
        GUI_IDENTITY_SKILL: (
            "应用展示名称",
            "主窗口标题",
            "DMG 背景",
            "应用/Applications 落点",
            "自动生成",
            "确定性备选方案",
            "用户上传",
            "1024×1024",
            "初始化 Logo 模式",
            "正好 3 个",
            "`candidate-1`、`candidate-2`、`candidate-3`",
            "不得按完成时间、文件名、摘要、风格偏好",
            "用户选择前",
            "不得检查文件类型、尺寸、色彩空间、透明通道、像素可见性",
            "不得转码、缩放、裁剪、补边、改色、压缩、去元数据",
            "后续重显、说明和选择问题必须保持同一顺序",
            "只对所选候选执行验证和标准化",
            "拒绝的候选不得补做检查或处理",
            "<project-id>_gui/src-tauri/icons/app-icon-master.png",
            "<project-id>_gui/public/app-identity/logo.png",
            "icons/32x32.png",
            "可见的 32×32 8-bit RGBA 非交错普通文件",
            "由 `bundle.icon` 引用",
            "`default_window_icon()` 当作必需值",
            "docs/GUI_APP_PROFILE.md",
            "唯一 `gui-initialization-config` 围栏代码块",
            "`system_tray`、`system_notification`、`autostart`、`about_page`、`sponsor_page`、`single_instance`、`deep_link`、`global_shortcut`、`sidebar_mode`",
            "<project-id>_gui/src-tauri/dmg/background.png",
            "SHA-256",
        ),
        SKILLS_ROOT / "desktop-define-product" / "SKILL.md": (
            "## Harness 源门禁",
            "Harness 专用 `Version.md`",
            "活动 `.agents/skills/desktop-instantiate-project/SKILL.md`",
            "必须在读取、整理或写入任何产品需求前停止",
            "切换到已存在下游的唯一 Git/项目根目录，再重新提出产品需求",
            "中性 scaffold 约束",
            "$desktop-plan-change",
            "$desktop-implement-change",
        ),
        SKILLS_ROOT / "desktop-implement-change" / "SKILL.md": (
            "Git 根/分支和工作区",
            "`{序号}|{Task简述}|{当前进度} |{功能摘要}`",
            "把第三字段更新为 `运行中`",
            "保持三个稳定字段并把第三字段更新为 `检查中`",
            "更新为终态 `已完成`",
            "按真实 `threadId` 用 `list_threads` 做一次有界复读",
            "Harness 专用 `Version.md` 和活动 `$desktop-instantiate-project`",
            "任何产品目的、业务功能、产品专属 UI/文案/数据",
            "必须在写入前拒绝",
            "要求用户切换到终端下游后重新提出",
            "保护用户已有修改",
            "$desktop-check-development-environment",
            "只运行第 6 步的测试",
            "不得自动追加格式化、lint、静态、集成/契约、全仓测试、构建",
        ),
        SKILLS_ROOT / "desktop-verify-delivery" / "SKILL.md": (
            "源码提交",
            "版本/构建标识",
            "Unverified",
            "项目全部非空单元测试",
        ),
        SKILLS_ROOT / "desktop-build-rust-release" / "SKILL.md": (
            "下游项目根同时是其独立 Git 顶层目录",
            "`HEAD` 解析到真实源码提交",
        ),
        SKILLS_ROOT / "desktop-prepare-release" / "SKILL.md": (
            "独立 Git 顶层目录",
            "尚未生成的 `HEAD`",
        ),
        GIT_LIFECYCLE_SKILL: (
            "name: desktop-manage-git-lifecycle",
            "创建本地分支不要求配置远端",
            "Git common-dir",
            "不会写入项目受跟踪目录",
            "`v{version}-{YYYYMMDD}`",
            "不设置任何分支门禁",
        ),
        GIT_LIFECYCLE_METADATA: (
            "$desktop-manage-git-lifecycle",
            "管理 Git 生命周期",
        ),
        GIT_LIFECYCLE_SCRIPT: (
            'STATE_DIRECTORY = "agent-first-harness"',
            'STATE_FILENAME = "git-lifecycle.json"',
            'commands.add_parser("start"',
            'commands.add_parser("track-worktree"',
            'commands.add_parser("publish"',
            'commands.add_parser("release"',
        ),
        GIT_LIFECYCLE_TESTS: (
            "test_start_without_remote_is_idempotent_and_uses_common_dir_state",
            "test_publish_merges_switches_and_pushes_without_tag_or_cleanup",
            "test_release_tags_before_exact_cleanup_and_retry_is_idempotent",
        ),
        MCP_SKILL: (
            "不得要求另选目标目录",
            "<project-id>_mcp",
            "Tokio current-thread 异步入口",
            "测量确认的 CPU 密集工作",
            "不得用同步 I/O、休眠、进程等待或 CPU 密集工具工作阻塞 Tokio stdio 运行时",
        ),
        CLI_SKILL: (
            "CLI 是可选项",
            "<project-id>_cli",
            "docs/CLI_CONTRACT.md",
            "Tokio current-thread 异步入口",
            "测量确认的 CPU 密集工作",
            "不得用同步 I/O、休眠、进程等待或 CPU 密集循环阻塞异步运行时",
        ),
        TUI_SKILL: (
            "<project-id>_tui",
            "不要求 CLI",
            "Ratatui",
            "tui-realm",
            "tui-realm-stdlib",
            "硬规则例外",
            "references/tui-baseline.md",
            "Tokio current-thread 异步入口",
            "测量确认的 CPU 密集工作",
            "不得用同步 I/O、休眠、进程等待或 CPU 密集的渲染/数据工作阻塞 Tokio 运行时",
        ),
        TUI_BASELINE: (
            "Ratatui",
            "tui-realm",
            "tui-realm-stdlib",
            "最低兼容稳定组合",
            "最低直接版本解析",
            "硬规则例外 ADR",
            "Tokio current-thread 异步入口",
            "测量确认的 CPU 密集工作",
        ),
        REACT_BASELINE: (
            "Vite",
            "React 和 TypeScript",
            "Mantine UI",
            "@tabler/icons-react",
            "TanStack Router",
            "TanStack Query",
            "Jotai",
            "不得把 Query 结果镜像到 Jotai",
            "URL/search 只用于产品明确批准的可分享导航事实",
            "最低兼容稳定范围",
            "resolutionMode: lowest-direct",
            "TypeScript Compiler AST",
            "Vitest",
            "Testing Library",
            "$desktop-prepare-gui-support-surfaces",
            "前端不得持有远程服务或发布者长期秘密",
            "运行时只复制所选页面需要的资源",
            "初始化固定建立 `/settings`",
            "`/about` 与 `/sponsor` 按 profile 选择存在",
            "compact 为 `80px` 全宽居中竖排菜单且不折叠",
            "全宽居中竖排菜单且不折叠",
            "按 detailed 标准锁定默认 `248px` 展开、`72px` Logo",
            "自身折叠按钮、身份父级无动作、`76px`/`44px` 收起",
            "图标-only + Tooltip 与偏好持久化",
            "底部按已选赞助、固定设置、已选关于生成",
            "真实更新、强更或统计上报",
            'defaultColorScheme="auto"',
            "light`/`dark`/`auto",
            "未选页面不得有路由、导航入口或运行时资源",
            "pageSessionState.ts",
            "route unmount/remount",
            "详细侧栏折叠偏好使用独立设备级存储",
        ),
        GUI_SKILL: (
            "固定 React/Mantine/Tabler/Router/Query/Jotai/i18n 技术栈",
            "普通 `async fn` Tauri 命令",
            "`get_app_metadata` 命令",
            "测量确认的 CPU 密集工作",
            "macosSigningSelection = disabled",
            "macosSigningSource = not-requested",
            "签名、公证与 stapling 必须作为一个不可降级阶段完成",
            "$desktop-build-tauri-release",
            "不得要求另选目标目录",
            "<project-id>_gui",
            "@tabler/icons-react",
            "$desktop-test-gui-initialization-e2e",
            "硬规则例外",
            "references/react-frontend-baseline.md",
            "references/mantine-ui-guidelines.md",
            "check-typescript-chinese-comments.cjs",
            "$desktop-prepare-gui-app-identity",
            "docs/GUI_APP_PROFILE.md",
            "唯一 `gui-initialization-config` 代码块",
            "`system_tray`、`system_notification`、`autostart`、`about_page`、`sponsor_page`、`single_instance`、`deep_link`、`global_shortcut`",
            "`sidebar_mode` 为 `compact`/`detailed`",
            "不得有 `pending`",
            "侧栏未选择时写入 `detailed` 的归一化只由初始化器完成",
            "$desktop-prepare-gui-support-surfaces",
            "$desktop-add-gui-system-locale",
            "$desktop-add-gui-updater",
            "$desktop-add-gui-window-state",
            "$desktop-add-gui-dialog",
            "$desktop-add-gui-system-tray",
            "$desktop-add-gui-single-instance",
            "$desktop-add-gui-deep-link",
            "$desktop-add-gui-global-shortcut",
            "所有 GUI 无条件调用 `$desktop-add-gui-system-locale`、`$desktop-add-gui-updater`、`$desktop-add-gui-window-state` 与 `$desktop-add-gui-dialog`",
            "再按 profile 分派 `$desktop-add-gui-system-tray`、`$desktop-add-gui-system-notifications`、`$desktop-add-gui-autostart`、`$desktop-add-gui-single-instance`、`$desktop-add-gui-deep-link` 与 `$desktop-add-gui-global-shortcut`",
            "关于/赞助只在启用时建立路由、入口和资源",
            "compact 必须实现 `tauri-gui-sidebar-compact-80-v1`",
            "detailed 必须实现 `tauri-gui-sidebar-detailed-v1`",
            "底部顺序为已选赞助、设置、已选关于",
            "侧栏按 `sidebar_mode` 选择",
            "APP_SIDEBAR_COLLAPSED_STORAGE_KEY",
            "折叠时只显示图标与 Tooltip",
            "页面会话 Jotai 状态仍只在进程内",
            "设置页固定区始终只渲染当前应用名/带一个小写 `v` 的版本",
            "只有 `about_page: enabled` 时建立关于页",
            "所有 GUI 都把品牌包的 `tauri/tauri.release.conf.json` 逐字节复制",
            "系统通知/开机自启只在启用时增加设置 Switch",
            "全局快捷键启用时还必须有唯一 `gui-global-shortcut-contract`",
            "中性初始化的 `actions` 必须为空；禁用时该块缺席",
            "global-shortcut 只按唯一 contract 注册非空 binding",
            "空 contract 零注册",
            "全局快捷键空 contract 不增加占位",
            "`user-configurable` 才增加录制、取消和清空",
            "不得以 WebView 状态作为绑定权威",
            "中性全局快捷键验证空 contract 零注册与 owned 清理",
            "中央 plugin 顺序固定为：启用时的 single-instance 首位、启用时的 deep-link 次位、固定 os、固定 updater、固定 window-state、固定 dialog、启用时的 notification、autostart、global-shortcut",
            "dialog 通过 `tauri_plugin_dialog::init()` 注册，不加入自有 `invoke_handler`",
            "主窗口 capability 只为固定 dialog 基线精确加入 `dialog:default`",
            "托盘通过独立 Skill 从 `.setup(...)`/`.on_window_event(...)` 接线",
            "测试必须锁定九项配置、唯一 profile 块、深链/单实例交叉关系、三项 Rust-only 固定基线、dialog 固定 WebView 基线与未选能力缺席",
            "$desktop-add-gui-system-notifications",
            "$desktop-add-gui-autostart",
            "初始化检查始终验证 locale/updater/window-state/dialog；条件验证托盘、通知、自启、单实例、深链接和全局快捷键",
            "详细模式默认展开/折叠持久化/Tooltip",
            "中性初始化随后固定调用 `$desktop-test-gui-initialization-e2e`",
            "未选托盘改验关闭最后窗口退出",
            "需要打包才能证明的 macOS 深链明确标为 `Not verified`",
            "React 事件、Tauri command 和平台回调不得承载业务规则",
            "未选项不得接线",
            "`candidate-1` → `candidate-2` → `candidate-3`",
            "选择前没有格式/尺寸/色彩/像素/摘要验证或标准化",
            "只为所选项记录后置验证/标准化",
        ),
        GUI_LOCALE_SKILL: (
            "`get_system_locale` 与 `set_interface_language` 两个窄 Tauri command",
            "GUI 固定的 `get_app_metadata`",
            "唯一合并的 `invoke_handler`",
        ),
        GUI_UPDATER_SKILL: (
            '`plugins.updater = { endpoints: [], pubkey: "" }`',
            "配置缺席会在当前插件版本被反序列化为 `null`",
            "不提供 endpoint、签名事实或出站能力",
        ),
        GUI_BASELINE: (
            "基于 Tokio 的单例异步运行时",
            "普通 `async fn`",
            "且不探测身份、证书、公证凭据或 profile",
            "使用 `--no-sign`",
            "完成签名、公证与 ticket stapling",
            "$desktop-build-tauri-release",
            "cargo-xwin + NSIS",
            "Windows runtime 保持为 `Unverified`",
            "Tauri 2",
            "React + TypeScript",
            "Mantine UI",
            "@tabler/icons-react",
            "$desktop-test-gui-initialization-e2e",
            "TanStack Router",
            "TanStack Query",
            "Jotai",
            "Tauri 2 和固定 React 前端技术栈是硬规则",
            "本次选择形成的最终候选字节",
            "`.DS_Store`",
            "GUI 初始化在接口选择后必须进行专门问询",
            "`system_tray`、`system_notification`、`autostart`、`about_page`、`sponsor_page`、`single_instance`、`deep_link`、`global_shortcut`",
            "`sidebar_mode` 的 `compact|detailed`",
            "八项条件能力不得缺失、推断或残留 `pending`",
            "未选择侧栏模式时必须写入 `sidebar_mode = detailed`",
            "显式非法值不得按未选择处理",
            "最终九项配置不得缺失或残留 `pending`",
            "$desktop-add-gui-system-notifications",
            "$desktop-add-gui-autostart",
            "tauri-plugin-single-instance",
            "首个 plugin 注册",
            "仅当 `system_tray = enabled` 时",
            "Tauri `tauri` 依赖启用 `tray-icon` feature",
            "src-tauri/icons/32x32.png",
            "`.setup(...)` 实际调用",
            "`.menu(&menu)`",
            "`default_window_icon()` 当作必需值",
            "成功 `.build(app)`",
            "主窗口 `CloseRequested` 由 `.on_window_event(...)` 注册",
            "只有 `quit` 显式结束应用",
            "组装仅含稳定 ID `show_window`/`quit` 的 `Menu`",
            "verify-gui-lifecycle-contract.mjs",
            "single_instance_plugin_is_registered_first",
            "second_launch_restores_existing_main_window",
            "tray_show_restores_and_focuses_main_window",
            "close_request_hides_without_exit",
            "tray_quit_exits_application",
            "tray_labels_resolve_for_supported_locales",
            "tray_labels_fall_back_to_english",
            "language_change_updates_tray_menu_labels",
            "选择禁用时不得启用 feature、安装托盘、保留菜单资源、调用 `prevent_close()` 或隐藏窗口",
            "close_last_window_exits_application",
            "`{applicationName} v{version} {contactChannel}:{contactValue}`",
            "初始化固定建立 `/settings`",
            "`/about` 与 `/sponsor` 分别只在相应选择启用时建立",
            "compact 当前为 `80px`、`6px` 内容内边距、`36px` Logo、`22px` 图标",
            "detailed 为 `248px`/`76px`、`72px`/`44px`、统一 `22px` 图标",
            "底部按已选赞助、固定设置、已选关于的视觉顺序生成",
            "初始化设置页不提供隐私/统计控件",
            "签名验证不可关闭",
            "所选关于页包含固定 updater 基线的 `NotConfigured`/零出站检查、更新日志、作者、联系方式和三段免责声明",
            "禁用或未同意时请求数为零",
            "支付二维码是敏感静态媒体",
            "<project-id>_gui/src-tauri/dmg/background.png",
            "./dmg/background.png",
            "应用 `(180, 220)`",
            "`candidate-1`、`candidate-2`、`candidate-3`",
            "用户选择前禁止格式/尺寸/色彩/像素/摘要验证及任何标准化",
            "选择后只处理所选项",
            "主应用窗口把 1440×900 逻辑像素、最小 960×640、居中与 `preventOverflow: true` 作为首次启动和持久状态缺失/损坏/离屏的回退",
            "最小 960×640",
            'defaultColorScheme="auto"',
            "useComputedColorScheme",
            "light`/`dark`/`auto",
            "未选页面不得存在路由、入口或运行时资源",
            "活动选项卡、已应用查询/筛选、排序、分页页码/每页数量",
            "页面背景、surface、主/次文字、边框与强调色",
        ),
        GUI_SUPPORT_SKILL: (
            "九项初始化配置",
            "`compact` 精确实现 `tauri-gui-sidebar-compact-80-v1`",
            "`detailed` 精确实现 `tauri-gui-sidebar-detailed-v1`",
            "Mantine `Tooltip`",
            "APP_SIDEBAR_COLLAPSED_STORAGE_KEY",
            "@tabler/icons-react",
            "三态主题与应用级亮暗语义",
            "system-locale、updater、window-state 由各自固定 Skill 无条件接入",
            "全局快捷键界面只按 contract 的非空固定/可编辑动作生成，空 contract 无占位",
            "全局快捷键只对 contract 非空动作接入逐项真实状态",
            "固定策略只读，可编辑策略使用 Rust 权威 load/save/capture 命令",
            "空 contract 不传 prop 或复制翻译键",
            "底部导航为已选赞助、固定设置、已选关于",
            "`/about` 与 `/sponsor` 只在对应配置启用时建立",
            "作者、联系方式和免责声明",
            "docs/GUI_SUPPORT_SURFACES.md",
            "默认 fail-open",
            "禁止 detached task",
            "秘密只能由已批准的安全运行时来源提供",
            "只有产品明确启用统计能力后才增加统计同意界面",
            "仅在托盘启用时复制/加载托盘原生文案",
            "不得信任远端 `forcedUpdate` 布尔值",
            "HTTPS JSON `POST` body",
            "初始化不得创建 `docs/GUI_SUPPORT_SURFACES.md`",
            "13 个源图片",
            "只有 `sponsor_page: enabled` 时",
            "支付二维码是敏感静态品牌材料",
            "应用根 Jotai store",
            "成功空页",
        ),
        GUI_SUPPORT_REFERENCE: (
            "## 所有权矩阵",
            "`{applicationName} v{version} {contactChannel}:{contactValue}`",
            "底部按已选赞助、固定设置、已选关于的视觉顺序生成",
            "compact 为 `80px`、`6px` 内容内边距、`36px` 本地 Logo、`22px` 图标",
            "detailed 首次默认 `248px` 展开、`72px` Logo、`22px` 图标",
            "Mantine Tooltip",
            "设置页固定提供当前应用/版本、中英文和浅色/深色/跟随系统",
            "系统通知与开机自启只在对应配置启用时增加",
            "托盘 i18n：仅在选择系统托盘时",
            "浅色、深色、跟随系统",
            "关于页在手动检查更新旁提供",
            "页面工作状态使用共享 `pageSessionState.ts`",
            "新 store 从默认值开始",
            "每个远程能力单独记录",
            "生产地址默认 HTTPS",
            "禁用或未同意时请求计数为零",
            "13 个源文件",
        ),
        GUI_SUPPORT_PAGES_REFERENCE: (
            "## 资产包内容",
            "关于页、赞助页、系统托盘、系统通知、开机自启、单实例、深链接、全局快捷键和侧栏模式则严格消费 GUI 初始化专门问询写入 `docs/GUI_APP_PROFILE.md` 的九项选择",
            "AppThemeProviderTemplate.tsx",
            "compact `80px` 全宽居中竖排菜单，或 detailed 默认 `248px` 展开、可收起为 `76px`",
            "设置页始终保留应用/版本、语言与三态主题",
            "仅当 `system_tray = enabled` 时",
            "手动检查更新和稳定状态随关于页存在",
            "作者、联系人、三段免责声明",
            "固定价格是 19、199、1999 CNY",
            "当前品牌包没有视频文件",
        ),
        GUI_SUPPORT_UPDATE_REFERENCE: (
            "## 更新状态机",
            "仅当初始化选择关于页时",
            "minimumSupportedVersion",
            "签名验证不可关闭",
            "普通功能导航和业务页面不挂载",
            "## 统计上报同意与固定最小事件",
            "禁止使用 GET/query",
            "撤回同意",
        ),
        MANTINE_GUIDELINES: (
            "docs/design_standards/README.md",
            "Tauri GUI 通用设计标准",
            "Tauri GUI 左侧栏标准",
            "标准匹配、优先级与偏离治理",
            "精简/详细模式的唯一尺寸、AppShell 接线和回归",
            "产品 `docs/GUI_APP_PROFILE.md` 中已批准的专属标准优先于 Harness 通用缺省",
            "不得自行发明密度",
        ),
        TYPESCRIPT_COMMENT_CHECKER: (
            "collectRequirements",
            "parseDiagnostics",
            "EXACT_EXCLUDED_FILES",
            "未发现受中文注释门禁管理的声明",
            "process.exitCode = main()",
        ),
        TYPESCRIPT_COMMENT_CHECKER_TESTS: (
            "accepts governed declarations without requiring locals or inline callbacks",
            "fails closed on parse diagnostics",
            "uses exact generated-file and directory exclusions",
            "fails closed on invalid UTF-8 and source symlinks",
        ),
        GUI_INITIALIZATION_E2E_SKILL: (
            "Computer Use",
            "verify-gui-lifecycle-contract.mjs",
            "pnpm tauri build --debug --no-bundle",
            "cargo metadata --format-version 1 --no-deps",
            "真实本机调试二进制",
            "新实例化目标在本 E2E 阶段不得提前 `git init`",
            "父级仓库不得视为目标自身的 Git 边界",
            "本 E2E 与裁剪成功后、紧邻唯一基线提交时建立",
            "有且只有一个 `gui-initialization-config` 围栏代码块",
            "八项能力均为 `enabled`/`disabled`",
            "侧栏模式为 `compact`/`detailed`",
            "本 E2E 不补写或推断缺失字段",
            "未选能力不是缺失证据",
            "检查器必须读取配置块并条件验证",
            "固定基线：所有 GUI 都验证 `$desktop-add-gui-system-locale`、`$desktop-add-gui-updater`、`$desktop-add-gui-window-state` 三项 Rust-only 基线",
            "同时验证 `$desktop-add-gui-dialog` 固定 WebView 基线",
            "主窗口的 `dialog:*` 权限精确为唯一 `dialog:default` 以覆盖 message/open/save",
            "不安装 `@tauri-apps/plugin-fs`、不授予 `fs:*` 或其他文件系统权限",
            '`plugins.updater = { endpoints: [], pubkey: "" }`',
            "`get_app_metadata`、`get_system_locale`、`set_interface_language` 三个窄 Tauri command 必须始终存在",
            "恰好进入一个无缺失、无重复、无额外项的合并 `invoke_handler`",
            "src-tauri/tauri.release.conf.json",
            "本次调试构建不传它",
            "异步 `load_release_notes`",
            "loading/error/retry",
            "`single_instance: enabled`",
            "single_instance_plugin_is_registered_first",
            "second_launch_restores_existing_main_window",
            "disabled 时拒绝依赖与注册",
            "`system_tray: enabled`",
            "`deep_link: enabled`",
            "`global_shortcut: enabled`",
            "唯一合法 `gui-global-shortcut-contract` JSON 块",
            "可空绑定/逐项真实状态",
            "Pressed-only typed dispatch",
            "注册与持久化原子回滚",
            "录制 token 及 owned 清理",
            "零默认 chord、零 OS 注册、零占位 UI",
            "固定动作只读显示需求 chord/逐项真实状态",
            "可编辑动作才提供录制、取消、清空和 Rust 权威 load/save/capture",
            "中性空 contract 必须确认启动/重启都没有 active binding",
            "不存在旧 Harness fallback chord",
            "本轮 owned chord 全部释放",
            "icons/32x32.png",
            "六个托盘生命周期/i18n 回归",
            "disabled 时拒绝 feature、托盘、`prevent_close` 与隐藏调用",
            "close_last_window_exits_application",
            "`system_notification: enabled`",
            "默认关闭的设置项",
            "`autostart: enabled`",
            "恢复执行前的 OS 登录项状态",
            "`compact` 为 `80px`",
            "`detailed` 首次无偏好时以 `248px` 展开",
            "`76px` 收起",
            "Tooltip 显示完整名称",
            "`/settings` 始终存在",
            "`/about`、`/sponsor` 及入口分别与配置一致",
            "仅当单实例启用时",
            "第二进程 15 秒内退出",
            "仅当托盘启用时",
            "真实非空图形",
            "中文“显示窗口/退出”和英文“Show Window/Quit”无重启刷新",
            "空白点击区域",
            "托盘未启用时",
            "close_last_window_exits_application",
            "终止并等待回收本 Skill 拥有的全部进程",
            "contract 动作数、初始非空 binding 数、实际注册/触发范围",
            "基线提交",
            "本 Skill 不创建 Verification",
        ),
        GUI_LIFECYCLE_CONTRACT_CHECKER: (
            "gui-initialization-config",
            "gui-global-shortcut-contract",
            "parseGlobalShortcutContract",
            "GLOBAL_SHORTCUT_ACTION_FIELDS",
            "GLOBAL_SHORTCUT_DISPATCH_FIELDS",
            "globalShortcutActions",
            '"system_tray"',
            '"system_notification"',
            '"autostart"',
            '"about_page"',
            '"sponsor_page"',
            '"single_instance"',
            '"deep_link"',
            '"global_shortcut"',
            '"sidebar_mode"',
            "初始化器应在用户未选择时写入 detailed",
            "validateFrontendInitializationContract",
            "GUI 固定基线缺少 /settings 路由",
            "未选择${page.label}时不得保留",
            "未选择赞助页时不得保留",
            "public/brand-support/sponsor",
            "22px 图标",
            "DEFAULT_DETAILED_SIDEBAR_COLLAPSED",
            "localStorage",
            "close_last_window_exits_application",
            "GUI 初始化配置 deep_link = enabled 必须同时满足 single_instance = enabled",
            "validatePluginDependencyContract",
            "validatePluginRuntimeContract",
            "validateRequiredPluginTests",
            "TrayIconBuilder",
            "MenuItemBuilder",
            "default_window_icon",
            "icons/32x32.png",
            "inflateSync",
            "全部像素透明，无法形成可见托盘图标",
            "绑定 .menu(...)",
            "成功 .build(app)",
            "托盘安装函数必须在同一实现中创建 Menu、绑定 .menu(...)、强制取得 default_window_icon、绑定 .icon(...) 并成功 .build(app)",
            "未选择系统托盘时必须在 CloseRequested 中显式调用 AppHandle::exit(0)",
            "MouseButton::Left",
            "MouseButtonState::Up",
            "WindowEvent::CloseRequested",
            "prevent_close",
            "show_window",
            "quit",
            "tray_show_restores_and_focuses_main_window",
            "close_request_hides_without_exit",
            "tray_quit_exits_application",
            "tray_labels_resolve_for_supported_locales",
            "tray_labels_fall_back_to_english",
            "language_change_updates_tray_menu_labels",
            "必须通过 rust-i18n t! 宏解析",
            "原始翻译键不得直接作为可见菜单文本",
            "workspace = true",
            "TextDecoder",
            "isSymbolicLink",
            "process.exitCode = main()",
            "validateReleaseNotesRuntimeContract",
        ),
        SKILLS_ROOT
        / "desktop-test-gui-initialization-e2e"
        / "scripts"
        / "gui-lifecycle-frontend-contract.mjs": (
            "validateFixedFrontendIpcContract",
            "validateDialogFrontendContract",
            '"@tauri-apps/plugin-dialog"',
            '"^2.7.3"',
            'permission === "dialog:default"',
            'permission.startsWith("fs:")',
            "capability.webviews",
            "dialog 权限只能授予 main 窗口/WebView",
            "AppMetadata",
            '"applicationName"',
            '"version"',
            '"contactChannel"',
            '"contactValue"',
            '"productDefinitionRequired"',
            '"title"',
            "decodeAppMetadata",
            "readString",
            "get_app_metadata",
            "get_system_locale",
            "set_interface_language",
            "GUI App/AppShell 运行时必须实际消费",
            "AppMetadata.title 更新 document.title",
        ),
        SKILLS_ROOT
        / "desktop-test-gui-initialization-e2e"
        / "scripts"
        / "verify-gui-lifecycle-contract.fixture.mjs": (
            'from "./gui-fixed-ipc-contract.fixture.mjs"',
            "FIXED_METADATA_LOCALE_RUNTIME_FIXTURE_SOURCE",
            "writeFixedFrontendIpcFixture",
            "${FIXED_METADATA_LOCALE_RUNTIME_FIXTURE_SOURCE}",
            "writeFixedFrontendIpcFixture(sourceRoot)",
        ),
        SKILLS_ROOT
        / "desktop-test-gui-initialization-e2e"
        / "scripts"
        / "gui-fixed-ipc-contract.fixture.mjs": (
            "struct AppMetadata",
            '#[serde(rename_all = "camelCase")]',
            "sample_core::scaffold_status().await",
            'env!("CARGO_PKG_VERSION")',
            "struct LocaleState",
            "app.state::<LocaleState>()",
            "state.set_saved_language(normalized.clone())",
            "rust_i18n::set_locale(&normalized)",
            "writeFixedFrontendIpcFixture",
            "decodeAppMetadata",
            'invoke<unknown>("get_app_metadata")',
            'invoke<unknown>("get_system_locale")',
            'invoke<unknown>("set_interface_language", { language })',
            "document.title = metadata.title",
            "setInterfaceLanguage(nextLanguage)",
        ),
        GUI_RELEASE_NOTES_CONTRACT_CHECKER: (
            "tauri.release.conf.json",
            '"../../release-notes.json": "release-notes.json"',
            "async fn load_release_notes",
            "BaseDirectory::Resource",
            "tokio::fs::symlink_metadata",
            "tokio::fs::read",
            "generate_handler! 必须注册 load_release_notes",
            'LOAD_RELEASE_NOTES_COMMAND = "load_release_notes"',
            "invoke<unknown>(command)",
            "releaseNotesLoader = loadBundledReleaseNotes",
            "parses_valid_release_notes_resource",
            "loads the packaged document through the narrow Tauri command",
            "未选择关于页时不得保留更新日志运行时实现",
            "@tauri-apps/plugin-fs",
        ),
        GUI_LIFECYCLE_CONTRACT_TESTS: (
            "dialog_default_permission_covers_all_dialog_types",
            "dialog_baseline_does_not_grant_filesystem_access",
            "rejects a main capability that appends extra dialog permissions",
            "rejects dialog permissions granted outside the main window",
            "accepts a complete single-instance and tray lifecycle contract",
            "accepts an explicit no-tray no-single-instance close-on-last-window contract",
            "rejects a GUI initialization without the dedicated capability profile",
            "rejects an unresolved GUI sidebar mode",
            "rejects a final profile that omits the materialized detailed sidebar default",
            'from "./gui-global-shortcut-contract.test-cases.mjs"',
            "registerGlobalShortcutContractTests();",
            "rejects an enabled about page without its route or runtime component",
            "rejects a GUI without the release-only resource mapping",
            "rejects an enabled about page without a registered release notes command",
            "rejects an enabled about page without the narrow frontend loader",
            "rejects a GUI without the fixed settings route and runtime component",
            "rejects a frontend AppMetadata decoder that trusts IPC fields",
            "rejects a frontend that does not invoke the fixed metadata command",
            "rejects App runtime that does not consume metadata title or locale commands",
            "rejects a disabled about page with a residual runtime route",
            "rejects a disabled about page with a residual release notes runtime",
            "rejects an enabled sponsor page with incomplete local media",
            "rejects disabled sponsor media left in the runtime bundle",
            "rejects a disabled sponsor page with residual route and component",
            "rejects frontend sidebar wiring that disagrees with the recorded mode",
            "rejects detailed sidebar without persistent collapsed-name disclosure",
            "rejects compact sidebar layout drift",
            "rejects close-hide lifecycle code when system tray was not selected",
            "rejects no-tray lifecycle without explicit close exit",
            "rejects a no-tray close-exit handler not wired into the builder",
            "rejects single-instance dependencies when the capability was not selected",
            "accepts table-form Cargo dependencies and MenuItem with_id",
            "rejects a GUI whose Tauri dependency lost tray-icon",
            "rejects a GUI missing the workspace single-instance dependency",
            "rejects a GUI that does not register the single-instance plugin first",
            "rejects a single-instance callback that does not restore the existing window",
            "rejects a neutral single-instance callback that consumes launch arguments",
            "rejects a GUI whose runtime no longer creates a tray",
            "rejects a tray implementation that is not wired into Tauri setup",
            "rejects a tray builder that does not attach its menu",
            "rejects optional default icon fallback that can create an iconless tray",
            "rejects a bundle config that omits the 32px tray icon source",
            "rejects an all-transparent 32px tray icon source",
            "rejects missing lifecycle regression coverage",
            "rejects missing single-instance regression coverage",
            "rejects missing native tray translations",
            "rejects tray labels that expose raw translation keys",
            "rejects tray i18n regression coverage without assertions",
        ),
        GUI_LIFECYCLE_PLUGIN_CONTRACT_CHECKER: (
            'from "./gui-global-shortcut-runtime-contract.mjs"',
            'from "./gui-fixed-ipc-runtime-contract.mjs"',
            "validateDialogRuntime",
            'tauri_plugin_dialog::init',
            "GLOBAL_SHORTCUT_TEST_NAMES",
            "USER_CONFIGURABLE_GLOBAL_SHORTCUT_TEST_NAMES",
            "allowedInitializationCommands",
            "invokeHandlerCommands",
            "validateFixedIpcRuntimeContract(sourceText, errors)",
            "validateUpdaterConfiguration",
            "合并的 generate_handler! 不得重复命令",
            "合并的 generate_handler! 不得接入未批准命令",
            "validateGlobalShortcutRuntimeContract",
            "validateGlobalShortcutTestCoverage",
            "validateGlobalShortcutRuntimeContract(sourceText, profile, errors)",
            "validateGlobalShortcutTestCoverage(testFunctions, profile, errors)",
        ),
        SKILLS_ROOT
        / "desktop-test-gui-initialization-e2e"
        / "scripts"
        / "gui-fixed-ipc-runtime-contract.mjs": (
            "FIXED_COMMANDS",
            "get_app_metadata",
            "get_system_locale",
            "set_interface_language",
            "GUI 固定基线命令必须是窄 Tauri command",
            "validateAppMetadataRuntime",
            "validateLocaleStateCommands",
            "validateFixedIpcRuntimeContract",
            "validateUpdaterConfiguration",
            "get_app_metadata 必须异步读取 core scaffold_status() 权威状态",
            'get_app_metadata 必须从 env!("CARGO_PKG_VERSION") 读取打包版本',
            "get_system_locale 必须让 LocaleState.saved_language() 进入系统 locale 解析链路",
            "set_interface_language 必须把归一化语言写回 LocaleState",
            "set_interface_language 必须同步调用 rust_i18n::set_locale",
            '中性 GUI 必须显式配置 plugins.updater = { endpoints: [], pubkey: "" }',
        ),
        GUI_GLOBAL_SHORTCUT_RUNTIME_CONTRACT_CHECKER: (
            "GLOBAL_SHORTCUT_TEST_NAMES",
            "USER_CONFIGURABLE_GLOBAL_SHORTCUT_TEST_NAMES",
            "global_shortcut_initial_bindings_match_contract",
            "global_shortcut_registers_only_configured_bindings",
            "global_shortcut_dispatches_pressed_events_to_declared_actions",
            "global_shortcut_reports_real_registration_state",
            "global_shortcut_unregisters_owned_bindings_on_shutdown",
            "global_shortcut_setup_failure_unregisters_owned_bindings",
            "shortcut_bindings_require_modifier_and_reject_equivalent_duplicates",
            "global_shortcut_replace_rolls_back_on_registration_failure",
            "global_shortcut_persistence_failure_restores_previous_bindings",
            "global_shortcut_recording_suppresses_dispatch_until_released",
            "parseMaterializedShortcutActions",
            "validateMaterializedShortcutActions",
            "validateEmptyShortcutRuntime",
            "sanitizeRustCode",
            "rustExecutableCode",
            "isShortcutRuntimeIdentifier",
            "invokeHandlerCommands",
            "allowedInitializationCommands",
            '"get_app_metadata"',
            '"get_system_locale"',
            '"set_interface_language"',
            "dispatchHelperName",
            "hasDispatchEffect",
            "visited = new Set()",
            "visited.has(candidate.name)",
            "typed static GLOBAL_SHORTCUT_ACTIONS",
            "GLOBAL_SHORTCUT_ACTIONS 与 profile 动作逐字段不一致",
            "typed dispatcher 必须拒绝未知动作",
            "typed dispatcher 分支必须与已声明 action id 精确一致",
            "typed dispatcher 未按 kind/target 物化动作",
            "全局快捷键不得通过通用 target helper 分派",
            "全局快捷键缺少 kind/target 专用 helper",
            "全局快捷键 kind/target 专用 helper 不得是通用 target 非空判断或 Ok/no-op",
            "Option<String>",
            "OwnedGlobalShortcutRegistry",
            "get_global_shortcut_statuses",
            "replace_owned_global_shortcuts",
            "rollback_staged_global_shortcuts",
            "unregister_owned_global_shortcuts",
            "dispatch_global_shortcut_action",
            "owned_action_id_for_shortcut",
            "ShortcutState::Pressed",
            "is_registered(chord)",
            "actions.is_empty()",
            "load_global_shortcut_bindings",
            "save_global_shortcut_bindings",
            "begin_global_shortcut_capture",
            "end_global_shortcut_capture",
            "不得调用 unregister_all()",
            "RunEvent::ExitRequested",
            "混合快捷键保存必须逐 ID 校验策略，并在 fixed chord 变化时立即 return Err",
            "混合快捷键保存必须在顶层先取得 fixed-safe validated updates，不得把校验放入死分支",
            "混合快捷键保存必须以 GLOBAL_SHORTCUT_ACTIONS 逐 ID 校验请求策略",
            "混合快捷键保存只能在 fixed 校验后用 validated updates 替换 owned bindings，不得随后全量 mutate 原请求",
            "全局快捷键固定回归缺少真实行为证据",
            "空 gui-global-shortcut-contract 不得由任何非测试函数取得 OS shortcut API",
            "空 gui-global-shortcut-contract 不得保留别名快捷键运行时",
            "空 gui-global-shortcut-contract 的插件注册必须精确为无 handler 的 Builder::new().build()",
            "空 gui-global-shortcut-contract 只能保留初始化所需的唯一 invoke_handler",
            "空 gui-global-shortcut-contract 的 invoke_handler 不得接入额外命令",
        ),
        GUI_GLOBAL_SHORTCUT_CONTRACT_FIXTURE: (
            "GLOBAL_SHORTCUT_ACTIONS_FIXTURE_BEGIN",
            "GLOBAL_SHORTCUT_RUNTIME_FIXTURE_BEGIN",
            "GLOBAL_SHORTCUT_TESTS_FIXTURE_BEGIN",
            "renderAction",
            "GlobalShortcutAction {",
            "id:",
            "binding_policy:",
            "default_chord:",
            "dispatch_kind:",
            "dispatch_target:",
            "e2e_safe:",
            "renderGlobalShortcutActionsFixtureSource",
            "get_app_metadata",
            "get_system_locale",
            "set_interface_language",
            "default_chord: Option<String>",
            "OwnedGlobalShortcutRegistry",
            "GlobalShortcutActionStatus",
            "dispatchHelperName",
            "renderDispatcher",
            "renderDispatchHelpers",
            "app.emit(",
            'map_err(|_| "shortcut-dispatch-failed")',
            '_ => Err("undeclared-shortcut-action")',
            "renderEmptyRuntime",
            "renderConfiguredRuntime",
            "renderGlobalShortcutRuntimeFixtureSource",
            "actions.length === 0",
            "renderGlobalShortcutRunFixtureSource",
            "ShortcutState::Pressed",
            "dispatch_global_shortcut_action",
            "replace_owned_global_shortcuts",
            "unregister_owned_global_shortcuts",
            "rewriteGlobalShortcutFixtureSource",
            "global_shortcut_initial_bindings_match_contract",
            "global_shortcut_registers_only_configured_bindings",
            "global_shortcut_dispatches_pressed_events_to_declared_actions",
            "global_shortcut_reports_real_registration_state",
            "global_shortcut_unregisters_owned_bindings_on_shutdown",
            "global_shortcut_setup_failure_unregisters_owned_bindings",
            "GLOBAL_SHORTCUT_TESTS_FIXTURE_SOURCE",
        ),
        GUI_GLOBAL_SHORTCUT_CONTRACT_TEST_CASES: (
            "registerGlobalShortcutContractTests",
            "rejects enabled global shortcut capability without its action contract block",
            "rejects a residual global shortcut action contract when the capability is disabled",
            "rejects Rust and frontend shortcut residuals when the capability is disabled",
            "accepts an empty global shortcut action contract without a default binding or UI",
            "ignores GlobalShortcutAction values constructed outside the static profile initializer",
            "parses fixed nullable and dotted-target global shortcut actions",
            "accepts a fixed shortcut action with exact Rust materialization and read-only OS status",
            "rejects a fixed global shortcut action without a chord",
            "rejects normalized duplicate default chords",
            "rejects malformed global shortcut action fields",
            "rejects URL script whitespace and unstable dispatch targets",
            "rejects duplicate action ids and oversized default chords",
            "rejects a global shortcut contract with the wrong schema version",
            "rejects an implicit legacy global shortcut default outside the action contract",
            "rejects variable-derived OS registration for an empty action contract",
            "rejects cross-function shortcut API access for an empty action contract",
            "rejects aliased shortcut commands added to the empty-contract invoke handler",
            "rejects semantic capture UI and hotkey translations for an empty action contract",
            "rejects shortcut save capture editor and translations for an empty contract",
            "rejects non-nullable desired shortcut binding state",
            "rejects any GLOBAL_SHORTCUT_ACTIONS field that differs from the profile",
            "rejects a wildcard no-op shortcut dispatcher",
            "rejects a generic target helper that returns Ok without dispatching",
            "rejects a target-specific dispatcher whose helper chain is a no-op",
            "rejects global shortcut dispatch without a Pressed-only gate",
            "rejects a constant-true global shortcut registration status",
            "rejects WebView storage Jotai and Query as the global shortcut binding authority",
            "rejects unregister_all because cleanup may only release owned shortcuts",
            "rejects replacement rollback that does not restore previous owned bindings",
            "rejects shortcut cleanup runtime for an empty action contract",
            "requires narrow Rust load save and capture commands for user-configurable shortcuts",
            "rejects a mixed-policy save command that can modify fixed actions",
            "rejects a dead fixed-action guard in mixed shortcut persistence",
            "rejects raw mixed shortcut updates mutated after fixed validation",
        ),
        GUI_LIFECYCLE_PLUGIN_CONTRACT_TESTS: (
            "dialog_dependencies_are_fixed",
            "dialog_plugin_is_registered_once_in_fixed_order",
            "rejects duplicate GUI initialization profile blocks",
            "rejects deep-link without single-instance",
            "rejects a missing system-locale dependency or plugin registration",
            "rejects browser-only locale wiring without a Rust locale call",
            "rejects treating tauri_plugin_os locale as a Result",
            "rejects system locale wiring without BCP-47 case normalization",
            "rejects updater code that can check before the NotConfigured gate",
            "rejects a missing explicit empty updater configuration",
            "rejects window-state setup that is not wired through the recoverable helper",
            "rejects window-state visibility restoration",
            "rejects deep-link schemes not derived from project identity",
            "rejects flattening the deep-link current URL result at the wrong layer",
            "rejects opening deep-link runtime registration APIs on the neutral restore path",
            "rejects global shortcut capability without a real registration",
            "rejects a global shortcut handler that fires on press and release",
            "rejects a constant global shortcut registration status",
            "rejects a missing single-instance registration",
            "rejects duplicate notification and autostart plugin registrations",
            "rejects disabled notification and autostart dependencies in generic member sections",
            "rejects enabled commands omitted from the merged invoke handler",
            "rejects an enabled about page without the updater check command in the merged handler",
            "keeps the fixed GUI command handler when every optional capability is disabled",
            "rejects missing fixed metadata and locale commands in the merged handler",
            "rejects duplicate commands in the merged initialization handler",
            "rejects a fixed GUI handler entry without the Tauri command attribute",
            "rejects a placeholder get_app_metadata return type",
            "rejects metadata detached from the core status or Cargo version",
            "rejects get_system_locale that bypasses saved LocaleState",
            "rejects set_interface_language without native state synchronization",
            "rejects an updater handler entry that is not a Tauri command",
            "rejects constant-true assertions in fixed plugin tests",
        ),
        E2E_SKILL: (
            "Computer Use",
            "完整真实最终产物",
            "最高风险失败路径",
            "GUI 更新日志",
            "release-notes.json",
            "最多五版",
            "about_page = disabled",
        ),
    }
