"""初始化主契约的必需片段。"""

from __future__ import annotations

from pathlib import Path

from .context import *  # noqa: F403


def primary_required_fragments(
    skill_file: Path,
) -> dict[Path, tuple[str, ...]]:
    """返回实例化、初始化和接口能力的主契约片段。"""

    return {
        INSTANTIATE_SKILL: (
            "完整目标项目目录路径",
            "目标目录是必填项",
            "ASCII `snake_case` 项目标识",
            "产品目的、核心输入/输出",
            "可以继续保持未确定",
            "解析后的目标目录基本名称",
            "通过符号链接解析到任何禁止位置的路径",
            "以免将 Harness 复制到其内部目标时发生递归",
            "唯一项目根目录",
            "git --version",
            "git init --initial-branch=main .",
            "git rev-parse --show-toplevel",
            "git symbolic-ref --short HEAD",
            "git rev-parse --verify HEAD",
            "git status --porcelain=v1 --untracked-files=all",
            "git remote",
            "独立的嵌套仓库边界",
            "docs/adr/",
            "docs/changelog/",
            "docs/product_spec/",
            "docs/work_plan/",
            "docs/verification/",
            "历史验证正文",
            "不得仅为实例化创建产品规格、工作计划、ADR、变更记录或 `docs/VERIFICATION.md`",
            "创建恰好一个本地基线提交",
            "$desktop-test-gui-initialization-e2e",
            "另进行一轮 GUI 配置询问",
            "系统托盘、关于页、赞助页、单实例",
            "`compact`/`detailed` 侧栏模式",
            "未选择侧栏模式时必须写入 `sidebar_mode = detailed`",
            "显式非法值必须重新确认",
            "五项无 `pending` 事实",
            "配置感知结构检查和 GUI 初始化 E2E",
            "单实例启用时才验证",
            "托盘启用时才验证",
            "托盘禁用时必须证明",
            "E2E 始终验证所选侧栏模式",
            "关于/赞助入口按选择存在或缺席",
            "未选能力不作为缺证据",
            "不得在经过选择性复制的目标目录中运行模板级 Harness 验证器",
            "LICENSE.zh-CN.md",
            "LICENSE.en.md",
            "逐字节复制两份许可证文件",
            "完整 `docs/design_standards/`",
            "$desktop-rename-project-identity",
            "整个受维护的目标树",
            "Applicable Project Name",
            "所有其他法律文本必须与复制后的源文件保持字节等价",
            "保留 `$desktop-rename-project-identity` 供未来已批准的产品改名使用",
            "$desktop-upgrade-harness",
            "推荐预设",
            "自定义",
            "superpowers: disabled",
            "parallel_worktree_subagents: enabled",
            "milestone_smoke: enabled",
            "milestone_e2e: disabled",
            "Harness 源字段值不是下游确认",
            "不得静默采用预设",
            "一次原子写入",
            "不得再次询问预设或各字段",
            "左侧 Task 描述模板",
            "独立 Worktree",
            "仅属于 Harness 的根目录 `Version.md`",
            "根 `Cargo.toml`",
            ".agents/skills/desktop-initialize-rust-project/assets/gui/macos-dmg-background.png",
            "$desktop-configure-git-commits",
            "安装并检查仓库本地提交模板",
            "不得修改全局 Git 配置",
        ),
        SKILLS_ROOT / "desktop-instantiate-project" / "agents" / "openai.yaml": (
            "在明确目标目录创建拥有独立 Git 根的干净下游项目",
            "$desktop-instantiate-project",
            "不继承 Harness 开发记忆",
        ),
        skill_file: (
            "$desktop-check-development-environment",
            "只有包含 `GUI` 的选择才增加阻断性的 Node.js 和 pnpm 门禁",
            "完整删除 `.agents/skills/desktop-instantiate-project/`、`.agents/skills/desktop-initialize-rust-project/` 和初始化专用的 `.agents/skills/desktop-test-gui-initialization-e2e/`",
            "## Skills 地图",
            "## 约束地图",
            "workspace = true",
            "只能从 `CLI`、`TUI`、`MCP` 和 `GUI` 中选择",
            "如果用户没有作出选择，则记录 `CLI`",
            "不得静默附加 CLI",
            "docs/AGENT_POLICY.md",
            "推荐预设",
            "自定义",
            "superpowers: disabled",
            "parallel_worktree_subagents: enabled",
            "milestone_smoke: enabled",
            "milestone_e2e: disabled",
            "Harness 源字段值不是下游确认",
            "不得静默采用推荐值",
            "一次原子写入",
            "只验证并复用，不再次询问",
            "统一描述模板",
            "左侧 Task 的独立 Worktree 交付契约",
            "$desktop-add-cli-adapter",
            "$desktop-add-tui-adapter",
            "$desktop-add-mcp-adapter",
            "$desktop-add-gui-adapter",
            "_cli",
            "_tui",
            "中性脚手架状态",
            "productDefinitionRequired=true",
            "业务 core 或适配器变化都直接实施",
            "不为中性初始化创建产品规格、计划、ADR、Changelog 或 Verification",
            "$desktop-define-product",
            "Ratatui + tui-realm + tui-realm-stdlib",
            "Vite + React + TypeScript + Mantine UI + `@tabler/icons-react` + TanStack Router 文件路由 + TanStack Query + Jotai",
            "@tabler/icons-react",
            "git --version",
            "git init --initial-branch=main .",
            "git rev-parse --show-toplevel",
            "git status --porcelain=v1 --untracked-files=all",
            "git remote",
            "chore: initialize project",
            "用户现有 Git 身份",
            "不得伪造身份",
            "docs/adr/",
            "docs/changelog/",
            "docs/product_spec/",
            "docs/work_plan/",
            "docs/verification/",
            "`docs/verification/` 仍然不存在",
            "`docs/harness_engineering/`",
            "只运行初始化本身必需的非空测试",
            "当前项目根目录必须同时是唯一的下游根目录及其独立 Git 顶层目录",
            "项目根目录 `.gitignore`",
            "根锚定的 `/release/`",
            "Tokio current-thread 异步入口",
            "Tauri 由 Tokio 支撑的异步运行时",
            "Tokio、Axum + Tower/Tower HTTP、Clap、SeaORM、config-rs、tracing + tracing-subscriber + tracing-appender、anyhow、thiserror、serde、jiff",
            "OpenTelemetry",
            "不得为中性状态预装未使用的 HTTP、ORM、配置、错误或可观测性依赖",
            "LICENSE.zh-CN.md",
            "LICENSE.en.md",
            "保留继承的两份非开源企业专有商业许可证文件",
            "$desktop-rename-project-identity",
            "$desktop-run-parallel-worktrees",
            "$desktop-upgrade-harness",
            "$desktop-configure-git-commits",
            "configure_git_commit.py install --project-root .",
            "configure_git_commit.py check --project-root .",
            "git config --local",
            "只有用户明确批准后才可使用 `--replace`",
            "提交模板本地配置与检查结果",
            "选择 GUI 时同时完整保留 `$desktop-prepare-gui-support-surfaces`（包括 `assets/brand-support/**`）",
            "不得预创建 `docs/GUI_SUPPORT_SURFACES.md`",
            "单独进行一轮 GUI 初始化配置询问",
            "`system_tray`、`about_page`、`sponsor_page`、`single_instance`、`sidebar_mode`",
            "`gui-initialization-config`",
            "未选择侧栏模式必须写入 `sidebar_mode = detailed`",
            "显式非法值不得按未选择处理",
            "最终五项不得缺失或残留 `pending`",
            "仅当 `system_tray: enabled` 时启用 `tray-icon` feature",
            "<project-id>_gui/src-tauri/icons/32x32.png",
            "选择系统托盘时，该文件同时是托盘可见图标来源",
            "托盘安装必须从 `.setup(...)` 可达并绑定必需图标/Menu/build",
            "`CloseRequested` 从 `.on_window_event(...)` 可达",
            "菜单稳定 ID 恰好为 `show_window`/`quit`",
            '`rust_i18n::t!("tray.show_window")`',
            '`rust_i18n::t!("tray.quit")`',
            "`system_tray: disabled` 时不得启用 feature、创建托盘、调用 `prevent_close()` 或隐藏窗口",
            "close_last_window_exits_application",
            "必须从 `.on_window_event(...)` 接线，在主窗口 `CloseRequested` 中显式调用 `AppHandle::exit(0)`",
            "仅当 `single_instance: enabled` 时声明官方 `tauri-plugin-single-instance`",
            "未选择时不得声明或注册该插件",
            "`{applicationName} v{version} {contactChannel}:{contactValue}`",
            "关于页、赞助页及其路由/菜单/运行时资源只在对应能力为 `enabled` 时建立",
            "已选赞助、设置、已选关于",
            "关于页启用时保留本地更新日志与 `NotConfigured` 零出站",
            "赞助页启用时才复制完整 `media/sponsor/*`",
            "`tauri-gui-sidebar-compact-80-v1`",
            "`80px` 栏宽",
            "`6px` 内容内边距",
            "`36px` Logo",
            "`22px`/`1.75` 图标",
            "`11px`/`1.25` 全宽居中名称",
            "`56px` 菜单项",
            "禁止固定 `em/ch` 名称盒和折叠按钮",
            "`detailed` 精确命中 `tauri-gui-sidebar-detailed-v1`",
            "自身按钮收起为 `76px`/`44px` Logo",
            "Mantine `Tooltip`",
            "独立设备偏好",
            "不含隐私/统计",
            "浅色/深色/跟随系统",
            "页面工作状态继续由应用根 Jotai store 仅在当前进程跨路由保留",
            "三态主题和亮暗语义主题始终存在",
            "正好 3 个 1024×1024 PNG 候选",
            "<project-id>_gui/src-tauri/icons/app-icon-master.png",
            "<project-id>_gui/public/app-identity/logo.png",
            "$desktop-test-gui-initialization-e2e",
            "tauri-plugin-single-instance",
            "结构检查器先读取配置块并条件验证",
            "单实例启用时检查依赖/首插件/回调/两个回归",
            "托盘启用时检查 feature、图标、运行时接线、六个回归和双语资源",
            "托盘禁用时检查 feature/隐藏实现缺席",
            "构建并启动真实本机调试二进制",
            "始终验证所选侧栏模式、设置页和所有实际渲染菜单页面",
            "仅对已选单实例执行双启动唯一性场景",
            "仅对已选托盘执行关闭隐藏/恢复/退出与运行时 i18n 场景",
            "未选托盘时必须真实关闭最后一个窗口并观察进程退出",
            "关于/赞助菜单与页面必须分别按选择存在或缺席",
            "未选能力不得被当作缺证据",
            "仍包含旧 Harness 身份",
            ".agents/skills/desktop-initialize-rust-project/assets/gui/macos-dmg-background.png",
            "<project-id>_gui/src-tauri/dmg/background.png",
            "bundle.macOS.dmg.background",
            "./dmg/background.png",
            "660×400",
        ),
        ENVIRONMENT_SKILL / "SKILL.md": (
            "只接受两类触发",
            "不得仅因首次修改代码、新任务、新会话、显式构建",
            "门禁成功后只重试原失败命令一次",
            "Rust 始终是常规阻断门禁",
            "仅当已记录的接口选择包含 `GUI` 时，Node.js 和 pnpm 才是常规阻断门禁",
            "必须把两者都报告为 `not-required`",
            "由中性 `$desktop-initialize-rust-project` 调用时",
            "不得为普通开发预建 Verification",
            "本 Skill 及其脚本在下游初始化后必须保留",
            "scripts/macos-tauri-xwin-gates.sh --install-missing",
            "不自动安装 Homebrew",
            "只证明交叉工具可用，不证明 Windows 运行时",
        ),
        GUI_IDENTITY_SKILL: (
            "应用展示名称",
            "主窗口标题",
            "DMG 背景",
            "应用/Applications 落点",
            "自动生成",
            "确定性备选方案",
            "用户上传",
            "1024×1024",
            "初始化 Logo 模式",
            "正好 3 个",
            "必须等待用户明确选择其中一个",
            "<project-id>_gui/src-tauri/icons/app-icon-master.png",
            "<project-id>_gui/public/app-identity/logo.png",
            "icons/32x32.png",
            "可见的 32×32 8-bit RGBA 非交错普通文件",
            "由 `bundle.icon` 引用",
            "`default_window_icon()` 当作必需值",
            "docs/GUI_APP_PROFILE.md",
            "唯一 `gui-initialization-config` 围栏代码块",
            "`system_tray`、`about_page`、`sponsor_page`、`single_instance`、`sidebar_mode`",
            "<project-id>_gui/src-tauri/dmg/background.png",
            "SHA-256",
        ),
        SKILLS_ROOT / "desktop-define-product" / "SKILL.md": (
            "中性 scaffold 约束",
            "$desktop-plan-change",
            "$desktop-implement-change",
        ),
        SKILLS_ROOT / "desktop-implement-change" / "SKILL.md": (
            "Git 根/分支和工作区",
            "保护用户已有修改",
            "$desktop-check-development-environment",
            "只运行第 6 步的测试",
            "不得自动追加格式化、lint、静态、集成/契约、全仓测试、构建",
        ),
        SKILLS_ROOT / "desktop-verify-delivery" / "SKILL.md": (
            "源码提交",
            "版本/构建标识",
            "Unverified",
            "项目全部非空单元测试",
        ),
        SKILLS_ROOT / "desktop-build-rust-release" / "SKILL.md": (
            "下游项目根同时是其独立 Git 顶层目录",
            "`HEAD` 解析到真实源码提交",
        ),
        SKILLS_ROOT / "desktop-prepare-release" / "SKILL.md": (
            "独立 Git 顶层目录",
            "尚未生成的 `HEAD`",
        ),
        MCP_SKILL: (
            "不得要求另选目标目录",
            "<project-id>_mcp",
            "Tokio current-thread 异步入口",
            "测量确认的 CPU 密集工作",
            "不得用同步 I/O、休眠、进程等待或 CPU 密集工具工作阻塞 Tokio stdio 运行时",
        ),
        CLI_SKILL: (
            "CLI 是可选项",
            "<project-id>_cli",
            "docs/CLI_CONTRACT.md",
            "Tokio current-thread 异步入口",
            "测量确认的 CPU 密集工作",
            "不得用同步 I/O、休眠、进程等待或 CPU 密集循环阻塞异步运行时",
        ),
        TUI_SKILL: (
            "<project-id>_tui",
            "不要求 CLI",
            "Ratatui",
            "tui-realm",
            "tui-realm-stdlib",
            "硬规则例外",
            "references/tui-baseline.md",
            "Tokio current-thread 异步入口",
            "测量确认的 CPU 密集工作",
            "不得用同步 I/O、休眠、进程等待或 CPU 密集的渲染/数据工作阻塞 Tokio 运行时",
        ),
        TUI_BASELINE: (
            "Ratatui",
            "tui-realm",
            "tui-realm-stdlib",
            "最低兼容稳定组合",
            "最低直接版本解析",
            "硬规则例外 ADR",
            "Tokio current-thread 异步入口",
            "测量确认的 CPU 密集工作",
        ),
        REACT_BASELINE: (
            "Vite",
            "React 和 TypeScript",
            "Mantine UI",
            "@tabler/icons-react",
            "TanStack Router",
            "TanStack Query",
            "Jotai",
            "不得把 Query 结果镜像到 Jotai",
            "URL/search 只用于产品明确批准的可分享导航事实",
            "最低兼容稳定范围",
            "resolutionMode: lowest-direct",
            "TypeScript Compiler AST",
            "Vitest",
            "Testing Library",
            "$desktop-prepare-gui-support-surfaces",
            "前端不得持有远程服务或发布者长期秘密",
            "运行时只复制所选页面需要的资源",
            "初始化固定建立 `/settings`",
            "`/about` 与 `/sponsor` 按 profile 选择存在",
            "compact 为 `80px` 全宽居中竖排菜单且不折叠",
            "全宽居中竖排菜单且不折叠",
            "按 detailed 标准锁定默认 `248px` 展开、`72px` Logo",
            "自身折叠按钮、身份父级无动作、`76px`/`44px` 收起",
            "图标-only + Tooltip 与偏好持久化",
            "底部按已选赞助、固定设置、已选关于生成",
            "真实更新、强更或统计上报",
            'defaultColorScheme="auto"',
            "light`/`dark`/`auto",
            "未选页面不得有路由、导航入口或运行时资源",
            "pageSessionState.ts",
            "route unmount/remount",
            "详细侧栏折叠偏好使用独立设备级存储",
        ),
        GUI_SKILL: (
            "固定 React/Mantine/Tabler/Router/Query/Jotai/i18n 技术栈",
            "普通 `async fn` Tauri 命令",
            "测量确认的 CPU 密集工作",
            "缺少完整签名公证条件且渠道允许时",
            "显式生成 `unsigned` 候选",
            "签名、公证与 stapling 必须作为一个阶段完成",
            "$desktop-build-tauri-release",
            "不得要求另选目标目录",
            "<project-id>_gui",
            "@tabler/icons-react",
            "$desktop-test-gui-initialization-e2e",
            "硬规则例外",
            "references/react-frontend-baseline.md",
            "references/mantine-ui-guidelines.md",
            "check-typescript-chinese-comments.cjs",
            "$desktop-prepare-gui-app-identity",
            "docs/GUI_APP_PROFILE.md",
            "唯一 `gui-initialization-config` 代码块",
            "`system_tray`、`about_page`、`sponsor_page`、`single_instance`",
            "`sidebar_mode` 为 `compact`/`detailed`",
            "不得有 `pending`",
            "侧栏未选择时写入 `detailed` 的归一化只由初始化器完成",
            "$desktop-prepare-gui-support-surfaces",
            "关于/赞助只在启用时建立路由、入口和资源",
            "compact 必须实现 `tauri-gui-sidebar-compact-80-v1`",
            "detailed 必须实现 `tauri-gui-sidebar-detailed-v1`",
            "底部顺序为已选赞助、设置、已选关于",
            "侧栏按 `sidebar_mode` 选择",
            "APP_SIDEBAR_COLLAPSED_STORAGE_KEY",
            "折叠时只显示图标与 Tooltip",
            "页面会话 Jotai 状态仍只在进程内",
            "设置页始终只渲染当前应用名/带一个小写 `v` 的版本",
            "只有 `about_page: enabled` 时建立关于页",
            "只有 `sponsor_page: enabled` 时建立赞助页并复制 sponsor 媒体",
            "只有 `system_tray: enabled` 才给 Tauri 启用 `tray-icon` feature",
            "只有 `single_instance: enabled` 才声明官方 `tauri-plugin-single-instance`",
            "仅当单实例启用时，把官方插件作为首个 plugin 注册",
            "仅当托盘启用时，启用 feature",
            "从 `.setup(...)` 接线并注册 `CloseRequested` 的 `prevent_close()`+隐藏",
            "必须通过 `.on_window_event(...)` 接线，在主窗口 `CloseRequested` 中显式调用 `AppHandle::exit(0)`",
            "测试必须锁定五项配置与未选能力缺席",
            "托盘禁用时运行 `close_last_window_exits_application`",
            "详细模式默认展开/折叠持久化/Tooltip",
            "支持页条件入口",
            "E2E 始终验证所选侧栏模式、设置页、实际菜单",
            "不得默认加入自动启动",
            "React 事件、Tauri command 和平台回调不得承载业务规则",
            "未选项不得接线",
        ),
        GUI_BASELINE: (
            "基于 Tokio 的单例异步运行时",
            "普通 `async fn`",
            "缺少签名身份",
            "使用 `--no-sign` 并记录 unsigned",
            "完成公证与 ticket stapling",
            "$desktop-build-tauri-release",
            "cargo-xwin + NSIS",
            "Windows runtime 保持为 `Unverified`",
            "Tauri 2",
            "React + TypeScript",
            "Mantine UI",
            "@tabler/icons-react",
            "$desktop-test-gui-initialization-e2e",
            "TanStack Router",
            "TanStack Query",
            "Jotai",
            "Tauri 2 和固定 React 前端技术栈是硬规则",
            "最终签名、公证与 stapling 字节",
            "`.DS_Store`",
            "GUI 初始化在接口选择后必须进行专门问询",
            "`system_tray`、`about_page`、`sponsor_page`、`single_instance`",
            "`sidebar_mode` 的 `compact|detailed`",
            "四项能力不得缺失、推断或残留 `pending`",
            "未选择侧栏模式时必须写入 `sidebar_mode = detailed`",
            "显式非法值不得按未选择处理",
            "最终五项配置不得缺失或残留 `pending`",
            "tauri-plugin-single-instance",
            "首个 plugin 注册",
            "仅当 `system_tray = enabled` 时",
            "Tauri `tauri` 依赖启用 `tray-icon` feature",
            "src-tauri/icons/32x32.png",
            "`.setup(...)` 实际调用",
            "`.menu(&menu)`",
            "`default_window_icon()` 当作必需值",
            "成功 `.build(app)`",
            "主窗口 `CloseRequested` 由 `.on_window_event(...)` 注册",
            "只有 `quit` 显式结束应用",
            "组装仅含稳定 ID `show_window`/`quit` 的 `Menu`",
            "verify-gui-lifecycle-contract.mjs",
            "single_instance_plugin_is_registered_first",
            "second_launch_restores_existing_main_window",
            "tray_show_restores_and_focuses_main_window",
            "close_request_hides_without_exit",
            "tray_quit_exits_application",
            "tray_labels_resolve_for_supported_locales",
            "tray_labels_fall_back_to_english",
            "language_change_updates_tray_menu_labels",
            "选择禁用时不得启用 feature、安装托盘、保留菜单资源、调用 `prevent_close()` 或隐藏窗口",
            "close_last_window_exits_application",
            "`{applicationName} v{version} {contactChannel}:{contactValue}`",
            "初始化固定建立 `/settings`",
            "`/about` 与 `/sponsor` 分别只在相应选择启用时建立",
            "compact 当前为 `80px`、`6px` 内容内边距、`36px` Logo、`22px` 图标",
            "detailed 为 `248px`/`76px`、`72px`/`44px`、统一 `22px` 图标",
            "底部按已选赞助、固定设置、已选关于的视觉顺序生成",
            "初始化设置页不提供隐私/统计控件",
            "签名验证不可关闭",
            "所选关于页包含检查更新、更新日志、作者、联系方式和三段免责声明",
            "禁用或未同意时请求数为零",
            "支付二维码是敏感静态媒体",
            "<project-id>_gui/src-tauri/dmg/background.png",
            "./dmg/background.png",
            "应用 `(180, 220)`",
            "正好 3 个 1024×1024 Logo 候选",
            "主应用窗口固定以逻辑像素初始化为 1440×900",
            "最小 960×640",
            'defaultColorScheme="auto"',
            "useComputedColorScheme",
            "light`/`dark`/`auto",
            "未选页面不得存在路由、入口或运行时资源",
            "活动选项卡、已应用查询/筛选、排序、分页页码/每页数量",
            "页面背景、surface、主/次文字、边框与强调色",
        ),
        GUI_SUPPORT_SKILL: (
            "五项初始化配置",
            "`compact` 精确实现 `tauri-gui-sidebar-compact-80-v1`",
            "`detailed` 精确实现 `tauri-gui-sidebar-detailed-v1`",
            "Mantine `Tooltip`",
            "APP_SIDEBAR_COLLAPSED_STORAGE_KEY",
            "@tabler/icons-react",
            "三态主题与应用级亮暗语义",
            "底部由 `buildSupportNavigationItems` 组装为已选赞助、固定设置、已选关于",
            "`/about` 与 `/sponsor` 只在对应配置启用时建立",
            "作者、联系方式和免责声明",
            "docs/GUI_SUPPORT_SURFACES.md",
            "默认 fail-open",
            "禁止 detached task",
            "秘密只能由已批准的安全运行时来源提供",
            "只有产品明确启用统计能力后才增加统计同意界面",
            "仅在托盘启用时复制/加载托盘原生文案",
            "不得信任远端 `forcedUpdate` 布尔值",
            "HTTPS JSON `POST` body",
            "初始化不得创建 `docs/GUI_SUPPORT_SURFACES.md`",
            "13 个源图片",
            "只有 `sponsor_page: enabled` 时",
            "支付二维码是敏感静态品牌材料",
            "应用根 Jotai store",
            "成功空页",
        ),
        GUI_SUPPORT_REFERENCE: (
            "## 所有权矩阵",
            "`{applicationName} v{version} {contactChannel}:{contactValue}`",
            "底部按已选赞助、固定设置、已选关于的视觉顺序生成",
            "compact 为 `80px`、`6px` 内容内边距、`36px` 本地 Logo、`22px` 图标",
            "detailed 首次默认 `248px` 展开、`72px` Logo、`22px` 图标",
            "Mantine Tooltip",
            "设置页只提供当前应用/版本、中英文和浅色/深色/跟随系统",
            "托盘 i18n：仅在选择系统托盘时",
            "浅色、深色、跟随系统",
            "关于页在手动检查更新旁提供",
            "页面工作状态使用共享 `pageSessionState.ts`",
            "新 store 从默认值开始",
            "每个远程能力单独记录",
            "生产地址默认 HTTPS",
            "禁用或未同意时请求计数为零",
            "13 个源文件",
        ),
        GUI_SUPPORT_PAGES_REFERENCE: (
            "## 资产包内容",
            "关于页、赞助页、系统托盘、单实例和侧栏模式则严格消费 GUI 初始化专门问询",
            "AppThemeProviderTemplate.tsx",
            "compact `80px` 全宽居中竖排菜单，或 detailed 默认 `248px` 展开、可收起为 `76px`",
            "设置页只保留应用/版本、语言与三态主题",
            "仅当 `system_tray = enabled` 时",
            "手动检查更新和稳定状态随关于页存在",
            "作者、联系人、三段免责声明",
            "固定价格是 19、199、1999 CNY",
            "当前品牌包没有视频文件",
        ),
        GUI_SUPPORT_UPDATE_REFERENCE: (
            "## 更新状态机",
            "仅当初始化选择关于页时",
            "minimumSupportedVersion",
            "签名验证不可关闭",
            "普通功能导航和业务页面不挂载",
            "## 统计上报同意与固定最小事件",
            "禁止使用 GET/query",
            "撤回同意",
        ),
        MANTINE_GUIDELINES: (
            "docs/design_standards/README.md",
            "Tauri GUI 通用设计标准",
            "Tauri GUI 左侧栏标准",
            "标准匹配、优先级与偏离治理",
            "精简/详细模式的唯一尺寸、AppShell 接线和回归",
            "产品 `docs/GUI_APP_PROFILE.md` 中已批准的专属标准优先于 Harness 通用缺省",
            "不得自行发明密度",
        ),
        TYPESCRIPT_COMMENT_CHECKER: (
            "collectRequirements",
            "parseDiagnostics",
            "EXACT_EXCLUDED_FILES",
            "未发现受中文注释门禁管理的声明",
            "process.exitCode = main()",
        ),
        TYPESCRIPT_COMMENT_CHECKER_TESTS: (
            "accepts governed declarations without requiring locals or inline callbacks",
            "fails closed on parse diagnostics",
            "uses exact generated-file and directory exclusions",
            "fails closed on invalid UTF-8 and source symlinks",
        ),
        GUI_INITIALIZATION_E2E_SKILL: (
            "Computer Use",
            "verify-gui-lifecycle-contract.mjs",
            "pnpm tauri build --debug --no-bundle",
            "cargo metadata --format-version 1 --no-deps",
            "真实本机调试二进制",
            "唯一 `gui-initialization-config` 围栏代码块",
            "四项能力均为 `enabled`/`disabled`",
            "侧栏模式为 `compact`/`detailed`",
            "本 E2E 不补写或推断缺失字段",
            "未选能力不是缺失证据",
            "检查器必须读取配置块并条件验证",
            "src-tauri/tauri.release.conf.json",
            "本次调试构建不传它",
            "异步 `load_release_notes`",
            "loading/error/retry",
            "`single_instance: enabled`",
            "single_instance_plugin_is_registered_first",
            "second_launch_restores_existing_main_window",
            "disabled 时拒绝依赖与注册",
            "`system_tray: enabled`",
            "icons/32x32.png",
            "六个托盘生命周期/i18n 回归",
            "disabled 时拒绝 feature、托盘、`prevent_close` 与隐藏调用",
            "close_last_window_exits_application",
            "`compact` 为 `80px`",
            "`detailed` 首次无偏好时以 `248px` 展开",
            "`76px` 收起",
            "Tooltip 显示完整名称",
            "`/settings` 始终存在",
            "`/about`、`/sponsor` 及入口分别与配置一致",
            "仅当单实例启用时",
            "第二进程 15 秒内退出",
            "仅当托盘启用时",
            "真实非空图形",
            "中文“显示窗口/退出”和英文“Show Window/Quit”无重启刷新",
            "空白点击区域",
            "托盘未启用时",
            "关闭最后一个窗口",
            "终止并等待回收本 Skill 拥有的全部进程",
            "基线提交",
            "本 Skill 不创建 Verification",
        ),
        GUI_LIFECYCLE_CONTRACT_CHECKER: (
            "gui-initialization-config",
            '"system_tray"',
            '"about_page"',
            '"sponsor_page"',
            '"single_instance"',
            '"sidebar_mode"',
            "初始化器应在用户未选择时写入 detailed",
            "validateFrontendInitializationContract",
            "GUI 固定基线缺少 /settings 路由",
            "未选择${page.label}时不得保留",
            "未选择赞助页时不得保留",
            "public/brand-support/sponsor",
            "22px 图标",
            "DEFAULT_DETAILED_SIDEBAR_COLLAPSED",
            "localStorage",
            "close_last_window_exits_application",
            "tauri_plugin_single_instance::init",
            "tauri-plugin-single-instance 必须作为首个 Tauri plugin 注册",
            "回调不得消费参数/工作目录",
            "restore_main_window",
            "TrayIconBuilder",
            "MenuItemBuilder",
            "default_window_icon",
            "icons/32x32.png",
            "inflateSync",
            "全部像素透明，无法形成可见托盘图标",
            "绑定 .menu(...)",
            "成功 .build(app)",
            "托盘安装函数必须由 Tauri Builder .setup(...) 实际调用",
            "主窗口关闭隐藏处理必须由 Tauri Builder .on_window_event(...) 实际注册",
            "MouseButton::Left",
            "MouseButtonState::Up",
            "WindowEvent::CloseRequested",
            "prevent_close",
            "show_window",
            "quit",
            "single_instance_plugin_is_registered_first",
            "second_launch_restores_existing_main_window",
            "tray_show_restores_and_focuses_main_window",
            "close_request_hides_without_exit",
            "tray_quit_exits_application",
            "tray_labels_resolve_for_supported_locales",
            "tray_labels_fall_back_to_english",
            "language_change_updates_tray_menu_labels",
            "必须通过 rust-i18n t! 宏解析",
            "原始翻译键不得直接作为可见菜单文本",
            "workspace = true",
            "TextDecoder",
            "isSymbolicLink",
            "process.exitCode = main()",
            "validateReleaseNotesRuntimeContract",
        ),
        GUI_RELEASE_NOTES_CONTRACT_CHECKER: (
            "tauri.release.conf.json",
            '"../../release-notes.json": "release-notes.json"',
            "async fn load_release_notes",
            "BaseDirectory::Resource",
            "tokio::fs::symlink_metadata",
            "tokio::fs::read",
            "generate_handler![load_release_notes]",
            'LOAD_RELEASE_NOTES_COMMAND = "load_release_notes"',
            "invoke<unknown>(command)",
            "releaseNotesLoader = loadBundledReleaseNotes",
            "parses_valid_release_notes_resource",
            "loads the packaged document through the narrow Tauri command",
            "未选择关于页时不得保留更新日志运行时实现",
            "@tauri-apps/plugin-fs",
        ),
        GUI_LIFECYCLE_CONTRACT_TESTS: (
            "accepts a complete single-instance and tray lifecycle contract",
            "accepts an explicit no-tray no-single-instance close-on-last-window contract",
            "rejects a GUI initialization without the dedicated capability profile",
            "rejects an unresolved GUI sidebar mode",
            "rejects a final profile that omits the materialized detailed sidebar default",
            "rejects an enabled about page without its route or runtime component",
            "rejects a GUI without the release-only resource mapping",
            "rejects an enabled about page without a registered release notes command",
            "rejects an enabled about page without the narrow frontend loader",
            "rejects a GUI without the fixed settings route and runtime component",
            "rejects a disabled about page with a residual runtime route",
            "rejects a disabled about page with a residual release notes runtime",
            "rejects an enabled sponsor page with incomplete local media",
            "rejects disabled sponsor media left in the runtime bundle",
            "rejects a disabled sponsor page with residual route and component",
            "rejects frontend sidebar wiring that disagrees with the recorded mode",
            "rejects detailed sidebar without persistent collapsed-name disclosure",
            "rejects compact sidebar layout drift",
            "rejects close-hide lifecycle code when system tray was not selected",
            "rejects no-tray lifecycle without explicit close exit",
            "rejects a no-tray close-exit handler not wired into the builder",
            "rejects single-instance dependencies when the capability was not selected",
            "accepts table-form Cargo dependencies and MenuItem with_id",
            "rejects a GUI whose Tauri dependency lost tray-icon",
            "rejects a GUI missing the workspace single-instance dependency",
            "rejects a GUI that does not register the single-instance plugin first",
            "rejects a single-instance callback that does not restore the existing window",
            "rejects a neutral single-instance callback that consumes launch arguments",
            "rejects a GUI whose runtime no longer creates a tray",
            "rejects a tray implementation that is not wired into Tauri setup",
            "rejects a tray builder that does not attach its menu",
            "rejects optional default icon fallback that can create an iconless tray",
            "rejects a bundle config that omits the 32px tray icon source",
            "rejects an all-transparent 32px tray icon source",
            "rejects missing lifecycle regression coverage",
            "rejects missing single-instance regression coverage",
            "rejects missing native tray translations",
            "rejects tray labels that expose raw translation keys",
            "rejects tray i18n regression coverage without assertions",
        ),
        E2E_SKILL: (
            "Computer Use",
            "完整真实最终产物",
            "最高风险失败路径",
            "GUI 更新日志",
            "release-notes.json",
            "最多五版",
            "about_page = disabled",
        ),
    }
