"""初始化仓库契约的必需片段。"""

from __future__ import annotations

from pathlib import Path

from .context import *  # noqa: F403


def repository_required_fragments(
    gate_file: Path,
    rust_baseline: Path,
) -> dict[Path, tuple[str, ...]]:
    """返回策略、工具链、身份和仓库文件的契约片段。"""

    return {
        AGENT_POLICY: (
            "superpowers:",
            "parallel_worktree_subagents:",
            "milestone_smoke:",
            "milestone_e2e:",
            "`superpowers:`",
            "任务路径与项目记忆触发彼此独立",
        ),
        gate_file: (
            "scripts/development-environment-gates.sh --install-missing",
            "scripts/development-environment-gates.ps1",
            "rustup --version",
            "node --version",
            "pnpm --version",
            "not-required",
            "https://static.rust-lang.org/rustup/dist",
            "https://nodejs.org/dist",
            "https://aka.ms/vs/17/release/vs_BuildTools.exe",
            "MSVC Build Tools",
            "scripts/macos-tauri-xwin-gates.sh --install-missing --target x86_64-pc-windows-msvc",
            "cargo install --locked cargo-xwin",
            "缺少 Homebrew 时阻断",
            "xwin 成功仍把 Windows runtime 记为 `Unverified`",
        ),
        rust_baseline: (
            "$check-development-environment",
            "只有 GUI 选择才增加 Node.js 与 pnpm 阻断门禁",
            "example_tool_core = { path = \"example_tool_core\" }",
            "<项目标识>_core",
            "<项目标识>_cli",
            "_tui",
            "_mcp",
            "_gui",
            "所有第三方依赖和工作区内 crate 路径都集中在根",
            "首次脚手架在当前项目根创建 `Cargo.toml`",
            "scaffold status",
            "productDefinitionRequired=true",
            "$define-product",
            "Ratatui + tui-realm + tui-realm-stdlib",
            "React + TypeScript + Mantine UI + TanStack Router + TanStack Query + Jotai",
            "Tokio",
            "Axum",
            "Clap",
            "SeaORM",
            "tracing",
            "anyhow",
            "thiserror",
            "serde",
            "jiff",
            "不表示初始化时把所有依赖无条件写入清单",
            "硬规则例外",
        ),
        PRODUCT_SPEC: (
            "完整目标项目目录路径",
            "目标目录基本名称必须与项目标识一致",
            "唯一项目根目录",
            "CLI/TUI/MCP/GUI",
            "未选择任何接口时默认 CLI",
            "docs/AGENT_POLICY.md",
            "scaffold status",
            "productDefinitionRequired=true",
            "Ratatui",
            "tui-realm-stdlib",
            "Mantine UI",
            "TanStack Router",
            "TanStack Query",
            "Jotai",
            "Tokio",
            "Axum",
            "Clap",
            "SeaORM",
            "tracing",
            "anyhow",
            "thiserror",
            "serde",
            "jiff",
            "固定选型表示“能力出现时采用该技术”",
            "硬规则例外 ADR",
            "独立 Git 仓库",
            "git rev-parse --show-toplevel",
            "main",
            "Skills 地图和约束地图",
            "$prepare-gui-app-identity",
            "400 个物理行",
        ),
        ROOT / "AGENTS.md": (
            "## Skills 地图",
            "## 约束地图",
            "$check-development-environment",
            "$prepare-gui-app-identity",
            "$build-tauri-release",
            "不得继续派生项目",
            "LICENSE.zh-CN.md",
            "LICENSE.en.md",
            "$rename-project-identity",
            "docs/verification/",
            "docs/harness_engineering/",
            "Tokio 异步运行时",
            "Axum HTTP 服务",
            "Clap CLI",
            "SeaORM 关系型数据库 ORM",
            "tracing 可观测性",
            "anyhow 应用边界错误上下文",
            "thiserror 稳定类型化错误",
            "serde 序列化",
            "jiff 日期时间",
        ),
        ROOT / "README.md": (
            "Rust 技术选型固定为 Tokio、Axum、Clap、SeaORM、tracing、anyhow、thiserror、serde 与 jiff",
            "不给中性 scaffold 安装未使用依赖",
        ),
        SKILLS_ROOT / "implement-change" / "SKILL.md": (
            "Tokio、Axum、Clap、SeaORM、tracing、anyhow、thiserror、serde、jiff",
            "只为已批准且存在真实使用路径的能力引入对应依赖",
        ),
        ROOT / "LICENSE.zh-CN.md": (
            "本协议不是开源许可证",
            "终端下游与禁止继续衍生",
            "知识产权",
            "第三方材料",
            "以中文版本为准",
            "适用项目名称：Agent-first Harness 项目模板",
            "仅将该名称替换",
        ),
        ROOT / "LICENSE.en.md": (
            "This is not an open-source license",
            "Terminal Downstream Project; No Further Derivation",
            "intellectual property rights",
            "Third-Party Materials",
            "the Chinese version controls",
            "Applicable Project Name: Agent-first Harness 项目模板",
            "only this name must be replaced",
        ),
        RENAME_IDENTITY_SKILL / "SKILL.md": (
            "--old-display-name",
            "--old-id",
            "--old-kebab",
            "--apply",
            "--rename-root",
            "路径越界",
            "符号链接",
            "LICENSE.zh-CN.md",
            "LICENSE.en.md",
            "残留",
        ),
        RENAME_IDENTITY_SKILL / "agents" / "openai.yaml": (
            "重命名项目身份",
            "$rename-project-identity",
        ),
        RENAME_IDENTITY_SKILL / "scripts" / "rename_project_identity.py": (
            "EXCLUDED_DIRECTORIES",
            "--apply",
        "不允许符号链接",
        "目标已存在",
            "residuals",
        ),
        RENAME_IDENTITY_SKILL / "scripts" / "test_rename_project_identity.py": (
            "test_preview_then_apply_renames_content_paths_and_licenses",
            "test_existing_destination_blocks_without_overwrite",
            "test_symbolic_link_blocks_before_write",
            "test_explicit_root_rename_moves_project_without_overwrite",
        ),
        GITIGNORE: (
            "/target/",
            "**/node_modules/",
            "**/dist/",
            "**/coverage/",
            ".env.*",
            "!.env.example",
            ".DS_Store",
        ),
        ROOT / "docs" / "CLI_CONTRACT.md": (
            "<项目标识>_cli",
            "scaffold status",
            "productDefinitionRequired=true",
        ),
    }
