"""初始化主契约的必需片段。"""

from __future__ import annotations

from pathlib import Path

from .context import *  # noqa: F403


def primary_required_fragments(
    skill_file: Path,
) -> dict[Path, tuple[str, ...]]:
    """返回实例化、初始化和接口能力的主契约片段。"""

    return {
        INSTANTIATE_SKILL: (
            "完整目标项目目录路径",
            "目标目录是必填项",
            "ASCII `snake_case` 项目标识",
            "产品目的、核心输入/输出",
            "可以继续保持未确定",
            "解析后的目标目录基本名称",
            "通过符号链接解析到任何禁止位置的路径",
            "以免将 Harness 复制到其内部目标时发生递归",
            "唯一项目根目录",
            "git --version",
            "git init --initial-branch=main .",
            "git rev-parse --show-toplevel",
            "git symbolic-ref --short HEAD",
            "git rev-parse --verify HEAD",
            "git status --porcelain=v1 --untracked-files=all",
            "git remote",
            "独立的嵌套仓库边界",
            "docs/adr/",
            "docs/changelog/",
            "docs/product_spec/",
            "docs/work_plan/",
            "docs/verification/",
            "历史验证正文",
            "不得仅为实例化创建产品规格、工作计划、ADR、变更记录或 `docs/VERIFICATION.md`",
            "创建恰好一个本地基线提交",
            "不得在经过选择性复制的目标目录中运行模板级 Harness 验证器",
            "LICENSE.zh-CN.md",
            "LICENSE.en.md",
            "逐字节复制两份许可证文件",
            "$desktop-rename-project-identity",
            "整个受维护的目标树",
            "Applicable Project Name",
            "所有其他法律文本必须与复制后的源文件保持字节等价",
            "保留 `$desktop-rename-project-identity` 供未来已批准的产品改名使用",
            "$desktop-run-parallel-worktrees",
            "$desktop-upgrade-harness",
            "推荐预设",
            "自定义",
            "superpowers: disabled",
            "parallel_worktree_subagents: enabled",
            "milestone_smoke: enabled",
            "milestone_e2e: disabled",
            "Harness 源字段值不是下游确认",
            "不得静默采用预设",
            "一次原子写入",
            "不得再次询问预设或各字段",
            "仅属于 Harness 的根目录 `Version.md`",
            "根 `Cargo.toml`",
            ".agents/skills/desktop-initialize-rust-project/assets/gui/macos-dmg-background.png",
        ),
        SKILLS_ROOT / "desktop-instantiate-project" / "agents" / "openai.yaml": (
            "在明确目标目录创建拥有独立 Git 根的干净下游项目",
            "$desktop-instantiate-project",
            "不继承 Harness 开发记忆",
        ),
        skill_file: (
            "$desktop-check-development-environment",
            "只有包含 `GUI` 的选择才增加阻断性的 Node.js 和 pnpm 门禁",
            "完整删除 `.agents/skills/desktop-instantiate-project/` 和 `.agents/skills/desktop-initialize-rust-project/`",
            "完整删除 `.agents/skills/desktop-instantiate-project/` 和 `.agents/skills/desktop-initialize-rust-project/`",
            "## Skills 地图",
            "## 约束地图",
            "workspace = true",
            "只能从 `CLI`、`TUI`、`MCP` 和 `GUI` 中选择",
            "如果用户没有作出选择，则记录 `CLI`",
            "不得静默附加 CLI",
            "docs/AGENT_POLICY.md",
            "推荐预设",
            "自定义",
            "superpowers: disabled",
            "parallel_worktree_subagents: enabled",
            "milestone_smoke: enabled",
            "milestone_e2e: disabled",
            "Harness 源字段值不是下游确认",
            "不得静默采用推荐值",
            "一次原子写入",
            "只验证并复用，不再次询问",
            "$desktop-add-cli-adapter",
            "$desktop-add-tui-adapter",
            "$desktop-add-mcp-adapter",
            "$desktop-add-gui-adapter",
            "_cli",
            "_tui",
            "中性脚手架状态",
            "productDefinitionRequired=true",
            "业务 core 或适配器变化都直接实施",
            "不自动创建 Work Plan、构建候选或完整验收记录",
            "$desktop-define-product",
            "Ratatui + tui-realm + tui-realm-stdlib",
            "Vite + React + TypeScript + Mantine UI + TanStack Router 文件路由 + TanStack Query + Jotai",
            "git --version",
            "git init --initial-branch=main .",
            "git rev-parse --show-toplevel",
            "git status --porcelain=v1 --untracked-files=all",
            "git remote",
            "chore: initialize project",
            "用户现有 Git 身份",
            "不得伪造身份",
            "docs/adr/",
            "docs/changelog/",
            "docs/product_spec/",
            "docs/work_plan/",
            "docs/verification/",
            "不创建或更新 `docs/VERIFICATION.md`",
            "`docs/verification/` 仍然不存在",
            "`docs/harness_engineering/`",
            "只运行初始化本身必需的非空测试",
            "不自动追加格式、lint、静态、全仓门禁",
            "当前项目根目录必须同时是唯一的下游根目录及其独立 Git 顶层目录",
            "项目根目录 `.gitignore`",
            "根锚定的 `/release/`",
            "Tokio current-thread 异步入口",
            "Tauri 由 Tokio 支撑的异步运行时",
            "Tokio、Axum + Tower/Tower HTTP、Clap、SeaORM、config-rs、tracing + tracing-subscriber + tracing-appender、anyhow、thiserror、serde、jiff",
            "OpenTelemetry",
            "不得为中性状态预装未使用的 HTTP、ORM、配置、错误或可观测性依赖",
            "LICENSE.zh-CN.md",
            "LICENSE.en.md",
            "保留继承的两份非开源企业专有商业许可证文件",
            "$desktop-rename-project-identity",
            "$desktop-run-parallel-worktrees",
            "$desktop-upgrade-harness",
            "选择 GUI 时同时完整保留 `$desktop-prepare-gui-support-surfaces`（包括 `assets/brand-support/**`）",
            "不得预创建 `docs/GUI_SUPPORT_SURFACES.md`",
            "Tauri `tray-icon` feature",
            "托盘只包含本地化“显示窗口”和“退出”",
            "主窗口关闭只 `prevent_close()` 后隐藏",
            "`{applicationName} {version} {contactChannel}:{contactValue}`",
            "`/settings`、`/about`、`/sponsor`",
            "底部固定项按视觉顺序为赞助、设置、关于",
            "更新显示 `NotConfigured`",
            "作者、作者联系方式和三段免责声明",
            "完整 `media/sponsor/*`",
            "中性初始化不自动追加格式、lint、静态、全仓门禁、独立构建、冒烟或 E2E",
            "仍包含旧 Harness 身份",
            ".agents/skills/desktop-initialize-rust-project/assets/gui/macos-dmg-background.png",
            "<project-id>_gui/src-tauri/dmg/background.png",
            "bundle.macOS.dmg.background",
            "./dmg/background.png",
            "660×400",
        ),
        ENVIRONMENT_SKILL / "SKILL.md": (
            "只接受两类触发",
            "不得仅因首次修改代码、新任务、新会话、显式构建",
            "门禁成功后只重试原失败命令一次",
            "Rust 始终是常规阻断门禁",
            "仅当已记录的接口选择包含 `GUI` 时，Node.js 和 pnpm 才是常规阻断门禁",
            "必须把两者都报告为 `not-required`",
            "由中性 `$desktop-initialize-rust-project` 调用时",
            "不得为普通开发预建 Verification",
            "本 Skill 及其脚本在下游初始化后必须保留",
            "scripts/macos-tauri-xwin-gates.sh --install-missing",
            "不自动安装 Homebrew",
            "只证明交叉工具可用，不证明 Windows 运行时",
        ),
        GUI_IDENTITY_SKILL: (
            "应用展示名称",
            "主窗口标题",
            "DMG 背景",
            "应用/Applications 落点",
            "自动生成",
            "确定性备选方案",
            "用户上传",
            "1024×1024",
            "docs/GUI_APP_PROFILE.md",
            "$desktop-prepare-gui-support-surfaces",
            "<project-id>_gui/src-tauri/dmg/background.png",
            "SHA-256",
        ),
        SKILLS_ROOT / "desktop-define-product" / "SKILL.md": (
            "中性 scaffold 约束",
            "$desktop-plan-change",
            "$desktop-implement-change",
        ),
        SKILLS_ROOT / "desktop-implement-change" / "SKILL.md": (
            "Git 根/分支和工作区",
            "保护用户已有修改",
            "$desktop-check-development-environment",
            "只运行第 6 步的测试",
            "不得自动追加格式化、lint、静态、集成/契约、全仓测试、构建",
        ),
        SKILLS_ROOT / "desktop-verify-delivery" / "SKILL.md": (
            "源码提交",
            "版本/构建标识",
            "Unverified",
            "项目全部非空单元测试",
        ),
        SKILLS_ROOT / "desktop-build-rust-release" / "SKILL.md": (
            "下游项目根同时是其独立 Git 顶层目录",
            "`HEAD` 解析到真实源码提交",
        ),
        SKILLS_ROOT / "desktop-prepare-release" / "SKILL.md": (
            "独立 Git 顶层目录",
            "尚未生成的 `HEAD`",
        ),
        MCP_SKILL: (
            "不得要求另选目标目录",
            "<project-id>_mcp",
            "Tokio current-thread 异步入口",
            "测量确认的 CPU 密集工作",
            "不得用同步 I/O、休眠、进程等待或 CPU 密集工具工作阻塞 Tokio stdio 运行时",
        ),
        CLI_SKILL: (
            "CLI 是可选项",
            "<project-id>_cli",
            "docs/CLI_CONTRACT.md",
            "Tokio current-thread 异步入口",
            "测量确认的 CPU 密集工作",
            "不得用同步 I/O、休眠、进程等待或 CPU 密集循环阻塞异步运行时",
        ),
        TUI_SKILL: (
            "<project-id>_tui",
            "不要求 CLI",
            "Ratatui",
            "tui-realm",
            "tui-realm-stdlib",
            "硬规则例外",
            "references/tui-baseline.md",
            "Tokio current-thread 异步入口",
            "测量确认的 CPU 密集工作",
            "不得用同步 I/O、休眠、进程等待或 CPU 密集的渲染/数据工作阻塞 Tokio 运行时",
        ),
        TUI_BASELINE: (
            "Ratatui",
            "tui-realm",
            "tui-realm-stdlib",
            "最新兼容稳定组合",
            "硬规则例外 ADR",
            "Tokio current-thread 异步入口",
            "测量确认的 CPU 密集工作",
        ),
        REACT_BASELINE: (
            "Vite",
            "React 和 TypeScript",
            "Mantine UI",
            "TanStack Router",
            "TanStack Query",
            "Jotai",
            "不得把 Query 结果镜像到 Jotai",
            "最新、彼此兼容稳定版本",
            "TypeScript Compiler AST",
            "Vitest",
            "Testing Library",
            "$desktop-prepare-gui-support-surfaces",
            "前端不得持有远程服务或发布者长期秘密",
            "GUI 下游完整保留该 Skill 的品牌源资产",
            "初始化固定建立可收起左侧菜单、`/settings`、`/about`、`/sponsor`",
            "版本在侧栏两种状态和设置页直接可见",
            "底部组按赞助、设置、关于渲染",
            "真实更新、强更或统计上报",
            "作者、联系方式和三段免责声明",
        ),
        GUI_SKILL: (
            "Tauri 基于 Tokio 的单例异步运行时",
            "普通 `async fn` Tauri 命令",
            "测量确认的 CPU 密集工作",
            "缺少完整签名公证条件且渠道允许时",
            "显式生成 `unsigned` 候选",
            "签名、公证与 stapling 必须作为一个阶段完成",
            "$desktop-build-tauri-release",
            "不得要求另选目标目录",
            "<project-id>_gui",
            "Vite、React、TypeScript、Mantine UI、TanStack Router、TanStack Query、Jotai",
            "硬规则例外",
            "references/react-frontend-baseline.md",
            "references/mantine-ui-guidelines.md",
            "check-typescript-chinese-comments.cjs",
            "$desktop-prepare-gui-app-identity",
            "docs/GUI_APP_PROFILE.md",
            "本地拖拽背景",
            "$desktop-prepare-gui-support-surfaces",
            "`tray-icon` feature",
            "托盘只含稳定 ID 的本地化“显示窗口”和“退出”",
            "`WindowEvent::CloseRequested`",
            "`api.prevent_close()`",
            "`{applicationName} {version} {contactChannel}:{contactValue}`",
            "`/settings`、`/about`、`/sponsor`",
            "底部固定组严格为赞助、设置、关于",
            "设置页始终渲染当前应用名/版本",
            "不得信任远端 `forcedUpdate` 布尔值",
            "HTTPS JSON POST",
            "作者、作者联系方式和三段免责声明",
            "不得默认加入自动启动",
            "品牌源资产",
            "<project-id>_gui/src-tauri/dmg/background.png",
            'background: "./dmg/background.png"',
            "applicationFolderPosition: { x: 480, y: 220 }",
        ),
        GUI_BASELINE: (
            "基于 Tokio 的单例异步运行时",
            "普通 `async fn`",
            "缺少签名身份",
            "使用 `--no-sign` 并记录 unsigned",
            "完成公证与 ticket stapling",
            "$desktop-build-tauri-release",
            "cargo-xwin + NSIS",
            "Windows runtime 保持为 `Unverified`",
            "Tauri 2",
            "React + TypeScript",
            "Mantine UI",
            "TanStack Router",
            "TanStack Query",
            "Jotai",
            "Tauri 2 和固定 React 前端技术栈是硬规则",
            "最终签名、公证与 stapling 字节",
            "`.DS_Store`",
            "Tauri `tauri` 依赖启用 `tray-icon` feature",
            "主窗口 `WindowEvent::CloseRequested` 必须 `prevent_close()` 后隐藏",
            "只有托盘退出显式结束应用",
            "`{applicationName} {version} {contactChannel}:{contactValue}`",
            "初始化固定建立可收起左侧菜单与 `/settings`、`/about`、`/sponsor` 文件路由",
            "底部固定组按视觉顺序为赞助、设置、关于",
            "统计上报默认关闭",
            "签名验证不可关闭",
            "作者、作者联系方式和三段免责声明",
            "禁用或未同意时请求数为零",
            "支付二维码是敏感静态媒体",
            "<project-id>_gui/src-tauri/dmg/background.png",
            "./dmg/background.png",
            "应用 `(180, 220)`",
        ),
        GUI_SUPPORT_SKILL: (
            "动态标题、可收起左侧菜单、设置页、关于页与赞助页默认成组存在",
            "`/settings`、`/about` 与 `/sponsor` 是固定路由",
            "底部固定项按视觉顺序为赞助、设置、关于",
            "三段免责声明",
            "docs/GUI_SUPPORT_SURFACES.md",
            "默认 fail-open",
            "禁止 detached task",
            "秘密只能由已批准的安全运行时来源提供",
            "统计上报默认关闭",
            "不得信任远端 `forcedUpdate` 布尔值",
            "HTTPS JSON `POST` body",
            "初始化不得创建 `docs/GUI_SUPPORT_SURFACES.md`",
            "13 个源图片",
            "支付二维码是敏感静态品牌材料",
        ),
        GUI_SUPPORT_REFERENCE: (
            "## 所有权矩阵",
            "`{applicationName} {version} {contactChannel}:{contactValue}`",
            "底部固定组按视觉顺序为赞助、设置、关于",
            "每个远程能力单独记录",
            "生产地址默认 HTTPS",
            "禁用或未同意时请求计数为零",
            "13 个源文件",
        ),
        GUI_SUPPORT_PAGES_REFERENCE: (
            "## 资产包内容",
            "固定侧栏、设置页、关于页、赞助页及其应用导航入口随 GUI 初始化自动建立",
            "作者、联系人、三段免责声明",
            "固定价格是 19、199、1999 CNY",
            "当前品牌包没有视频文件",
        ),
        GUI_SUPPORT_UPDATE_REFERENCE: (
            "## 更新状态机",
            "minimumSupportedVersion",
            "签名验证不可关闭",
            "普通功能导航和业务页面不挂载",
            "## 统计上报同意与固定最小事件",
            "禁止使用 GET/query",
            "撤回同意",
        ),
        MANTINE_GUIDELINES: (
            "每个 React 根只挂载一个 `MantineProvider`",
            "page → surface → section → field → action",
            "Testing Library",
            "WCAG 2.2 AA",
        ),
        TYPESCRIPT_COMMENT_CHECKER: (
            "collectRequirements",
            "parseDiagnostics",
            "EXACT_EXCLUDED_FILES",
            "未发现受中文注释门禁管理的声明",
            "process.exitCode = main()",
        ),
        TYPESCRIPT_COMMENT_CHECKER_TESTS: (
            "accepts governed declarations without requiring locals or inline callbacks",
            "fails closed on parse diagnostics",
            "uses exact generated-file and directory exclusions",
            "fails closed on invalid UTF-8 and source symlinks",
        ),
        E2E_SKILL: ("Computer Use", "完整真实最终产物", "最高风险失败路径"),
    }
